### ISSUE TITLE
start-up-delay-should-be-sufficiently-low.js uses HTML5 "playing" event but that's not what it seems

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#1]
Looking in dpctf-tests/subtests/start-up-delay-should-be-sufficiently-low.js, I noticed that this sets a listener for the HTML5 "playing" event. It has been pointed out by Vewd that this event doesn't actually mean video is being presented and audio is audible. It just means those conditions will happen soon. As I understand it, this event is generated by the browser relating to changes in readyState without any interaction with the OS media playback libraries.

IMHO this test really needs to be measured by the observation framework based on the actual visibility (audibility) of the data.

**Comment by louaybassbouss** [comment]
@jpiesing exactly this is the case we cannot rely on the HTML Video events and we need to make sure via observation Framework that the video is playing and audio is audible. The subtests folder is currently used for internal testing and is currently not bound to any test. We used it to test the report generation process with some programmatic observations. @FritzHeiden  We will add a README.md file to this folder with a notice that these files are used only for internal test purposes.

**Comment by FritzHeiden** [comment]
I pushed a disclaimer README.md to the [subtests](https://github.com/cta-wave/dpctf-tests/tree/master/subtests) directory

**Comment by louaybassbouss** [comment]
thanks @FritzHeiden. @jpiesing if you are happy with this solution feel free to close this issue.

**Comment by jpiesing** [comment]
That's clearer, thank you.
