### ISSUE TITLE
The current state of the video element not visible on the full screen playback

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#10]
From the link https://github.com/cta-wave/dpctf-tests/tree/master/video-evaluation it states that another QR code with information such as current state of the video element on the test page under the video playback.
However, this will not be visible when the playback is full screen.

**Comment by jpiesing** [comment]
A search for "full screen api z order" yielded a number of results that include work-arounds.

https://stackoverflow.com/questions/18578244/displaying-elements-other-than-fullscreen-element-html5-fullscreen-api

https://stackoverflow.com/questions/45798213/firefox-fullscreen-video-append-dom-elements

https://stackoverflow.com/questions/16234740/overlay-on-html5-fullscreen-video

**Comment by louaybassbouss** [comment]
@jpiesing the screenshot in this page https://github.com/cta-wave/dpctf-tests/tree/master/video-evaluation is not final. We can configure the position and size of the QR code. As I remember from previous discussion, there is a placeholder in the video where we can place the QR code on top of it. 

Regarding the fullscreen playback, yes we should try the work-arounds you provided. Maybe in environments where the App runs in fullscreen (e.g. Smart TV, HbbTV, ...) we can make the video fullscreen via CSS (see CSS Snippet below).  

```css
html, body, video {
  margin: 0; 
  padding: 0; 
  width: 100%; 
  height: 100%;
}
``` 
We should keep in mind that in Desktop/mobile Browsers the Fullscreen API requires user gestures which means we cannot fully automate the test session. Some browsers (e.g. chrome, see screenshot below) allow to enter fullscreen manually, in this case the CSS snippet above will work as well. 

![image](https://user-images.githubusercontent.com/1138409/102468295-a0d87100-4051-11eb-91de-b51bb534d10c.png)

@FritzHeiden can you double check that we can easily configure the position and size of QR codes for all tests.

**Comment by jpiesing** [comment]
@louaybassbouss Only one test requires full screen playback in the sense of the W3C Fullscreen API - 8.11. The others can run in a window or indeed a window that happens to be the full size of the browser graphics plane.
@nicholas-fr Can confirm the details about the space left for the QR codes from the application but I believe it's the area to the right of the QR codes burnt into the video.

**Comment by louaybassbouss** [comment]
Thanks @jpiesing agree then we will need to implement the work-arounds for this specific test.

**Comment by jpiesing** [comment]
> Thanks @jpiesing agree then we will need to implement the work-arounds for this specific test.

If the display is 16:9 then your CSS snippet looks OK but what if the display isn't 16:9?

The requirement in the Device Playback spec is written in terms of a "video output window". There's an editorial issue (see https://github.com/cta-wave/device-playback-task-force/issues/63) so you need to look carefully to find how this is defined but it turns out that, for most tests, the video output window is required to be 16:9 to match the video - even on devices where the display is something other than 16:9. I don't think your CSS snippet will achieve this.

This spec issue also contains relevant discussion about what fullscreen means.

https://github.com/cta-wave/device-playback-task-force/issues/75

**Comment by louaybassbouss** [comment]
Thanks @jpiesing for the links.  I created two examples the first one with fullscreen via CSS and a second one via API:

1. Fullscreen via CSS: [source code](https://github.com/louaybassbouss/louaybassbouss.github.io/blob/master/dpctf-tests/video-fullscreen-css.html), [run example](https://louaybassbouss.github.io/dpctf-tests/video-fullscreen-css.html) 
2. Fullscreen via API: [source code](https://github.com/louaybassbouss/louaybassbouss.github.io/blob/master/dpctf-tests/video-fullscreen-api.html), [run example](https://louaybassbouss.github.io/dpctf-tests/video-fullscreen-api.html) 

In both examples, you can click on the video to toggle fullscreen. In the CSS example, you can make the Browser fullscreen manually. Below are screenshots for both options on my Laptop with display resolution 1440 x 900. The output is the same. 

1. Fullscreen via CSS:
![image](https://user-images.githubusercontent.com/1138409/102494774-7b5d5e80-4075-11eb-9ddb-3497b9ef6fc9.png)
2. Fullscreen via API:
![image](https://user-images.githubusercontent.com/1138409/102494911-b2cc0b00-4075-11eb-98cb-dd8e0baf4acf.png)

**Comment by jpiesing** [comment]
@louaybassbouss What's the aspect ratio of your laptop? The black band across the top makes me think it's not 16:9.

**Comment by louaybassbouss** [comment]
> @louaybassbouss What's the aspect ratio of your laptop? The black band across the top makes me think it's not 16:9.

It is not 16/9, my screen resolution is 1440x900.

**Comment by louaybassbouss** [comment]
@jpiesing @yanj-github lets talk about this during our phone call tomorrow.

**Comment by nicholas-fr** [comment]
@louaybassbouss  Regarding the placeholder in the video for the application QR codes, I believe it's as @jpiesing mentioned: to the right of the video. Space was also left above the video for a text string if relevant/useful. 
It isn't pixel accurate, but the reserved areas are illustrated below:

![image](https://user-images.githubusercontent.com/9865551/103573789-202dc780-4ecf-11eb-816b-7264d15a3c86.png)

**Comment by louaybassbouss** [comment]
@FritzHeiden  FYI

**Comment by jpiesing** [comment]
Jan 5th meeting
OK with reserved areas.
The one test that explicitly mentions full screen will use the full screen API and others will not.
Next steps - Fraunhofer to implement, comment & close.

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/105058115-2ea2e400-5a76-11eb-943a-da7754010b85.png)
Setting the video element to the current viewport and overlaying it with the qr code.

In this screenshot the qr code contains the following:
```json
{
  "s": "playing",
  "a": "play",
  "ct": 194.94458,
  "d": 13
}
```

where `s` is the current state, `a` is the last performed action, `ct` is the currentTime of the video at the time the creation of the current qr code was started and `d` the time it took to create the previous qr code

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden  I assume that `d` is in `ms` and `ct` is the currentTime in seconds can you confirm this?

**Comment by FritzHeiden** [comment]
That is correct

**Comment by jpiesing** [comment]
January 19th meeting
What about updating currentTime every (say) 50ms or 100ms?
Now it's done based on timeupdate event
What about generating the QR code (say) 100ms in advance of when it would be needed?
Would requestAnimationFrame help? Not sure this is implemented on all device browsers.

**Comment by louaybassbouss** [comment]
> January 19th meeting
> What about updating currentTime every (say) 50ms or 100ms?
> Now it's done based on timeupdate event
> What about generating the QR code (say) 100ms in advance of when it would be needed?
> Would requestAnimationFrame help? Not sure this is implemented on all device browsers.
> Perhaps use of requestAnimationFrame (or not) could be a configuration option?

@jpiesing your proposed solution requires to use `setTimeout` or `setInterval` to monitor the video currentTime. These 2 functions are not accurate (or not accurate all the time) on TV sets (Tested on a TV set from 2018 that support MSE). If you agree we would like to keep the current approach which is independent from setTimeout` or `setInterval`.

**Comment by jpiesing** [comment]
> @jpiesing your proposed solution requires to use `setTimeout` or `setInterval` to monitor the video currentTime. These 2 functions are not accurate (or not accurate all the time) on TV sets (Tested on a TV set from 2018 that support MSE). If you agree we would like to keep the current approach which is independent from setTimeout`or`setInterval`.

Can you give a short summary of the current approach?
Would an approach based on setTimeout or setInterval be better?
Are there tests in the test suite for WMAS for setTimeout or setInterval?

**Comment by yanj-github** [comment]
@louaybassbouss and @FritzHeiden how often the QR code gets updated please?

**Comment by louaybassbouss** [comment]
> @louaybassbouss and @FritzHeiden how often the QR code gets updated please?

when the state of the video changes (error, play, pause, ...) or `ontimeupdate` (in this case the `ct` value will change. You need to detect in observation framework the first frame where the `ct` value is changed)

**Comment by yanj-github** [comment]
@louaybassbouss can you see the following capture from observation framework please?
index 1735 shows that the playing play comes after many frames from content already shown. If that is because of the delay time to generate QR code I was expecting to see d value. I think the point where the play was executed was not clear to me, I not sure where I can measure the start-up delay from.

_1063 s= waiting a= initialize ct=  d= 
1119 s= buffering a= initialize ct=  d= 
1711 content_id= L2 media_time= 00:00:00.067 frame_num= 2 frame_rate= 30.0
1713 content_id= L2 media_time= 00:00:00.100 frame_num= 3 frame_rate= 30.0
1717 content_id= L2 media_time= 00:00:00.133 frame_num= 4 frame_rate= 30.0
1722 content_id= L2 media_time= 00:00:00.167 frame_num= 5 frame_rate= 30.0
1725 content_id= L2 media_time= 00:00:00.200 frame_num= 6 frame_rate= 30.0
1729 content_id= L2 media_time= 00:00:00.233 frame_num= 7 frame_rate= 30.0
1733 content_id= L2 media_time= 00:00:00.267 frame_num= 8 frame_rate= 30.0
1735 s= playing a= play ct=  d= 
1738 content_id= L2 media_time= 00:00:00.300 frame_num= 9 frame_rate= 30.0
1741 content_id= L2 media_time= 00:00:00.333 frame_num= 10 frame_rate= 30.0
1745 content_id= L2 media_time= 00:00:00.367 frame_num= 11 frame_rate= 30.0
1749 content_id= L2 media_time= 00:00:00.400 frame_num= 12 frame_rate= 30.0
1754 content_id= L2 media_time= 00:00:00.433 frame_num= 13 frame_rate= 30.0
1757 content_id= L2 media_time= 00:00:00.467 frame_num= 14 frame_rate= 30.0
1761 content_id= L2 media_time= 00:00:00.500 frame_num= 15 frame_rate= 30.0
1765 content_id= L2 media_time= 00:00:00.533 frame_num= 16 frame_rate= 30.0
1770 content_id= L2 media_time= 00:00:00.567 frame_num= 17 frame_rate= 30.0
1773 content_id= L2 media_time= 00:00:00.600 frame_num= 18 frame_rate= 30.0
1773 s= playing a= play ct= 0.302244 d= 237
1777 content_id= L2 media_time= 00:00:00.633 frame_num= 19 frame_rate= 30.0
1781 content_id= L2 media_time= 00:00:00.667 frame_num= 20 frame_rate= 30.0
... ..._

**Comment by louaybassbouss** [comment]
> @louaybassbouss can you see the following capture from observation framework please?
> index 1735 shows that the playing play comes after many frames from content already shown. If that is because of the delay time to generate QR code I was expecting to see d value. I think the point where the play was executed was not clear to me, I not sure where I can measure the start-up delay from.
> 
> _1063 s= waiting a= initialize ct= d= 1119 s= buffering a= initialize ct= d= 1711 content_id= L2 media_time= 00:00:00.067 frame_num= 2 frame_rate= 30.0 1713 content_id= L2 media_time= 00:00:00.100 frame_num= 3 frame_rate= 30.0 1717 content_id= L2 media_time= 00:00:00.133 frame_num= 4 frame_rate= 30.0 1722 content_id= L2 media_time= 00:00:00.167 frame_num= 5 frame_rate= 30.0 1725 content_id= L2 media_time= 00:00:00.200 frame_num= 6 frame_rate= 30.0 1729 content_id= L2 media_time= 00:00:00.233 frame_num= 7 frame_rate= 30.0 1733 content_id= L2 media_time= 00:00:00.267 frame_num= 8 frame_rate= 30.0 1735 s= playing a= play ct= d= 1738 content_id= L2 media_time= 00:00:00.300 frame_num= 9 frame_rate= 30.0 1741 content_id= L2 media_time= 00:00:00.333 frame_num= 10 frame_rate= 30.0 1745 content_id= L2 media_time= 00:00:00.367 frame_num= 11 frame_rate= 30.0 1749 content_id= L2 media_time= 00:00:00.400 frame_num= 12 frame_rate= 30.0 1754 content_id= L2 media_time= 00:00:00.433 frame_num= 13 frame_rate= 30.0 1757 content_id= L2 media_time= 00:00:00.467 frame_num= 14 frame_rate= 30.0 1761 content_id= L2 media_time= 00:00:00.500 frame_num= 15 frame_rate= 30.0 1765 content_id= L2 media_time= 00:00:00.533 frame_num= 16 frame_rate= 30.0 1770 content_id= L2 media_time= 00:00:00.567 frame_num= 17 frame_rate= 30.0 1773 content_id= L2 media_time= 00:00:00.600 frame_num= 18 frame_rate= 30.0 1773 s= playing a= play ct= 0.302244 d= 237 1777 content_id= L2 media_time= 00:00:00.633 frame_num= 19 frame_rate= 30.0 1781 content_id= L2 media_time= 00:00:00.667 frame_num= 20 frame_rate= 30.0 ... ..._

@yanj-github for start-up delay you need to detect the first QR Code with `a=play` (this means the previous QR code includes `a=initialize`). This is the time when play() is called on the HTMLVideoElement. 
Regarding `ct`, it gives you the current time reported by the HTMLVideoElement where `d` is the time for creating the previous QR Code. Example from your Logs:

- step `1735` the play is triggered. In order to measure the start-up time, you need to monitor the QR code embedded in the video.  
- step `1773` the current time `0.302244` of the video right before creating the QR Code. In order to consider the time for generating the QR code, you need to wait for the next QR code (step > `1773`) and read the value of `d`.

**Comment by jpiesing** [comment]
> @yanj-github for start-up delay you need to detect the first QR Code with `a=play` (this means the previous QR code includes `a=initialize`). This is the time when play() is called on the HTMLVideoElement.
> Regarding `ct`, it gives you the current time reported by the HTMLVideoElement where `d` is the time for creating the previous QR Code. Example from your Logs:
> 
>     * step `1735` the play is triggered. In order to measure the start-up time, you need to monitor the QR code embedded in the video.
> 
>     * step `1773` the current time `0.302244` of the video right before creating the QR Code. In order to consider the time for generating the QR code, you need to wait for the next QR code (step > `1773`) and read the value of `d`.

If I understand @yanj-github  correct, this cannot be correct as frames 2-8 have already been shown before step 1735.

**Comment by louaybassbouss** [comment]
> If I understand @yanj-github correct, this cannot be correct as frames 2-8 have already been shown before step 1735.

@yanj-github can you explain more the semantic of your logs? I interpreted each line in the log as one recorded/observed frame and not video frame.

**Comment by yanj-github** [comment]
@jpiesing  yes I was meant the play recieved after the serveal frames that already shown. 
@louaybassbouss  
|index of recording| content_id | media_time | frame_num | frame_rate|
|1711| content_id= L2| media_time= 00:00:00.067| frame_num= 2| frame_rate= 30.0|

If I understand you correctly 
1735 s= playing a= play ct= d=
1773 s= playing a= play ct= 0.302244 **d= 237**

d =237 delay means the delay in the creartion of QR code "s= playing a= play ct= d=".

The QR Code with a=play appears toghether with mezzanine QR code with media_time= 00:00:00.267, QR Code with a=play should caculated timed 237ms? 
1733 content_id= L2 **media_time= 00:00:00.267** frame_num= 8 frame_rate= 30.0
1735 s= playing a= play ct= d=

**Comment by louaybassbouss** [comment]
> If I understand you correctly, "s= playing a= play ct= d=" means ct=0?

Yes 
> 1735 s= playing a= play ct= d=
> 1773 s= playing a= play ct= 0.302244 **d= 237**
> 
> d =237 delay means the delay in the creartion of QR code "s= playing a= play ct= d=".

Yes. 

> The QR Code with a=play appears toghether with mezzanine QR code with media_time= 00:00:00.267, QR Code with a=play should caculated back time 237ms?
> 1733 content_id= L2 **media_time= 00:00:00.267** frame_num= 8 frame_rate= 30.0
> 1735 s= playing a= play ct= d=

Yes. 

PS: I recommend to use an observation timeline where you can assign observations to it. What is the framerate of your observation recording? with a higher observation recording framerate you can achieve better accuracy.

**Comment by jpiesing** [comment]
> PS: I recommend to use an observation timeline where you can assign observations to it. What is the framerate of your observation recording? with a higher observation recording framerate you can achieve better accuracy.

My impression is that the first column in comment https://github.com/cta-wave/dpctf-tests/issues/10#issuecomment-780463792 is the frame number of the captured video from the camera - which is essentially the same as an observation timeline. The recording framerate will be the framerate of the camera. Typically 60Hz which is the same frame rate as the video. 

If so then video frames 2-8 (according to the QR code) are found in frames 1711-1733 of the captured video from the camera. All of them before the app generated QR code indicating playing at frame 1735 of the captured video from the camera. Looking at the size of the difference, this suggests that an event is being missed by the test or isn't being generated at all by the browser.

@yanj-github Are my 2 points above correct?

**Comment by yanj-github** [comment]
@jpiesing first column in comment #10 (comment) is frame number of the recording. I have recorded the test with 120fps on the camera. The frame rate of the content that is used for this testing is 30 fps. 

"1735 s= playing a= play ct= d=" is found after 2-8 frames already shown, is because there is a delay in generating a QR code from the test runner which is recorded on the next event "1773 s= playing a= play ct= 0.302244 d= 237". So, we should calculate back the time that it shows a first "a= play" to -237ms. 
The last frame before the 1st "s= playing" has a media_time= 00:00:00.267, take the time of the delay, which is 237ms, this seems about right to me. 

We are still defining the algorithms of each observations based on this information.
And which is going to be shared on device-observation-framework repository once they are ready. 

P.S. the event from test runner (the current time) is not per frame. So that the observation "The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration." will not be measured per frame. However, we are trying to find a way to measure it for every frame, which will be defined on the device-observation-framework repository. This is still in progress.

**Comment by jpiesing** [comment]
> "1735 s= playing a= play ct= d=" is found after 2-8 frames already shown, is because there is a delay in generating a QR code from the test runner which is recorded on the next event "1773 s= playing a= play ct= 0.302244 d= 237". So, we should calculate back the time that it shows a first "a= play" to -237ms.
> The last frame before the 1st "s= playing" has a media_time= 00:00:00.267, take the time of the delay, which is 237ms, this seems about right to me.

Just to check I'm understanding this correctly, "1735 s= playing a= play ct= d=" would have been generated at a media time somewhere around 0.285ms. 0.285-0.237 is 0.048ms which is reasonably before frame no. 1 which was lost.

Is this correct?

**Comment by yanj-github** [comment]
> 
> 
> > "1735 s= playing a= play ct= d=" is found after 2-8 frames already shown, is because there is a delay in generating a QR code from the test runner which is recorded on the next event "1773 s= playing a= play ct= 0.302244 d= 237". So, we should calculate back the time that it shows a first "a= play" to -237ms.
> > The last frame before the 1st "s= playing" has a media_time= 00:00:00.267, take the time of the delay, which is 237ms, this seems about right to me.
> 
> Just to check I'm understanding this correctly, "1735 s= playing a= play ct= d=" would have been generated at a media time somewhere around 0.285ms. 0.285-0.237 is 0.048ms which is reasonably before frame no. 1 which was lost.
> 
> Is this correct?

Yes, your calculation is correct too. 
What I worked out is, 237ms makes it 28-29 number of recording frames up frome where it detected. So "s= playing a= play ct= d=" would have been apear somewhere 1706 -1707. we have 2nd frame of the content detectected 1711. So the start up dealy should be measured from 1706 to 1711 which is around 42ms. 

However, I am thinking if it is possble for the test runner to generate QR code beforehand and just show it when it is needed so we can rule out the delay in QR generation on Test Runer end?

**Comment by jpiesing** [comment]
> However, I am thinking if it is possble for the test runner to generate QR code beforehand and just show it when it is needed so we can rule out the delay in QR generation on Test Runer end?

I think I made this comment more than once :)

**Comment by louaybassbouss** [comment]
> > However, I am thinking if it is possble for the test runner to generate QR code beforehand and just show it when it is needed so we can rule out the delay in QR generation on Test Runer end?
> 
> I think I made this comment more than once :)

This can be easily activated it is only a matter of changing the timing (when to create the QR Code and when to show it). We will activate it to give you the chance to test and compare both approaches. 
The reason why we selected the current approach is because the 'Pre-generate QR Code' method requires `setTimeout(fn, delay)` or `setInterval(fn, delay)` ideally with a `delay` small than the duration of a single frame. Lets consider this example: 

- Lets suppose the video is playing and current position is `ct=15.2`. The test implementation prepares the QR code for `ct=16.0`. 
- The test implementation uses `setInterval(fn, 30)` (`delay=30ms`) to monitor the `video.currentTime` to detect  `ct=16.0`. The drawback of this approach is the accuracy of `setTimeout` or `setInterval` on TV devices. We did tests on some TVs (2017/18 models) and observed this behaviour (JavaScript is single threaded so there is no guarantee that `fn` will be ontime). In some situations we got more than 1s inaccuracy (just 1-2 times for 1min video).

**Comment by yanj-github** [comment]
> 
> 
> > > However, I am thinking if it is possble for the test runner to generate QR code beforehand and just show it when it is needed so we can rule out the delay in QR generation on Test Runer end?
> > 
> > 
> > I think I made this comment more than once :)
> 
> This can be easily activated it is only a matter of changing the timing (when to create the QR Code and when to show it). We will activate it to give you the chance to test and compare both approaches.
> The reason why we selected the current approach is because the 'Pre-generate QR Code' method requires `setTimeout(fn, delay)` or `setInterval(fn, delay)` ideally with a `delay` small than the duration of a single frame. Lets consider this example:
> 
>     * Lets suppose the video is playing and current position is `ct=15.2`. The test implementation prepares the QR code for `ct=16.0`.
> 
>     * The test implementation uses `setInterval(fn, 30)` (`delay=30ms`) to monitor the `video.currentTime` to detect  `ct=16.0`. The drawback of this approach is the accuracy of `setTimeout` or `setInterval` on TV devices. We did tests on some TVs (2017/18 models) and observed this behaviour (JavaScript is single threaded so there is no guarantee that `fn` will be ontime). In some situations we got more than 1s inaccuracy (just 1-2 times for 1min video).

I think OF can calculate time backwards; I am fine with current approach. 
If others have no further question, I am happy to close this issue.

**Comment by jpiesing** [comment]
@yanj-github @louaybassbouss I still don't like this approach but I don't dislike it enough to spend time trying to work out something better. I am happy to close this issue - for now.
