### ISSUE TITLE
Test execution stuck after low-latency-initialization__t2.html test

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/dpctf-tests#102]
Test execution is stuck after this test finishes: `dpcat-local/low-latency-initialization__t2.html`

Page re-direction doesn’t seem to work as it is not possible to run the subsequent test.

Note, this only occurs on this specific test set.

To confirm issue is fixed, please retest using the complete test suite and review results from Observation Framework. OF  version to use is available [here](https://github.com/cta-wave/device-observation-framework/tree/dpcat)

For further details on the issue please see:
[“Eurofins CTA WAVE Test Suite validation of the Observation Framework results including analysis 31 Jan 2023.xls”](https://standards.cta.tech/apps/org/workgroup/dpctf/document.php?document_id=37957)

**Comment by FritzHeiden** [comment]
This was a bug I already fixed, but forgot to regenerate the tests. The test should now redirect properly.

**Comment by jpiesing** [comment]
@rcottingham Can this issue be closed?

**Comment by rcottingham** [comment]
Confirmed fixed during retesting of OF.

Issue closed.
