### ISSUE TITLE
Unable to validate random access (s8.22)

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/dpctf-tests#103]
Unable to validate the following test using the Observation Framework: 
`dpcat/random-access-from-one-place-in-a-stream-to-a-different-place-in-the-same-stream__t2.html`

`random_access_to` parameter needs to be less than the CMAF track duration (_see_ §8.22.3 in the Device Playback Capabilities Specification).

Currently, the track is 30s and `random_access_to` is also set to 30s.

To confirm issue is fixed, please retest using the complete test suite and review results from Observation Framework. OF  version to use is available [here](https://github.com/cta-wave/device-observation-framework/tree/dpcat)

For further details on the issue please see:
[Eurofins CTA WAVE Test Suite validation of the Observation Framework results including analysis 31 Jan 2023.xls](https://standards.cta.tech/apps/org/workgroup/dpctf/document.php?document_id=37957)

**Comment by FritzHeiden** [comment]
I updated the test-config.json by setting `random_access_to` parameter to 15s.

**Comment by rcottingham** [comment]
Hi @FritzHeiden - please can you confirm you have retested this fix using the OF (https://github.com/cta-wave/device-observation-framework/tree/dpcat)? If so, issue can be closed.

**Comment by FritzHeiden** [comment]
I captured the test run so you can check it using the OF
[one-place-to-other_2023-04-14 15-06-32.zip](https://github.com/cta-wave/dpctf-tests/files/11233124/one-place-to-other_2023-04-14.15-06-32.zip)

**Comment by rcottingham** [comment]
Thanks Fritz. Issue can be closed.

N.B. Observation results [13c74aa0-dac5-11ed-8315-0242ac110002.zip](https://github.com/cta-wave/dpctf-tests/files/11261980/13c74aa0-dac5-11ed-8315-0242ac110002.zip) show:

- Many missing frames
- At 15 seconds in the recording, first frame detected after gap 451 doesn't matches expected frame 452

(The OF correctly reports these issues)
