### ISSUE TITLE
Test random-access-to-time__t1.html configuration is incorrect

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/dpctf-tests#104]
Test `random-access-to-time__t1.html` configuration is incorrect. 

Parameter `random_access_time` is currently set to 10, which is on the CMAF Fragment boundary, but as per §8.4.1 in the Device Playback Capabilities Specification, a time other than the start of a CMAF Fragment shall be used.

To confirm issue is fixed, please retest using the complete test suite and review results from Observation Framework. OF  version to use is available [here](https://github.com/cta-wave/device-observation-framework/tree/dpcat)

For further details on the issue please see:
[Eurofins CTA WAVE Test Suite validation of the Observation Framework results including analysis 31 Jan 2023.xls](https://standards.cta.tech/apps/org/workgroup/dpctf/document.php?document_id=37957)

**Comment by FritzHeiden** [comment]
I updated the test-config.json by setting `random_access_time` to 11s.

**Comment by jpiesing** [comment]
@rcottingham Can this issue be closed?

**Comment by rcottingham** [comment]
Hi @FritzHeiden - please can you confirm you have retested this fix using the OF (https://github.com/cta-wave/device-observation-framework/tree/dpcat)? If so, issue can be closed.

**Comment by gitwjr** [comment]
@FritzHeiden Appears the code was changed. Can you confirm that this fix was done and check it works?

**Comment by rcottingham** [comment]
Thanks Fritz. Issue can be closed.

N.B. Observation results ([8044124a-da10-11ed-a5ac-0242ac110002.zip](https://github.com/cta-wave/dpctf-tests/files/11261911/8044124a-da10-11ed-a5ac-0242ac110002.zip)) show many missing frames - this could be a device or recording issue (taken at 60fps, rather than required 120fps).
