### ISSUE TITLE
High number of missing frames in test cfhd_14.985_29.97_59.94/regular-playback-of-chunked-content-non-aligned-append__t2.html

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/dpctf-tests#105]
Many frames are found to be missing in test: `cfhd_14.985_29.97_59.94/regular-playback-of-chunked-content-non-aligned-append__t2.html`

Following frames are missing: 146-167, 172, 296-320, 446-471, 475
Total number missing is 79

Test re-run on PC and same frame numbers are missing. Observation Framework reports the failure correctly.

To confirm issue is fixed, please retest using the complete test suite and review results from Observation Framework. OF  version to use is available [here](https://github.com/cta-wave/device-observation-framework/tree/dpcat)

For further details on the issue please see:
[Eurofins CTA WAVE Test Suite validation of the Observation Framework results including analysis 31 Jan 2023.xls](https://standards.cta.tech/apps/org/workgroup/dpctf/document.php?document_id=37957)

**Comment by FritzHeiden** [comment]
Chunked content currently does not work with the tests properly. See https://github.com/cta-wave/Test-Content/issues/41

**Comment by louaybassbouss** [comment]
> Chunked content currently does not work with the tests properly. See [cta-wave/Test-Content#41](https://github.com/cta-wave/Test-Content/issues/41)

@FritzHeiden you mean this list of test in this comment https://github.com/cta-wave/Test-Content/issues/41#issuecomment-1268587139

**Comment by gitwjr** [comment]
@FritzHeiden to provide recordings to @rcottingham.

**Comment by FritzHeiden** [comment]
@rcottingham recordings can be found here: https://drive.google.com/file/d/1LnNQxGHKDA8Ww9xqvoLP5Hk9i1LggxC1/view?usp=sharing

**Comment by DannyKokkinos** [comment]
Hey @FritzHeiden could you please approve my request to access the recordings from the google drive.

**Comment by FritzHeiden** [comment]
@DannyKokkinos I updated access permissions for the link. Please try again

**Comment by rcottingham** [comment]
No issues with observations of chunked content. Recording provided is for different frame rate family (cfhd_15_30_60) than original issue, but still has missing frames. No further test planned with OF.

**Comment by gitwjr** [comment]
@FritzHeiden @louaybassbouss to determine if this is a result of implementation or the recording and then resolve.

**Comment by jpiesing** [comment]
@louaybassbouss  @FritzHeiden Since chunked content now works, can this be closed? If so, please close it.

**Comment by FritzHeiden** [comment]
Can be closed.
