### ISSUE TITLE
timescale is missing from representations level

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#109]
for test code "ba9a668f3c43b6829919d9c51cbe1b3c" in https://github.com/cta-wave/dpctf-tests/blob/dpcat-2022-10-17/generated/tests.json
representation 6 has "segmentTimeline" but "timescale" is missing.

**Comment by FritzHeiden** [comment]
The dpcat-2022-10-17 branch is outdated. The current tests.json on master branch has timescale parameter for "ba9a668f3c43b6829919d9c51cbe1b3c"
https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json

**Comment by gitwjr** [comment]
@FritzHeiden please fix.

**Comment by FritzHeiden** [comment]
I tried to check whether this issue still exists, however, it seems things have change to the extend that I feel I can't. The mentioned test Id doesn't exist anymore. For any example MPD I look into, the timescale parameter is present. @yanj-github Maybe you could check if timescale parameters are present everywhere you expect them to be, otherwise please hint me to the exact location so I can fix it.

**Comment by yanj-github** [comment]
@FritzHeiden can you check on master branch for test cfhd_14.985_29.97_59.94-online/switching-set-playback__ss1-1.html
last three representations.
e.g: 
`
                            "../../../../chdf_sets/14.985_29.97_59.94/t20/2023-04-28/1": {
                                "period": 1,
                                "duration": 59,
                                "type": "video",
                                "frame_rate": "60/1001",
                                "fragment_duration": 2.002,
                                "segmentTimeline": [
                                    {
                                        "r": 28,
                                        "t": 0,
                                        "d": 120120
                                    },
                                    {
                                        "d": 116116
                                    }
                                ]
                            },
`
It seems that every representations has different segmentTimeline then the base one so additional segmentTimeline is defined in representations level but correspondent timescale is missing.

**Comment by FritzHeiden** [comment]
Thank you for the details. I pushed a fix to master. Please check if there are any issues remaining with the tests.json parameters

**Comment by gitwjr** [comment]
@yanj-github Please check if any remaining issues.
