### ISSUE TITLE
Ability to run a single test is missing

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#11]
Can we have an ability to run a single test please? At the moment Folder1, Folder2 and Folder3 are including multiple tests, but user can not run a single test.

**Comment by louaybassbouss** [comment]
@yanj-github this feature is not supported in the WPT/WAVE Test Runner but is on our Feature List.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss  so the tester will see buttons for the single tests from the landing page? How do the contents link with the test codes?

**Comment by louaybassbouss** [comment]
@yanj-github for now the tester can select the whole folder e.g. [Folder1](https://github.com/cta-wave/dpctf-tests/tree/master/generated/Folder1) which means all tests in this folder will be selected. Once single test selection is implemented, the tests in each folder will be displayed and you can select each test individually (The file names will appear in the UI). The QR codes include the hash code of each test, you can via [tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) all the details of the test.

**Comment by yanj-github** [comment]
For development purpose it would be helpful if we can access the configuration and make changes to run test with different content.

**Comment by louaybassbouss** [comment]
This is how single test selection in the UI looks like. PS: it is still not pushed to git. It needs to be connected to the corresponding REST API. 

![select-single-tests](https://user-images.githubusercontent.com/1138409/106723789-c6243d00-6607-11eb-9f80-2fe23e12a4c1.png)

**Comment by FritzHeiden** [comment]
This feature is now available as part of the new [DPCTF Test Runner release](https://github.com/cta-wave/dpctf-test-runner/releases/tag/v1.0.0)

**Comment by yanj-github** [comment]
Thanks @FritzHeiden  and @louaybassbouss  I can see this feature now. Thank you!

**Comment by jpiesing** [comment]
> Thanks @FritzHeiden and @louaybassbouss I can see this feature now. Thank you!

@yanj-github Can the issue be closed or do you want to do some simple testing first?

**Comment by yanj-github** [comment]
@FritzHeiden  and @louaybassbouss  I just managed to try this out. Selecing and run a single test if working fine now. However, each test only run for 1-2 seconds and move to the next one, just wondering if you have put the debugging configuration back on the last commit please?

**Comment by louaybassbouss** [comment]
Thanks @yanj-github  for testing we will check.

**Comment by FritzHeiden** [comment]
@yanj-github The tests used to only play 1-2 seconds of the test content, however, I already fixed this a while back 977c62f43e3793783c60fd76da8b182bde863706

What content do you use?

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I was using http://dash.akamaized.net/WAVE/vectors/avc_sets/1/stream.mpd.
I just tried to run this again this time I dont see the problem I guess it might be the connection when I test it before. 
As I can not replicate this fault and you have confirmed that is it fixed. I am happy to close this issue now.

**Comment by jpiesing** [comment]
@yanj-github Do you have rights to close issues or do you need someone else to do it?

**Comment by yanj-github** [comment]
@jpiesing I have rights to close it, I have closed this now, let me know if anyone think otherwise please.
