### ISSUE TITLE
creation of aac audio tests

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#111]
This issue is for the creation of the HTML+JS code for the AAC audio tests - referencing the new AAC test content as follows;

http://dash-large-files.akamaized.net/WAVE/vectors/releases/1/

e.g. http://dash-large-files.akamaized.net/WAVE/vectors/releases/1/caaa_sets/aac_lc/at8/2023-04-27/stream.mpd

@yanj-github @rcottingham Please can you help @FritzHeiden with any additional information he needs.

**Comment by FritzHeiden** [comment]
I would need some matrix matching audio content with test template to generate the audio tests from

**Comment by rcottingham** [comment]
Matrix attached [CTA WAVE_AAC Matix_20230428.xlsx](https://github.com/cta-wave/dpctf-tests/files/11464889/CTA.WAVE_AAC.Matix_20230428.xlsx). Note:

- chunked audio content not yet created
- splicing content/tests for Resillion development purposes only at this stage

Note, Resillion are responsible to generate audio tests for 8.2-8.14 (excluding 8.5 as out of scope).
Fraunhofer to generate Section 9 tests.

**Comment by DannyKokkinos** [comment]
Pull request for the aac tests has been made: https://github.com/cta-wave/dpctf-tests/pull/112 
@FritzHeiden  @louaybassbouss

**Comment by yanj-github** [comment]
@FritzHeiden Thanks for getting this done.
Just a quick comment on those section 9 tests:
- 9.2   Regular Playback of a CMAF Presentation
- 9.3 Random Access of a WAVE Presentation
- 9.4   Splicing of WAVE Program with Baseline Constraints

I think, we need to add the audio to exsiting video test not create a new test. 
For example:
"regular-playback-of-a-cmaf-presentation","https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t1/2023-04-28/stream.mpd","https://dash.akamaized.net/WAVE/vectors/releases/1/caac_sets/aac_lc/at1/2023-04-27/stream.mpd","cfhd_15_30_60-online"

And remove:
"regular-playback-of-a-cmaf-presentation","","https://dash.akamaized.net/WAVE/vectors/releases/1/caac_sets/aac_lc/at1/2023-04-27/stream.mpd","caac_sets-online"

**Comment by yanj-github** [comment]
> I updated the tests accordingly. In case of test 9.4, the audio and video segments are not in line, which is expected to cause issue with the audio

@FritzHeiden  https://github.com/cta-wave/device-playback-task-force/issues/111 
is still open for discussion. As far as I understand audio should match video playout.

**Comment by FritzHeiden** [comment]
The audio tests are now merged to master

**Comment by yanj-github** [comment]
@FritzHeiden will you be able to merge playback-over-wave-baseline-splice to have:

9.4 Splicing of WAVE Program with Baseline Constraints:

- video: cfhd_sets/12.5_25_50/splice_main   cfhd_sets/12.5_25_50/splice_ad 
- audio: caac_sets/aac_lc/at13   caac_sets/aac_lc/at14

**Comment by gitwjr** [comment]
Relates to DPCTF Tests #110  . This is on @FritzHeiden list of tasks when checking splicing tests.

**Comment by gitwjr** [comment]
@FritzHeiden to provide recordings to @rcottingham

**Comment by yanj-github** [comment]
Thanks @FritzHeiden are these new audio tests and video audio combined tests been tested and validated on your end please?

**Comment by FritzHeiden** [comment]
Yes they are. I will provide a recording

**Comment by FritzHeiden** [comment]
@rcottingham recordings can be found here: https://drive.google.com/file/d/16U1A8A53zt-B532NOkZnOdX4lzOT6Spe/view?usp=sharing

**Comment by rcottingham** [comment]
Unfortunately, recording does not have audio so unable to run through Observation Framework

**Comment by FritzHeiden** [comment]
> @rcottingham recordings can be found here: https://drive.google.com/file/d/16U1A8A53zt-B532NOkZnOdX4lzOT6Spe/view?usp=sharing

> Unfortunately, recording does not have audio so unable to run through Observation Framework

When I download the linked recordings there is audio present in the video. Could you specify what exactly is the problem?

**Comment by jpiesing** [comment]
@yanj-github I'm OK with closing this. Are you still confident there's nothing left to do under this issue?

**Comment by yanj-github** [comment]
@jpiesing yes please feel free to close this issue. we have issue with 9.4 but we have separate issue created for 9.4 test in general.

**Comment by jpiesing** [comment]
Closing as agreed.
