### ISSUE TITLE
random-access-to-time: is it really testing what is required?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#113]
From https://redmine.hbbtv.org/issues/12118 ...

The whole point of this test is to seek to a time that is not the start of a segment.
Seeking to the start of a segment is covered by random-access-to-fragment.

Is is suggested that the value configured as the seek location "parameters.randomAccessTime", is in fact the start of a segment.
That would make this test redundant and duplicative.

I can't find where this value is configured but please check the configured value and the segment length and confirm if there is a problem.

**Comment by jpiesing** [comment]
Looking in test-config.json, I see the following.

![image](https://github.com/cta-wave/dpctf-tests/assets/8490792/b78ec50c-9700-4508-ac6e-612a4ddaaf1e)

The WAVE test content has segment durations of 2s and 5s so 11s is not the start of a segment.

I will close this issue when the corresponding HbbTV issue is closed.

**Comment by yanj-github** [comment]
This issue has been addressed already https://github.com/cta-wave/dpctf-tests/issues/104

**Comment by gitwjr** [comment]
Closed. Addressed in #104 which was closed.
