### ISSUE TITLE
Test splicing-of-wave-program-with-baseline-constraints__splice_main_splice_ad.html failed in all HbbTV tests

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#114]
This test failed on all HbbTV Terminals during Plugfest.

**Comment by jpiesing** [comment]
@louaybassbouss @FritzHeiden Can this now be closed? If so, please add a short explanation of what the problem was and close it.

**Comment by FritzHeiden** [comment]
This is fixed now. In this test case we have two video MPDs. One of the video MPDs was configured as an audio MPD, which caused the issue.
