### ISSUE TITLE
configuration playout is missing for test playback-over-wave-baseline-splice ... ... at13_at14.html

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#115]
playout parameter is missing for the splice test. At the moment it only plays main not there is no ad.

**Comment by FritzHeiden** [comment]
Thank you for reporting, I pushed a fix. Please check again

**Comment by FritzHeiden** [comment]
> While testing we found another issue on test playback-over-wave-baseline-splice-constraints this test is a section 8 test we dont need audio linked with video. It should contain only video.

I removed audio from this test

**Comment by yanj-github** [comment]
LGTM
