### ISSUE TITLE
new value for maximum permitted start-up delay

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#116]
This is a clone of https://github.com/cta-wave/device-observation-framework/issues/56 moved from the OF project as it wasn't clear to me that this value was set in https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json.

Currently the maximum permitted start-up delay is 120ms.
This needs to be reviewed against the results from the plugfest.
Initial results from @FritzHeiden suggest something in the region of 500-600-700 is average across most (but not all) devices but the worst case is a lot larger. More analysis is needed to see if the same test is the worst case across devices from multiple manufacturers. If this would be the case then the test content and the test would need to be investigated to see if they are correct. If they are correct then that one test may need a tolerance >1.2s.

**Comment by louaybassbouss** [comment]
@jpiesing   these are the average (average across all tests that measure startup delay within a test session) and max startup delays. Each columns a test session on a dedicated device. We can provide the concreted numbers of each test as well if needed.


Average | 471,84 | 290,23 | 365,42 | 392,45 | 708,04 | 1212,80 | 336,91 | 844,28 | 630,01 | 572,94 | 486,51 | 576,00
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Max | 624,67 | 779,33 | 653,00 | 463,67 | 1415,00 | 1514,90 | 1691,33 | 996,33 | 1111,33 | 723,33 | 1414,00 | 1272,33

</body></html></div>

**Comment by jpiesing** [comment]
> @jpiesing these are the average (average across all tests that measure startup delay within a test session) and max startup delays. Each columns a test session on a dedicated device. We can provide the concreted numbers of each test as well if needed.
> Average 	471,84 	290,23 	365,42 	392,45 	708,04 	1212,80 	336,91 	844,28 	630,01 	572,94 	486,51 	576,00
> Max 	624,67 	779,33 	653,00 	463,67 	1415,00 	1514,90 	1691,33 	996,33 	1111,33 	723,33 	1414,00 	1272,33

Very sorry but that's not the question I was asking.
Given the huge difference between Average and Max, I was wondering if the Max was always on the same test or on a small number of tests. If so then the test or the content might have a problem.

**Comment by jpiesing** [comment]
Looking at some data from @FritzHeiden , some obvious values that stand out are around 800ms and 1.0 seconds. In order for all TV sets to pass on all tests, we would need to go as high as 1.7 seconds.

**Comment by poolec** [comment]
For comparison, the HbbTV specification requires a max start-up time of 1 second where no content has yet been decoded (e.g. when starting playback of a new stream) and 250 ms otherwise (e.g. when seeking within a stream).  These figures are conditional on an init segment and one or more CMAF chunks comprising at least 500 ms of media having been appended to the SourceBuffers(s), and the start point being a random access point.  (If the start point is not a random access point, some additional time is allowed).

It would be useful to know if those conditions are satisfied in the CTA test.

The reason for the two figures, 250 ms and 1s, is to allow for implementations that for architectural reasons cannot begin to initialise media decoders until playback is requested to start for the first time.

The precise requirements in HbbTV can be found on page 117 of [ETSI TS 102 796 v1.7.1](https://www.etsi.org/deliver/etsi_ts/102700_102799/102796/01.07.01_60/ts_102796v010701p.pdf).

**Comment by jpiesing** [comment]
Here are the anonymised results from analysing the July 2023 plugfest recordings with >1s highlighted. While one implementation is clearly an outlier, it's quite common for the others to have one-two-three outliers which are >1s and sadly it's not the same one across different implementations. (WAVE participants can get the XLS from https://standards.cta.tech/apps/org/workgroup/dpctf/download.php/39678/DPCTF-HbbTV-Testing-Event-Evaluation-Anonym.xlsx)
![image](https://github.com/cta-wave/dpctf-tests/assets/8490792/5d3f5810-91ad-4753-a6e2-3302b20db528)

I believe these tests are all compatible with the HbbTV requirements as summarised by Chris for "no content has yet been decoded". There is a test for "8.23	Random access from one place in a stream to a different place in the same stream" but that is much newer and wasn't included in the plugfest.

**Comment by haudiobe** [comment]
I am ok to update the spec. I was travelling 3GPP last week and San Diego this week. I will catch up next week.

**Comment by jpiesing** [comment]
> If you disagree with this proposal, please say what you would propose instead. Silence is consent."

This was an email to the DPCTF list on November 2nd. No replies were received therefore changing the value to 1s is approved.

@louaybassbouss @FritzHeiden Please change the value in test-config.json and then close this issue.

**Comment by FritzHeiden** [comment]
Changed value from 120 to 1000 in test-config.json on master branch: https://github.com/cta-wave/dpctf-tests/commit/bf2c98cf0ecfd311edae855714d9ac8d6a6f21d4
