### ISSUE TITLE
Content inappropriate - AAC-LC, HE-AAC, HE-AAC v2

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-tests#119]
I am not 100% sure if the generated audio content is correct. Due to Table 2 – WAVE Audio Media Profiles of CTA-5001-E, the AAC profile includes 3 codecs levels (AAC-LC, HE-AAC, HEAAC v2), but the audio is encoded using the lower level (AAC-LC).
Please consider to create separate audio tracks for each level, or, check if given codec is supported and then  select appropriate track starting from most demanding.

**Comment by louaybassbouss** [comment]
@jpiesing who do you think can check this audio-related issue?

**Comment by Lis-TV** [comment]
I looked for tests which requires any audio check, accordingly to CTA 5003.  These are:
- Switching Set Playback (8.5)
- Overlapping Fragments (8.10)

Here AAC-LC is used only if used(!).

There is no single test where HE_AAC(_v2) audio is played together with video. The main branch has HE-AAC and HE-AAC v2 media, but these are used in tests with audio track only (sequential-track-playback*). I am wondering why audio sequential track playback was developed, if CTA 5003 8.2.5.3 Audio has None ?

**Comment by jpiesing** [comment]
@yanj-github @rcottingham What was in the sparse matrix for the audio codec tests? Is it proposed to test each audio codec with AVC video in tests for sections 9.2/3/4 of the DPCTF specification?

**Comment by rcottingham** [comment]
Hi Jon - sparse matrix has only AAC-LC audio to be used for S9 tests. DPCTF spec states "The WAVE Presentation has at least a Switching Set of type video and one of type audio".

**Comment by jpiesing** [comment]
In the AVC tests, 9.2/3/4 are with AAC-LC video. Are there versions of 9.2/3/4 with Dolby audio?

**Comment by yanj-github** [comment]
> In the AVC tests, 9.2/3/4 are with AAC-LC video. Are there versions of 9.2/3/4 with Dolby audio?

Hi @jpiesing yes we have 9.2/3/4 for Dolby audio.
