### ISSUE TITLE
Finalise Tests related to encrypted content

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#12]
- DPCTF Tests:
  - 8.12 Playback of Encrypted Content
  - 8.13 Restricted Splicing of Encrypted Content
  - 8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content

- Consider Clear Key encryption only
- keyId and contentKey can provided through the test-config.json
- ClearKey Content still missing

**Comment by rbouqueau** [comment]
NB: call Jan 19 2020: one content available with Clear Key would help. We may need to analyze https://github.com/cta-wave/Test-Content-Generation/issues/13 first. Keeping track here.

**Comment by rbouqueau** [comment]
Would a handmade stream already help? Automatizing the process still shows some limitations (listed at https://github.com/cta-wave/Test-Content-Generation/pull/21#issuecomment-776708756).

Also when generating the content, what is the procedure to check it is ok? (e.g. plays back in a specific player, ... ?)

**Comment by jpiesing** [comment]
I don't know if it would help but the HbbTV DASH-DRM reference app has a Java program called 'dasher' which builds on ffmpeg and mp4box and fills in the gaps to generate encrypted content and MPDs including PlayReady and ClearKey. Source code is here. https://github.com/HbbTV-Association/ReferenceApplication/tree/master/tools

**Comment by louaybassbouss** [comment]
> Would a handmade stream already help? Automatizing the process still shows some limitations (listed at https://github.com/cta-wave/Test-Content-Generation/pull/21#issuecomment-776708756).
> 
> 
> 
> Also when generating the content, what is the procedure to check it is ok? (e.g. plays back in a specific player, ... ?)

Handmade is fine for us. How the stream is generated, is not relevant for the test implementation. You can check if stream plays in dash.js reference player.

**Comment by louaybassbouss** [comment]
> I don't know if it would help but the HbbTV DASH-DRM reference app has a Java program called 'dasher' which builds on ffmpeg and mp4box and fills in the gaps to generate encrypted content and MPDs including PlayReady and ClearKey. Source code is here. https://github.com/HbbTV-Association/ReferenceApplication/tree/master/tools

@FritzHeiden @mlasak FYI

**Comment by jpiesing** [comment]
I realised the cloud hosted instance of the HbbTV DASH-DRM reference app obviously includes encrypted streams with PlayReady, Marlin and ClearKey. You probably need to look at it with a debugger to get the URL for the MPDs. If you would use it a lot, it might be better to copy the MPD and the media onto your own server rather than running it off the HbbTV one all the time. It will run on a PC using dash.js.

**Comment by rbouqueau** [comment]
Thanks for the links and ideas.

For the record I initially planned to take the first clear content and make some forward encryption with GPAC: ```gpac -i MANIFEST_URL:forward=man cecrypt:cfile=DRM.xml @ -o encrypted/live.mpd:pssh=mv``` as a first try.

I hope to make a first try before Tuesday eod.

**Comment by rbouqueau** [comment]
I have a first version but how do we plan to get the keys?

I see two ways. Both are quite easy to set up:
1) https://reference.dashif.org/dash.js/v3.2.0/samples/drm/clearkey.html =>we need to provide a custom page for our dash.js player with the protData.
2) Use a clearkey server (https://github.com/Dash-Industry-Forum/dash.js/issues/3343). A partner (e.g. Akamai or Axinom) could provide us with a pair of keys and allow us to make these requests for test purposes.

Do you see other options? What do we prefer?

**Comment by louaybassbouss** [comment]
> I have a first version but how do we plan to get the keys?
> 
> I see two ways. Both are quite easy to set up:
> 
> 1. https://reference.dashif.org/dash.js/v3.2.0/samples/drm/clearkey.html =>we need to provide a custom page for our dash.js player with the protData.
> 2. Use a clearkey server ([Dash-Industry-Forum/dash.js#3343](https://github.com/Dash-Industry-Forum/dash.js/issues/3343)). A partner (e.g. Akamai or Axinom) could provide us with a pair of keys and allow us to make these requests for test purposes.
> 
> Do you see other options? What do we prefer?

Thanks @rbouqueau  can you put the keys in a json file in the same folder e.g. keys.json? If you see an option to put the key in the MPD feel free to it as well. We decided in earlier meetings to keep it very simple without the need for a clearkey server (when the content is downloaded locally, there is no need to call external server). @jpiesing wdyt?

**Comment by jpiesing** [comment]
> Thanks @rbouqueau can you put the keys in a json file in the same folder e.g. keys.json? If you see an option to put the key in the MPD feel free to it as well. We decided in earlier meetings to keep it very simple without the need for a clearkey server (when the content is downloaded locally, there is no need to call external server). @jpiesing wdyt?

Avoiding an external server would be better if we can. We want to keep this simple to setup. If putting them in a json file doesn't work then can we have an HTML page hosted on the PC running the test control UI?

**Comment by rbouqueau** [comment]
Let me know if any decision is taken regarding this AP. Once again it should be quite straightforward to implement once we make a decision.

**Comment by louaybassbouss** [comment]
> Let me know if any decision is taken regarding this AP. Once again it should be quite straightforward to implement once we make a decision.

@rbouqueau if we can put the keys in a json file (e.g. keys.json) in the same folder of the MPD file? If yes, let's go for this option.

**Comment by rbouqueau** [comment]
@louaybassbouss Yes it is possible by adding some js (which I can do).

Auto-quote:

> we need to provide a custom page for our dash.js player with the protData.

@all Do you have any preference or can I rely on [this player page for encrypted content](https://reference.dashif.org/dash.js/v3.2.0/samples/drm/clearkey.html)? If your tests depends on URL parameters or some feedback/logs from the [sample player](https://reference.dashif.org/dash.js/v3.2.0/samples/dash-if-reference-player/index.html) (e.g. dropped frames...) then a discussion should occur first about the integration (and maybe we should ask Daniel for advice).

Let me know.

**Comment by FritzHeiden** [comment]
Implementation of encrypted content support is done. I generated a test with encrypted content based on test 8.12 in the [cenc](https://github.com/cta-wave/dpctf-tests/tree/master/generated/cenc) sub folder.

**Comment by louaybassbouss** [comment]
> Implementation of encrypted content support is done. I generated a test with encrypted content based on test 8.12 in the [cenc](https://github.com/cta-wave/dpctf-tests/tree/master/generated/cenc) sub folder. The keys are specified in the [`test-config.json`](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json)

Thanks @FritzHeiden 👍 . @rbouqueau FYI the content we used is the same you provided in this [example](https://reference.dashif.org/dash.js/v3.2.0/samples/drm/clearkey.html). @FritzHeiden copied the required parameters in the [test-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json) file manually. This means you can still provide the parameters in a JSON file as discussed above and will take care that these parameters are copied to the right place (this will be done in the test generation script).

**Comment by rbouqueau** [comment]
Ok I packaged [this](https://www.gpac-licensing.com/downloads/CTA-Wave/encrypted/stream.mpd).

The parameters are: ```"J5kmSWp_XSXaafKzsnmafw": "ABEiM0RVZneImaq7zN3u_w"```.

There is more to do to make this automatic.

**Comment by louaybassbouss** [comment]
> Ok I packaged [this](https://www.gpac-licensing.com/downloads/CTA-Wave/encrypted/stream.mpd).
> 
> The parameters are: `"J5kmSWp_XSXaafKzsnmafw": "ABEiM0RVZneImaq7zN3u_w"`.
> 
> There is more to do to make this automatic.

Thanks @rbouqueau this is great we will test and let you know

**Comment by FritzHeiden** [comment]
> Ok I packaged [this](https://www.gpac-licensing.com/downloads/CTA-Wave/encrypted/stream.mpd).

Just tried to use it in a test and it seems to work just fine.

**Comment by louaybassbouss** [comment]
thanks @rbouqueau can you also generate the content with 2 representations the first one is encrypted and the second one is the same content but not encrypted. This is required for [8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content (pages 51-52)](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5003-final.pdf).

**Comment by rbouqueau** [comment]
New content uploaded with the ```-senc``` suffix e.g. https://dash.akamaized.net/WAVE/vectors/avc_sets/t1-cenc/stream.mpd or https://dash.akamaized.net/WAVE/vectors/avc_sets/ss1-cenc/stream.mpd

**Comment by louaybassbouss** [comment]
> New content uploaded with the `-senc` suffix e.g. https://dash.akamaized.net/WAVE/vectors/avc_sets/t1-cenc/stream.mpd or https://dash.akamaized.net/WAVE/vectors/avc_sets/ss1-cenc/stream.mpd

Thanks a lot @rbouqueau great work 👍  we will start testing beginning of next week and keep you updated

**Comment by jpiesing** [comment]
@louaybassbouss Where is this in your backlog? (This is a just a request for understanding, not a suggestion to change your priorities).

**Comment by louaybassbouss** [comment]
> @louaybassbouss Where is this in your backlog? (This is a just a request for understanding, not a suggestion to change your priorities).

@jpiesing  moved to the top of the backlog. you should get feedback by today regarding the new CENC content from database.json

**Comment by FritzHeiden** [comment]
The `database.json` didn't seem to contain the cenc MPDs. However, I discovered https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ contains directories called `*-cenc` with content in it. So I tried to use these MPDs in the tests. Unfortunately every of these MPDs are invalid XML syntax, which the MPD parser of the player cannot parse. It looks like a namespace issue.

**Comment by rbouqueau** [comment]
@FritzHeiden Thanks for reporting. I'll investigate this issue.

**Comment by louaybassbouss** [comment]
> @FritzHeiden Thanks for reporting. I'll investigate this issue.

Thanks @rbouqueau can you also include the CENC tests in database.json with `zipPath`.

**Comment by FritzHeiden** [comment]
@rbouqueau I am also not sure which of the two URLs to use for the `database.json` or how they differ. Sometimes the `zipPath` key is missing, currently in the second one.

https://dash-large-files.akamaized.net/WAVE/vectors/database.json  
https://dash.akamaized.net/WAVE/vectors/database.json

Could you please elaborate on that?

**Comment by rbouqueau** [comment]
@FritzHeiden The cache policy on the server leads to this. I already mentioned that it creates a lot of confusion. We shoud use another server for hosting more dynamic content. Or we should make sure we never rewrite on an existing URL.

**Comment by rbouqueau** [comment]
Fixed. I uploaded it yesterday night but the cache is still not updated. We need a way to version the content if we need to update it sometimes.

**Comment by rbouqueau** [comment]
I put a local copy (so that you see) here: http://www.gpac-licensing.com/downloads/CTA-Wave/Test-Content/. Don't use it for production.

**Comment by louaybassbouss** [comment]
Thanks a lot @rbouqueau we will test the new content and let you know

**Comment by FritzHeiden** [comment]
> I put a local copy (so that you see) here: http://www.gpac-licensing.com/downloads/CTA-Wave/Test-Content/. Don't use it for production.

@rbouqueau Could you post a link to an MPD file here? I can't seem to find any cenc content on the page you provided.

**Comment by rbouqueau** [comment]
ss1: https://dash-large-files.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1-cenc/stream.mpd

t1: https://dash-large-files.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t1-cenc/stream.mpd

**Comment by FritzHeiden** [comment]
> ss1: https://dash-large-files.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1-cenc/stream.mpd
> 
> t1: https://dash-large-files.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t1-cenc/stream.mpd

From these links I derived the links for the other content. I have the following issues:

Content hosted on dash-large-files.akamaized.net domain could not be played due to CORS policies. Additionally, t15, t30 still had XML parsing errors.

As the CORS errors prevented me from further testing, I tried content hosted on dash.akamaized.net:

- t3, t15, t17, t20, t23, t24, t30, t33, ss1 had XML parsing errors.
- dash reference play couldn't play any content due to missing PSSH box
- I could play most of the content in the tests, except for t2, t14, t16
   - firefox it plays a little, then freezes without error
   - chromium showed the following error: `CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf`

**Comment by rbouqueau** [comment]
Let's discuss tomorrow about how to work around the caching issues. We are all losing time here because we are not certain to be working on the latest content.

**Comment by jpiesing** [comment]
See https://github.com/cta-wave/Test-Content/issues/15

**Comment by FritzHeiden** [comment]
I tested the new encrypted content with the timestamp. There still seems to be some content with the aforementioned error `CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf`: t1, t2, t3, t14, t15, t16

**Comment by jpiesing** [comment]
> I confirm that encrypting + audio&video causes an issue (a crash in the ClearKey CDM module after 14 seconds, in Windows and Linux, in Chrome/Chromium and Firefox). I need to better understand that.
> 
> Video only (encrypted) is ok.
> 
> Video encrypted + audio in clear is not ok.

@rbouqueau Is there anything I can do to help you? Is there someone I could chase?

**Comment by rbouqueau** [comment]
@jpiesing Thanks, we are waiting for Daniel's insights at the moment.

**Comment by dsilhavy** [comment]
We checked the content. I think the issue is not the encryption but rather a minor mistake in the MPD. In the audio AdaptationSet the timeline looks like this:
````
    <SegmentTimeline>
     <S t="0" d="88064" r="6"/>
     <S t="0" d="89088"/>
     <S t="0" d="88064" r="6"/>
     <S t="0" d="89088"/>
     <S t="0" d="88064" r="5"/>
     <S t="0" d="89088"/>
     <S t="0" d="88064" r="5"/>
     <S t="0" d="89072"/>
    </SegmentTimeline>
````
S@t is set to 0 for all of the entries which is not correct. It should look like this:
````
    <SegmentTimeline>
     <S t="0" d="88064" r="6"/>
     <S d="89088"/>
     <S d="88064" r="6"/>
     <S d="89088"/>
     <S d="88064" r="5"/>
     <S d="89088"/>
     <S d="88064" r="5"/>
     <S d="89072"/>
    </SegmentTimeline>
```` 
 
Otherwise it breaks the time calculation in dash.js. Additional question: Any reasons to not use the aligned segment length here (1.92 seconds) ?
 
Best
Daniel

**Comment by rbouqueau** [comment]
It should work. Would you please validate the fix?

**Comment by FritzHeiden** [comment]
I just ran a test and it looks good

**Comment by jpiesing** [comment]
If you're both OK then please close the issue. I can't run the test for a different reason.

**Comment by louaybassbouss** [comment]
LGTM as well closing this issue
