### ISSUE TITLE
re-generate tests with most recent content to fix illegible QR codes

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#120]
@FritzHeiden @louaybassbouss Have you regenerated the tests with the most recent test content from Romain that fixes https://github.com/cta-wave/Test-Content-Generation/issues/64 and https://github.com/cta-wave/Test-Content-Generation/issues/63? If not, please can you do so. This is now the largest cause of failures.

**Comment by FritzHeiden** [comment]
I updated the content and regenerated the tests

**Comment by jpiesing** [comment]
> I updated the content and regenerated the tests

If you can re-run the same 26 tests on the same Philips TV as in July and share the recording with me then that will help move thing forwards. I'm very nervous about errors from the QR code recognition masking other errors.

**Comment by louaybassbouss** [comment]
@FritzHeiden will run the tests and observation on Phillips TV today

**Comment by jpiesing** [comment]
I confirm this is resolved in recordings since the start of October.
