### ISSUE TITLE
long-duration-playback tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#121]
Current long-duration-playback tests doesn’t link with long duration content yet.
However, from OF point of view, when we testing actual long duration content, we suggest user to run long-duration-playback tests on its own without having it together in same recording with other tests. This is because it took quite long to process longer duration test on OF.  Also makes it easier to manage the storage and debugging. I suggest separating out long duration test on its own instead of having it inside same folder with other tests. 
Any objection please? Feel free to comment if you think otherwise.

**Comment by jpiesing** [comment]
I agree. 
How does this impact the project? Is this just a documentation issue or is there a technical change somewhere?

**Comment by yanj-github** [comment]
From user's prospetive,
To run all test other than long duration, user requires to select a test group they want, e.g: cfhd_12.5_25_50-local then find long duration test and de-select it:
![image](https://github.com/cta-wave/dpctf-tests/assets/59022223/8d72b510-b389-496d-9112-99bc0656953c)
To run a long duration test find expected long duration test and select it and run. 

I think it would be better to have long duration test in seperate folder on test generation so user does not have to exclude it.

**Comment by jpiesing** [comment]
@FritzHeiden In the screendump from @yanj-github above, long duration playback is in the same set as all the other AVC tests. Is it practical to either;
- Move it into a different set on its own?
- Have it default to unchecked or somehow prompt the user to re-confirm?

**Comment by louaybassbouss** [comment]
@jpiesing  move it into a different set on its own is simple. I discussed this option yesterday with @FritzHeiden . The second option requires more time and changes in the UI. I propose to go with the first option and move to its own dataset?

**Comment by jpiesing** [comment]
> @jpiesing move it into a different set on its own is simple. I discussed this option yesterday with @FritzHeiden . The second option requires more time and changes in the UI. I propose to go with the first option and move to its own dataset?

Whatever is the easiest way to avoid people running long duration playback by accident.

**Comment by FritzHeiden** [comment]
I moved the long duration tests into separate groups

**Comment by yanj-github** [comment]
It looks good to me. If no further comments this can be closed.

**Comment by jpiesing** [comment]
> It looks good to me. If no further comments this can be closed.
