### ISSUE TITLE
amend AVC sparse matrix & generate stand-alone tests for 50/60 and 12.5/15 

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#124]
While the majority of our streams are 25/30 Hz, we have streams for 50/60 and 12.5/15 but they are only used in the switching set tests. There is no stand-alone test that exercises these with as few other complicating factors as possible.

I believe we should create new tests with the 'sequential track playback' template and streams t20 (1080p50/60, AVC 4.2), t23 (720p50/60, AVC 4.0) and t34 (480x270p12.5/15).

These will be very useful to eliminate possible causes when the switching set playback tests have problems.

**Comment by FritzHeiden** [comment]
We already have these tests, we didn't ran them at hbbtv events, as they are not specified to be part of hbbtv tests.

**Comment by jpiesing** [comment]
> We already have these tests, we didn't run them at hbbtv events, as they are not specified to be part of hbbtv tests.

The number of failures on the switching set tests make me think they need to be run.

**Comment by jpiesing** [comment]
I have confirmed that both [sequential-track-playback__t34.html](https://github.com/cta-wave/dpctf-tests/blob/master/generated/cfhd_12.5_25_50-local/sequential-track-playback__t34.html) and [sequential-track-playback__t20.html](https://github.com/cta-wave/dpctf-tests/blob/master/generated/chdf_12.5_25_50-local/sequential-track-playback__t20.html) exist under "generated" in this repo.

It's up to me to create an HbbTV .xml file for these two.
