### ISSUE TITLE
"message": "Script error.", 

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#126]
What should be done about these?

            "message": "Script error.", 
            "message": "Script error.", 
            "message": "Script error.", 

How significant are they?

**Comment by louaybassbouss** [comment]
This is raised on an HbbTV set and not to be related to the test. The test results are not affected by this.

**Comment by jpiesing** [comment]
> This is raised on an HbbTV set and not to be related to the test. The test results are not affected by this.

Is it reasonable to catch this instead of generating an error in the test report? This error will be very confusing to people.

**Comment by louaybassbouss** [comment]
> > This is raised on an HbbTV set and not to be related to the test. The test results are not affected by this.
> 
> Is it reasonable to catch this instead of generating an error in the test report? This error will be very confusing to people.

It is not possible since the error is triggered by the HbbTV UA on only a TV set and not from the testing code. We know this error from the other HbbTV dev on the specific TV.

**Comment by gitwjr** [comment]
The script errors cannot be caught. Needs to be documented that some implementations generate the error.  @louaybassbouss Fraunhofer to document in test execution section of Deploy. @louaybassbouss

**Comment by gitwjr** [comment]
Fixed.
