### ISSUE TITLE
"Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'."

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#127]
What should be done about these?

            "message": "Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.", 
            "message": "Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.", 
            "message": "Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.", 

How significant are they?

**Comment by louaybassbouss** [comment]
@jpiesing this error does not have effect on the test since video `ended` event is triggered before and the test is considered as completed. This test result are affected.

**Comment by jpiesing** [comment]
> @jpiesing this error does not have effect on the test since video `ended` event is triggered before and the test is considered as completed. This test result are affected.


Is it reasonable to catch this instead of generating an error in the test report? This error will be very confusing to people.

**Comment by FritzHeiden** [comment]
This is now fixed. https://github.com/cta-wave/dpctf-tests/pull/136

**Comment by gitwjr** [comment]
Closed. Reopen when the test is run on the device concerned if needed.
