### ISSUE TITLE
Audio only splicing tests not working

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#128]
All of audio only splicing tests not working and I have got following error.
Ch108:	promise_test: Unhandled rejection with value: object "Error: No representation of type video found!"
Audio only tests do not require video.

**Comment by yanj-github** [comment]
"caac_sets-local/playback-over-wave-baseline-splice-constraints__at13_at14.html"
"caac_sets-local/restricted-splicing-of-encrypted-content-https__at15_at16.html"
"caac_sets-local/sequential-playback-of-encrypted-and-non-encrypted-baseline-content-https__at15_at14.html"

**Comment by yanj-github** [comment]
ac4-local/playback-over-wave-baseline-splice-constraints__at3_at4.html works fine. And other caac tests work fine too.  
It seems that combination of caac and splicing test issue.

**Comment by gitwjr** [comment]
@FritzHeiden  Need to verify if this issue is fixed.

**Comment by louaybassbouss** [comment]
@FritzHeiden PR for new audio-only tests is merged in master. Can you check if "combination of caac and splicing test" (https://github.com/cta-wave/dpctf-tests/issues/128#issuecomment-1820660628) if is fixed

**Comment by FritzHeiden** [comment]
The tests work fine for me, @yanj-github can you check?
