### ISSUE TITLE
Show currentTime  on a  QR  code

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#13]
Sorry if I have missed if this had been discssed before. 
But from what I can see here: https://github.com/cta-wave/dpctf-tests/tree/master/video-evaluation, and on the Test Runer the currentTime is not shown on the QR code. 
I just wanted to check if this will be implemented please?

**Comment by louaybassbouss** [comment]
@yanj-github the currentTime is included @FritzHeiden will share details about it. The documentation page needs to be updated.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss that is great to know. 
I have one more question about the QR code.
The QR code overlayed on the content is inverted QR code which has black background. However, the QR code on the test runner is different. 
Will it be better to have them consistent please?

**Comment by louaybassbouss** [comment]
> The QR code overlayed on the content is inverted QR code which has black background. However, the QR code on the test runner is different.
> Will it be better to have them consistent please?

yes it makes sense @FritzHeiden can you configure this in the QR code library we use.

**Comment by louaybassbouss** [comment]
@yanj-github FYI @FritzHeiden add a comment to this [issue](https://github.com/cta-wave/dpctf-tests/issues/10#issuecomment-762934906) about currentTime

**Comment by yanj-github** [comment]
@louaybassbouss  Can you kindly confirm this is already implemented and updated on github please? I still cannot see it on my set up. If it is already implemneted I will try again with the latest change. Thanks.

**Comment by FritzHeiden** [comment]
The current time of the video is included in the overlayed qr code under the key `ct`.

**Comment by jpiesing** [comment]
> The current time of the video is included in the overlayed qr code under the key `ct`.

For the mezzanine content, the same string that is included in the QR code is also available as text for human beings including debugging. Is this practical here as well?

**Comment by yanj-github** [comment]
Thanks @louaybassbouss  and @FritzHeiden I can see "ct" now.

**Comment by louaybassbouss** [comment]
@yanj-github can you confirm that we can close this issue?

**Comment by yanj-github** [comment]
@louaybassbouss yes please close this issue.
