### ISSUE TITLE
eac3 tests are not working

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#130]
When running eac3 tests I have following error:
promise_test: Unhandled rejection with value: object "Error: Unsupported MIME types or codecs: | audio/mp4; codecs="eac3"

I think it might be caused by the issue https://github.com/cta-wave/dpctf-test-runner/issues/32

However, ac4 tests are working fine.

**Comment by louaybassbouss** [comment]
@yanj-github the test reads the mimetype or codec string from the mpd and checks if the browser supports it using `MediaSource.isTypeSupported(mimeType)`. If you check the MPDs of [EAC3](https://dash.akamaized.net/WAVE/vectors/releases/1/ceac_sets/eac3/at1/2023-10-13/stream.mpd) and [AC4](https://dash.akamaized.net/WAVE/vectors/releases/1/ca4s_sets/ac4/at1/2023-08-01/stream.mpd) contents, you can see the mimeType and codec reported in each MPD as following:

* EAC3:
![image](https://github.com/cta-wave/dpctf-tests/assets/1138409/71c20a9f-61fa-48ff-a0c5-39740390af86)
* AC4: 
![image](https://github.com/cta-wave/dpctf-tests/assets/1138409/ab076193-092b-4756-9f55-a71eb63b2e03)

Maybe the codec string of EAC3 content ist not correct? In this case, you need to fix it in the MPD and provide new content.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss we will have a look.

**Comment by yanj-github** [comment]
@FritzHeiden  and @louaybassbouss 
https://github.com/cta-wave/dpctf-deploy/pull/51
https://github.com/cta-wave/dpctf-tests/pull/131
Can you please review the pull request and merge when you happy with the changes please?

**Comment by louaybassbouss** [comment]
@yanj-github  PR is merged

**Comment by yanj-github** [comment]
@FritzHeiden  and @louaybassbouss can we get this merged as well please? Otherwise local test wont work with correct content.
https://github.com/cta-wave/dpctf-deploy/pull/51
