### ISSUE TITLE
Make QR code generated in the Test inline with QR embedded in the content

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#14]
Currently the QR code generated in the Test has a different foreground/background Black/White colors as the QR embedded in the content. The Test implementation needs to be updated to generate QR codes in the same format as for QR codes embedded in the content.

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/106485995-79c6e900-64b1-11eb-8dc0-641bcd7da209.png)

This is now implemented.

**Comment by yanj-github** [comment]
I can see this had been implemented but I just founded that the start of the test QR code is not inverted, is it on your to do list please? If not can we get the start of the test QR inverted too please? Thank you!

**Comment by louaybassbouss** [comment]
@yanj-github  yes @FritzHeiden is going to fix the start QR code as well.

**Comment by FritzHeiden** [comment]
Inverted QR code of pre test page is now implemented.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden the QR codes looks all good to me.

**Comment by louaybassbouss** [comment]
This issue can be closed during the Testing meeting.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss  yes happy to close it please.

**Comment by jpiesing** [comment]
Closing as agreed by involved parties.
