### ISSUE TITLE
buffer-underrun-and-recovery__t2.html failed on all except 1 TV in London plugfest

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#149]
/cfhd_12.5_25_50-local/buffer-underrun-and-recovery__t2.html failed the observation "[OF] Video: The presented sample shall match the one reported by the currentTime value within the tolerance of +/-(2/framerate + 20ms)" on 6 of 8 TV sets in the London plugfest and failed to even run on a 7th.

**Comment by jpiesing** [comment]
https://github.com/cta-wave/device-playback-task-force/issues/122 could be all or part of the problem.

**Comment by jpiesing** [comment]
There's something wrong with the duration calculation here @yanj-github .

2169 - 2nd frame should be detectable for the first time
3351 - frame 248 visible for the first time which is the frame shown thoughout the underrun
3621- frame 249 first detectable
6473 - last (red) frame first detectable

Duration excluding 4 frames that may be displayed for longer than normal =((6473-4069)+(3351-2169))/120 = 29.8833333

Duration corrected for 4 frames at 40ms = 30.04333333

The error message from the OF is as follows;

FAIL: Playback duration 35955.0ms does not match expected duration 30000.0ms. Detected duration is different by 5955.0ms. Minimum waiting durationn is 3862.67ms, and Maximun waiting duration is 3879.33ms. Allowed tolerance is 50ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 0..

I accept the OF may be a correct implementation of the DPCTF spec but in that case, the spec is wrong.

**Comment by yanj-github** [comment]
Spec change https://github.com/cta-wave/device-playback-task-force/issues/122 and OF code change https://github.com/cta-wave/device-observation-framework/issues/78 required.

**Comment by jpiesing** [comment]
https://github.com/cta-wave/device-playback-task-force/issues/126 also applies here.

**Comment by jpiesing** [comment]
2024-05-14: Can we close this one? The behaviour mentioned by Fritz below looks like a TV implementation bug.

> On some TVs I noticed when reaching the end of the buffer, while video playback stopped the current time was still updated for some short time. When continuing playback, the ct either jumped back to the correct value or did not change until the video playback caught up to that point.

**Comment by jpiesing** [comment]
2024-05-14: Closed.
