### ISSUE TITLE
Content that played has no QR code

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#15]
The content that is played on Test Runner has no annotation. 
When the latest content is ready (QR code has frame rate), can you update it to point to the latest content please?

**Comment by louaybassbouss** [comment]
@yanj-github we updated the [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv) file and new tests with one of the new content with QR code. There is a new folder [avc](https://github.com/cta-wave/dpctf-tests/tree/master/generated/avc) in the generated folder with the corresponding tests. In the Test Runner companion page, please select `avc` to these tests. 

To use custom generated tests, simply checkout this repository, modify [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv) or create a new file and generate the new tests:
```
./generate-tests.py <csv-file> <dest>
```
e.g.
```
./generate-tests.py custom.csv generated
```

Then copy the generated test folders into the test runners directory (`/home/ubuntu/DPCTF`) inside the docker container:

```
docker cp <src> <container>:<dest>
```
e.g.
```
docker cp generated/Custom dpctf:/home/ubuntu/DPCTF
```

Then restart the container:

```
docker restart dpctf
```

To interactively access the container you may run the following:

```
docker exec -ti dpctf /bin/bash
```

**Comment by louaybassbouss** [comment]
@yanj-github can we close this issue in the Testing Meeting tomorrow?

**Comment by jpiesing** [comment]
@louaybassbouss Please could you share a screendump / picture showing the the QR codes and the text written by the app?

**Comment by louaybassbouss** [comment]
> @louaybassbouss Please could you share a screendump / picture showing the the QR codes and the text written by the app?

Yes @FritzHeiden will share during the day a screenshot.

**Comment by yanj-github** [comment]
@louaybassbouss Thats for getting this done. Now, I can see the avc folder and be able to run the test. I will be able to change the input contents internally as well. 
However, we are blocked on the content that is on AVC folder, wihch was not generated with latest Mezzanine so the frame rate information is missing.

**Comment by jpiesing** [comment]
> However, we are blocked on the content that is on AVC folder, wihch was not generated with latest Mezzanine so the frame rate information is missing.

You can get the script from the test-content-generation project and run it yourselves against the latest Mezzanine. Alternatively someone else may be able to run it for you.

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/106484602-17211d80-64b0-11eb-8f25-c6f3c8124afc.png)

The QR code is positioned and scaled relative to the actual video inside the video element and contains the following:

```json
{
  "s": "buffering",
  "a": "initialize",
  "ct": "60.033333,
  "d": 34
}
```

Where `s` is the current state, `a` is the current action, `ct` is the current time of the video and `d` is the duration it took to create the QR code.

**Comment by yanj-github** [comment]
> 
> 
> > However, we are blocked on the content that is on AVC folder, wihch was not generated with latest Mezzanine so the frame rate information is missing.
> 
> You can get the script from the test-content-generation project and run it yourselves against the latest Mezzanine. Alternatively someone else may be able to run it for you.

Thanks @jpiesing Yes, I can do this for our testing. But I tink the contents need to be updated anyway on https://dash.akamaized.net/WAVE/vectors/avc_sets/
I have rised issue on the Test-Content repositry. 
https://github.com/cta-wave/Test-Content/issues/10

**Comment by louaybassbouss** [comment]
@yanj-github  please confirm that this issue can be closed during our Testing meeting today.

**Comment by yanj-github** [comment]
@louaybassbouss  Yes it is fine to close it. Thanks
