### ISSUE TITLE
random-access-from-one-place-in-a-stream-to-a-different-place-in-the-same-stream__t2.html

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#154]
In the London plugfest, the following observations for this test failed on 7 of 8 TV sets and the test failed to run on the 8th.
* [OF] Every video frame S[k,s] shall be rendered and the video frames shall be rendered in increasing presentation time order.
* [OF] Video: The playback duration shall match the duration of the CMAF Track

**Comment by jpiesing** [comment]
I think this is an OF bug.

**Comment by yanj-github** [comment]
Spec change request: https://github.com/cta-wave/device-playback-task-force/issues/124
OF code change is required: https://github.com/cta-wave/device-observation-framework/issues/75

**Comment by jpiesing** [comment]
Closing as OF code change seems to work.
