### ISSUE TITLE
Result API not working

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#16]
I cannot get the following API working and getting 500 internal server error.
https://github.com/cta-wave/dpctf-test-runner/blob/master/tools/wave/docs/rest-api/results-api/import.md#2-import-api-results
It says "If enabled, the WMAS Test Runner can import results exported by any arbitrary other instance."
It is might be because this feature is not enabled?

**Comment by louaybassbouss** [comment]
@yanj-github can you provide the following information of the HTTP POST Request:
* HTTP Endpoint 
* HTTP Request Headers
* HTTP Body (JSON content)

We will check in our side and come back to you.

**Comment by yanj-github** [comment]
I was looking at the code and it has a flag import_results_enabled but cannot figure out where this is set?

**Comment by FritzHeiden** [comment]
This configuration parameter has no impact on the endpoint you are having issues with. 

I am unable to reproduce your issue. Please check the server logs for any error messages. You can view them by using `docker logs -f <container>` e.g. `docker logs -f dpctf`

**Comment by louaybassbouss** [comment]
@yanj-github please provide the following information of the HTTP POST Request

> * HTTP Endpoint
> * HTTP Request Headers
> * HTTP Body (JSON content)

**Comment by yanj-github** [comment]
> 
> 
> @yanj-github please provide the following information of the HTTP POST Request
> 
> > * HTTP Endpoint: http://web-platform.test:8000/_wave/api/results/4ab7c268-6224-11eb-8c15-080027138d0d/test/json
> > * HTTP Request Headers: {'Accept' : 'application/json', 'Content-Type' : 'application/json'}
> > * HTTP Body (JSON content): 
{
    "results": [
        {
            "status": "OK", 
            "test": "/test/sequential-track-playback-manual__stream__.html", 
            "subtests": [
                {
                    "status": "PASS", 
                    "message": null, 
                    "name": "video ended event fired"
                }
            ], 
            "message": null
        }
    ]
}

**Comment by FritzHeiden** [comment]
From your logs I can see that the directory for your sessions result reside in does not exist. Can you confirm that the path `results/ac48e856-6538-11eb-a1f8-080027138d0d/test` exist in your filesystem?

In case the directory exists, can you confirm the following:

- You can read the existing results using the API e.g. `GET  /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json`
- You can run tests from the avc directory and read its results
- You can import results for the avc tests

**Comment by yanj-github** [comment]
> 
> 
> From your logs I can see that the directory for your sessions result reside in does not exist. Can you confirm that the path `results/ac48e856-6538-11eb-a1f8-080027138d0d/test` exist in your filesystem?
> 
> In case the directory exists, can you confirm the following:
> 
>     * You can read the existing results using the API e.g. `GET  /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json`
> 
>     * You can run tests from the avc directory and read its results
> 
>     * You can import results for the avc tests

yes I can download result by GET /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json

**Comment by FritzHeiden** [comment]
> Can you confirm that the path `results/ac48e856-6538-11eb-a1f8-080027138d0d/test` exist in your filesystem

Can you please check this? I think this might be a problem with the directory's permissions. However, in that case you should have seen an OSError 13 in your servers logs.

**Comment by yanj-github** [comment]
The path ~/DPCTF/results is empty.

**Comment by FritzHeiden** [comment]
In that case, to confirm the test runners expected behavior, you should get a 404 when performing a `GET /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json` request after restarting the server.

**Comment by yanj-github** [comment]
> 
> 
> In that case, to confirm the test runners expected behavior, you should get a 404 when performing a `GET /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json` request after restarting the server.

After docker restarted:
`GET /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/test/json` give me 500
`GET /_wave/api/results/ac48e856-6538-11eb-a1f8-080027138d0d/json`  I did get result and response 200 but I am getting empty zip file.

**Comment by yanj-github** [comment]
@FritzHeiden and @louaybassbouss Just came across the configuration file https://github.com/cta-wave/dpctf-deploy/blob/master/config.json
Dose "enable_results_import": false," have to be set to true please?

**Comment by FritzHeiden** [comment]
This also seems like there are problems with the result directory due to missing permissions. What operating systems do you use? On unix like systems you should set the owner and group of the results directory to 1000. Can you check if this is the case? Otherwise, please change the owner and group and check if the previous 500 errors still occur.

**Comment by FritzHeiden** [comment]
> @FritzHeiden and @louaybassbouss Just came across the configuration file https://github.com/cta-wave/dpctf-deploy/blob/master/config.json
> Dose "enable_results_import": false," have to be set to true please?

As mentioned before, this configuration parameter has no impact on the endpoint you are trying to use.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden set the owner and group of the results directory to 1000 resolved issue. 
Do I need to change this after each time that I built the new docker please?

**Comment by jpiesing** [comment]
> Thanks @FritzHeiden set the owner and group of the results directory to 1000 resolved issue.
> Do I need to change this after each time that I built the new docker please?

Please can this get added to the documentation?

**Comment by FritzHeiden** [comment]
Glad to hear this fixed your issue. I will update the documentation accordingly.

As docker inherits the ownerships from your local filesystem, it will suffice to set it once.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden for helping to solve this issue and @jpiesing is it good idea to document it. 
I am happy to close this issue once this is documented.

**Comment by FritzHeiden** [comment]
Documentation is already updated, see https://github.com/cta-wave/dpctf-deploy
