### ISSUE TITLE
Playback of sequential-track-playback-manual 

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#17]
Apologize that this might not be the test runner issue, but I think this maybe related. 

Regarding to the sequential-track-playback-manual of the content wave_avc_sets_1, I have noticed that the playback is in order of Representations in the MPD file. I can see the playback order is O1, O2, O3, N1, M1 then L1.
The details of the content can be found here: https://dash.akamaized.net/WAVE/vectors/database.json

I guess what the Test Runner is doing for the sequential track playback tests is playing one Representation from start to finish. Then picking the next Representation and playing that, and so on.

However, I do not think it taken the device capability into account. This might be a problem when a device does not support the part of the resolution or framerate. Device might support one resolution but not the other.

**Comment by jpiesing** [comment]
Devices

**Comment by jpiesing** [comment]
This is a bug in the test content and in the definition of the combinations of tests & test content.
https://github.com/cta-wave/Test-Content-Generation/issues/13

8.2 should only be run with MPDs that have exactly one representation.
If 8.2 is run with an MPD with >1 representation then playing all representations is a bug.
Random access (8.3) may have a similar problem.

**Comment by louaybassbouss** [comment]
@yanj-github  @jpiesing can we close this issue since it related to content generation and not test implementation?

**Comment by jpiesing** [comment]
> @yanj-github @jpiesing can we close this issue since it related to content generation and not test implementation?

It sounds to me like there's a test bug as well if the test code will play each representation in an MPD sequentially when there's more than one.

**Comment by louaybassbouss** [comment]
> > @yanj-github @jpiesing can we close this issue since it related to content generation and not test implementation?
> 
> It sounds to me like there's a test bug as well if the test code will play each representation in an MPD sequentially when there's more than one.

@FritzHeiden can you check this and confirm that the test plays only a single representation?

**Comment by FritzHeiden** [comment]
The playout parameter was wrongly applied to all tests. With the latest changes it should only be applied to tests that require it. The sequential track playback test now only plays the first video representation from the provided mpd.

**Comment by louaybassbouss** [comment]
@yanj-github  can you confirm that is now playing properly on your side and we can close this issue?

**Comment by yanj-github** [comment]
> 
> 
> The playout parameter was wrongly applied to all tests. With the latest changes it should only be applied to tests that require it. The sequential track playback test now only plays the first video representation from the provided mpd.

thanks @FritzHeiden  I just tried a /avc/sequential-track-playback-manual__stream__.html with the latest code and I am getting test stoped half way the **Duration 00:00:09** with the following result. 
5 time update events fired	PASS
Playback starts	PASS

**Comment by yanj-github** [comment]
Hi @FritzHeiden The generated folder seems that it still not updated and it has "5 time update events", so I have regenerated and copy paste generated/avc folder to the docker now I am getting error "dpctfTest.asyncTest is not a function" I cannot find where this is defined. Can you help please?

**Comment by FritzHeiden** [comment]
Hi @yanj-github, when you copy the new generated files, you would also have to copy the lib directory. This would have fixed the "dpctfTest.asyncTest is not a function" error you got. However, indeed I forgot to update the generated directory. I pushed the updated to the repository now. When I build the image everything works fine for me. Can you please check if this also resolves the issue for you?

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I can see O1 is played back from start to end for the sequential-track-playback-manual now. 
I am happy to close this issue.

**Comment by louaybassbouss** [comment]
Thanks @yanj-github for the feedback feel free to close the issue
