### ISSUE TITLE
Enhancing usability for end-user.

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-tests#171]
Propose to include set of commands and steps to allow deploy HbbTV tests branch, to have fully operational solution.
Assume the starting point is that the user is inside dpctf-deploy folder, with running docker image ( successful installation dpcf-deploy project).
The starting point:

> python3 -m pip install six
> python3 -m pip install isodate
> git clone -b hbbtv-tests https://github.com/cta-wave/dpctf-tests
....

**Comment by jpiesing** [comment]
> Propose to include set of commands and steps to allow deploy HbbTV tests branch, to have fully operational solution. Assume the starting point is that the user is inside dpctf-deploy folder, with running docker image ( successful installation dpcf-deploy project). The starting point:
> 
> > python3 -m pip install six
> > python3 -m pip install isodate
> > git clone -b hbbtv-tests https://github.com/cta-wave/dpctf-tests
> > ....

The current preference is to point people at the dpctf-deploy repo. Only real power users and rocket scientists should run tests from dpctf-tests. IMHO the only reason for a normal user to install dpctf-tests is if they need to examine the code and work out what's going on.

**Comment by FritzHeiden** [comment]
To use the hbbtv tests branch use the corresponding parameter when building the image:

```
./build.sh master latest --tests-branch hbbtv
```

**Comment by Lis-TV** [comment]
dpctf-deploy works fine, however it carries all CTA tests. 
I am looking for a way to allow people find, configure and use HbbTV test set in convenient way. For testing guys usage git is a problem...
Fritz - the command is fine, but it is not implicitly mentioned in dpctf-deploy, people even dont know that there is hbbtv branch.
Fritz, is it possible to create document/paragraph in dpctf-deploy with HbbTV specific set of commands?
After that we could add link to it on our systems (Redmine, Test spec, tech.cta.wave* XML files, link in https://www.hbbtv.org/resource-library ) to

**Comment by FritzHeiden** [comment]
> EDIT: We have a test runner issue for making it easier to run subsets of tests.
> [cta-wave/dpctf-test-runner#47](https://github.com/cta-wave/dpctf-test-runner/issues/47)

This has an implementation with hbbtv subset: https://github.com/cta-wave/dpctf-test-runner/issues/47#issuecomment-2104843583

**Comment by jpiesing** [comment]
The underlying issue of making it easier for people to use the HbbTV tests is addressed in a different way as explained above. 

I think the original proposal is "WONTFIX". There is no interest in making it easier for people to use dpctf-tests directly avoiding dpctf-deploy. 

I think this one can be closed.

**Comment by jpiesing** [comment]
2024-05-14: Closed on the basis of the recent work by @FritzHeiden
