### ISSUE TITLE
report 'a: close' via QR code

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#173]
Here is an analysis of a failing test from the London test event.

![image](https://github.com/cta-wave/dpctf-tests/assets/8490792/9f7d5e2d-e029-4046-b5ef-2be4fc572328)

a: reports values initialize, play, pause and representation_change

This test is failing because the last (red) frame is never shown.

This is very hard to analyse because there's no information available about whether/when/if MediaSource.endOfStream was called.

MediaSource.endOfStream not being called for any reason is IMHO the most likely reason for the last frame not being called.

Please consider modify the closeBuffer method to send 'a: close' (or a: endOfStream' if you prefer) so it's clear what is happening.

**Comment by FritzHeiden** [comment]
This is now implemented. https://github.com/cta-wave/dpctf-tests/pull/174

**Comment by louaybassbouss** [comment]
@jpiesing  can this be closed?

**Comment by jpiesing** [comment]
> @jpiesing can this be closed?

Yes.
