### ISSUE TITLE
how many tests.json file & how does the observation framework find them?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#2]
Redme.md says;

> The test generator script will be extended to generate a tests.json file that containts the IDs of all generated files. This allows us to get the test path/filename from the test ID embedded in the QR Code. The following example shows the structure of the generated tests.json file:

How many tests.json files will there be? 
- One per media profile?
- One per set of tests which may (or may not) be the same as a media profile?
- Potentially more than one per media profile depending on when the tests were generated?
- One for each release of the WAVE test suite?

One one hand keeping the number of tests.json files down keeps things simple.
On the other hand, if someone wants to add their own tests then this shouldn't be too complex even though very few people will do it.

**Comment by louaybassbouss** [comment]
@jpiesing there is only one `tests.json` file which will be auto-generated from the input csv file. It can be seen as a lookup table to get tests information from the MD5 hash (test ID). 
Do you mean by "...if someone wants to add their own tests..." is to update the csv file. In this case, the test generator script needs to be executed and a new tests.json will be generated.

**Comment by jpiesing** [comment]
> @jpiesing there is only one `tests.json` file which will be auto-generated from the input csv file. It can be seen as a lookup table to get tests information from the MD5 hash (test ID).

@louaybassbouss But if each WAVE media profile has its own input.csv file?

**Comment by louaybassbouss** [comment]
> @louaybassbouss But if each WAVE media profile has its own input.csv file?
@jpiesing  you can define multiple media profiles in a single csv file by specifying a folder name for each media profile (see [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv)). You can later select one or multiple folders (media profiles) in the configuration UI of the test session.

**Comment by jpiesing** [comment]
> > @louaybassbouss But if each WAVE media profile has its own input.csv file?
> 
> @jpiesing you can define multiple media profiles in a single csv file by specifying a folder name for each media profile (see [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv)). You can later select one or multiple folders (media profiles) in the configuration UI of the test session.

My mental model was that each media profile would have its own .csv file.

**Comment by louaybassbouss** [comment]
> > > @louaybassbouss But if each WAVE media profile has its own input.csv file?
> > 
> > 
> > @jpiesing you can define multiple media profiles in a single csv file by specifying a folder name for each media profile (see [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv)). You can later select one or multiple folders (media profiles) in the configuration UI of the test session.
> 
> My mental model was that each media profile would have its own .csv file.

Our proposal was to have a single csv file but we are open to split to multiple csv files if needed. lets take a decision during the call later.

**Comment by jpiesing** [comment]
> > > > @louaybassbouss But if each WAVE media profile has its own input.csv file?
> > > 
> > > 
> > > @jpiesing you can define multiple media profiles in a single csv file by specifying a folder name for each media profile (see [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv)). You can later select one or multiple folders (media profiles) in the configuration UI of the test session.
> > 
> > 
> > My mental model was that each media profile would have its own .csv file.
> 
> Our proposal was to have a single csv file but we are open to split to multiple csv files if needed. lets take a decision during the call later.

Whether there's one or more than tests.json, the observation framework needs to find it (or them).

**Comment by louaybassbouss** [comment]
> > > > > @louaybassbouss But if each WAVE media profile has its own input.csv file?
> > > > 
> > > > 
> > > > @jpiesing you can define multiple media profiles in a single csv file by specifying a folder name for each media profile (see [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv)). You can later select one or multiple folders (media profiles) in the configuration UI of the test session.
> > > 
> > > 
> > > My mental model was that each media profile would have its own .csv file.
> > 
> > 
> > Our proposal was to have a single csv file but we are open to split to multiple csv files if needed. lets take a decision during the call later.
> 
> Whether there's one or more than tests.json, the observation framework needs to find it (or them).

Exactly the `tests.json` file will be served via test runner http server `http://ip:port/path/to/tests.json` and can be accessed by the observation framework on-the-fly.

**Comment by yanj-github** [comment]
Regardless of tests.json numbers observation framework needs to find them if there is a way to reference them or find them all. Maybe we can search all .json files from the "generated" folder. Test Runner server and Observation frame work can be co-located or observation framework can be made to check out shared folder "generated".

**Comment by louaybassbouss** [comment]
> Regardless of tests.json numbers observation framework needs to find them if there is a way to reference them or find them all. Maybe we can search all .json files from the "generated" folder. Test Runner server and Observation frame work can be co-located or observation framework can be made to check out shared folder "generated".

@yanj-github you can find an example of the [tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) in the [generated](https://github.com/cta-wave/dpctf-tests/blob/master/generated) folder

**Comment by jpiesing** [comment]
Proposal was discussed in the November 30th test runner call. It was agreed that there would be one tests.json file but that there may be multiple tests.csv files as input from the media profile proponents. A new issue will be created for the latter.
