### ISSUE TITLE
Test Runner does not work on IOS

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#20]
Test Runner failed to playback any tests on IOS with given error message "Can't find variable: MediaSource".
I think IOS safari does not support MediaSource on JS. I have tried on google chrome app on IOS which giving me same error.

**Comment by jpiesing** [comment]
MSE isn't implemented on iOS on iPhone. It is implemented on iPads with OS 13 and later. See

https://caniuse.com/mediasource

Test Runner is not going to work on iPhones or older iPads.

I recommend closing this issue.

**Comment by yanj-github** [comment]
Thanks @jpiesing to confirm. I am closing this issue now.
