### ISSUE TITLE
consider replacing peak black and peak white backgrounds with something in the middle

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#201]
We've seen that cameras take time to adjust when the display switches from a peak black background with white text or a peak white background with black text to the test material. For the particular case of peak black backgrounds used at the start of a test, this causes problems when the test starts as the white in the QR codes is over-exposed and burnt out.
Please consider replacing the peak black and peak white backgrounds with a grey background somewhere in the middle.

**Comment by louaybassbouss** [comment]
@jpiesing are these tests audio-only? If yes, we noticed also this behaviour and our idea to use a suitable background image of the video element (maybe using [video.poster](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#poster)).

**Comment by jpiesing** [comment]
> @jpiesing are these tests audio-only? If yes, we noticed also this behaviour and our idea to use a suitable background image of the video element (maybe using [video.poster](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#poster)).

Well the white text and/or QR code on a majority black background and black text on a white background are common to all tests. I don't have a strong opinion about using a picture vs using a plain mid-grey background. Anything that 1) reduces a white QR code on a black background being almost burnt-out and 2) reduces the first second(s) of video being burnt out before the camera adjusts.

![image](https://github.com/user-attachments/assets/d5091123-a11e-4d62-b6cc-a31d73e43c98)

![image](https://github.com/user-attachments/assets/b33fe0f3-b717-455c-8cbe-fbca6efac0d7)

**Comment by louaybassbouss** [comment]
Something like this?

<img width="984" alt="image" src="https://github.com/user-attachments/assets/345fcef7-0c74-4141-bd86-4692bf4312ee">

**Comment by jpiesing** [comment]
> Something like this?
> <img alt="image" width="984" src="https://private-user-images.githubusercontent.com/1138409/379670236-345fcef7-0c74-4141-bd86-4692bf4312ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTY5MTUsIm5iZiI6MTcyOTc1NjYxNSwicGF0aCI6Ii8xMTM4NDA5LzM3OTY3MDIzNi0zNDVmY2VmNy0wYzc0LTQxNDEtYmQ4Ni00NjkyYmY0MzEyZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDc1NjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlkMTZlYjIxOGQzNzA5MDllOWUwMzk1NWYyZTE0MjA3NTliZDE3ZWI4ZDZjYTA1Mzc5YTBiMjI3NjQ4ZmYyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u8FleiFfbPztYcamfzo5E8d35MocBpui2sNGFYD90RE">

That's the less critical one but, yes, that will certainly avoid the camera having its sensitivity turned down to the maximum.

**Comment by louaybassbouss** [comment]
yes this was something I can quickly do in the browser dev console, but yes it should be applied to both pages. We will do it.

**Comment by yanj-github** [comment]
@louaybassbouss In case you have used autofocus on camera try use manual focus next time it will help.

**Comment by louaybassbouss** [comment]
@yanj-github We disabled all automatic features on the camera, including auto-focus, but this still occurred.

**Comment by jpiesing** [comment]
Has this been done, both for "next test is about to start" and for the video element before any video is displayed?

**Comment by louaybassbouss** [comment]
> Has this been done, both for "next test is about to start" and for the video element before any video is displayed?

@jpiesing yes in all pages. I think we can close this issue
