### ISSUE TITLE
delay is missing for the last current time event

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#21]
On the recording position 8951 I was expecting to see delay value defined for the previous current time event. 
The delay seems missing. 
8951 s= paused a= play ct=  d= ?
Please see the following capture result. 

... ...
8883 content_id= L2 media_time= 00:00:59.900 frame_num= 1797 frame_rate= 30.0
8887 content_id= L2 media_time= 00:00:59.933 frame_num= 1798 frame_rate= 30.0
8891 content_id= L2 media_time= 00:00:59.967 frame_num= 1799 frame_rate= 30.0
8895 content_id= L2 media_time= 00:00:60.000 frame_num= 1800 frame_rate= 30.0
8909 s= playing a= play ct= 59.917232 d= 91
8951 s= paused a= play ct=  d= 
8971 s= ended a= play ct=  d=

**Comment by louaybassbouss** [comment]
@FritzHeiden can you check this?

**Comment by FritzHeiden** [comment]
I pushed an updated. The delay is now always included.

**Comment by louaybassbouss** [comment]
@yanj-github feel free to close this issue if it solved on your side.

**Comment by yanj-github** [comment]
Thanks for getting this fixed @FritzHeiden  and @louaybassbouss  I will check soon.

**Comment by yanj-github** [comment]
checked and the delays are present.
