### ISSUE TITLE
sequential track playback test alters between 2 representations

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#23]
I am trying to run avc/sequential-track-playback-manual__stream__.html with the latest code.
However, the sequential track playback test alters between 2 representations for every 6 seconds O2-L2-O2-L2... ....

Could you try clean build the test runner from the latest code in github and see if you are seeing the same problem please?

**Comment by louaybassbouss** [comment]
Thanks @yanj-github we will check and let you know

**Comment by yanj-github** [comment]
This might related to recent content change I used local content which downloaded before the change doesnt show this issue. Hope this will help to investigate.

**Comment by louaybassbouss** [comment]
@yanj-github I cannot see this behaviour on our side but @FritzHeiden will check on Tuesday if he can reproduce this issue. 
PS: Monday is holiday in Germany!

**Comment by FritzHeiden** [comment]
I built the latest image and ran the sequential track playback test with the avc content. I am unable to reproduce your issue. Please make sure you use the latest image

**Comment by yanj-github** [comment]
> 
> 
> I built the latest image and ran the sequential track playback test with the avc content. I am unable to reproduce your issue. Please make sure you use the latest image

Which content did you used? I was running this one. https://dash.akamaized.net/WAVE/vectors/avc_sets/1/stream.mpd

**Comment by louaybassbouss** [comment]
> > I built the latest image and ran the sequential track playback test with the avc content. I am unable to reproduce your issue. Please make sure you use the latest image
> 
> Which content did you used? I was running this one. https://dash.akamaized.net/WAVE/vectors/avc_sets/1/stream.mpd
> the playback alters between O1 and L2, dash js player does the same.

Yes this is the content we tested. As mentioned before, the implementation of the sequential track considers only the first representation in the MPD. Since the content avc_sets/1/stream.mpd has 8 video representations, any DASH player e.g. dash.js will select the representation based on the current conditions (Bandwidth, ...) on the used ABR algorithm.

**Comment by yanj-github** [comment]
That is strange I think you have fixed this issue and only playsback 1st representation from mpd. 
I have tried to remove container and image and rebuild the test runner however I am still seeting this problem.

**Comment by FritzHeiden** [comment]
@yanj-github Where do you run the tests? On a TV or desktop browser? Did you clear any caches? Maybe look into the network logs to see what segments are being loaded

**Comment by yanj-github** [comment]
> Did you clear any caches? Maybe look into the network logs to see what segments are being loaded

Hi @FritzHeiden  I have tried on local. Which caches do you mean? I think I did clean rebuild the test runner. Is there anything else that i need to clean please? I think it might be caches.

**Comment by yanj-github** [comment]
I have done the complete rebuild and clean all the cache. Now this is not a problem anymore. 
Thanks @FritzHeiden
