### ISSUE TITLE
terminology - test = html+js or html+js+media?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#3]
The proposal for the tests.json file is inconsistent in how it uses "test".
It uses "tests" (plural) to refer to each combination of HTML+JS+media - which I think is correct.
Is uses "test" singular to refer to HTML+JS without media.

Perhaps you could consider changing the following;

      "test": "Folder1/fullscreen-playback-of-switching-sets-manual_ToS_MultiRate_fragmented.html"

to

      "code": "Folder1/fullscreen-playback-of-switching-sets-manual_ToS_MultiRate_fragmented.html"

**Comment by louaybassbouss** [comment]
@jpiesing  yes completely agree we should use `code` instead `test`

**Comment by jpiesing** [comment]
This was agreed in the November 30th test runner call.
@louaybassbouss Please close this issue here when you've finished implementation & tested it.

**Comment by louaybassbouss** [comment]
@jpiesing  now it is fixed in the test generator script. This [tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) file provides an example. I will close this issue
