### ISSUE TITLE
Check manual/automatic tests and update filenames

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#33]
To check if there are manual DPCTF tests and remove 'manual' from filenames if these tests are automatic. This is related to issue https://github.com/cta-wave/dpctf-deploy/issues/9 .

**Comment by FritzHeiden** [comment]
Test file names are now renamed to no longer include the -manual annotation.

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden ... @jpiesing this issue can be closed if ok for you

**Comment by yanj-github** [comment]
If this means test codes are changed then OF requires same changes. 
Issue is raised here:
https://github.com/cta-wave/device-observation-framework/issues/13

**Comment by louaybassbouss** [comment]
> If this means test codes are changed then OF requires same changes.
> Issue is raised here:
> [cta-wave/device-observation-framework#13](https://github.com/cta-wave/device-observation-framework/issues/13)

@yanj-github  only filenames are changed (`manual` removed from all filenames). These changes are also reflected in the config files e.g. test-config.json and /generated/tests.json. You need to only rename these filenames if you use them in the OF.
