### ISSUE TITLE
consider making length of DPCTF tests a session option

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#34]
Currently the DPCTF tests all play for 60s, in line with the mezzanine content that has a red frame at the end.
We should consider allowing the test engineer to over-ride the length so that they could choose to only run the tests for, e.g. 20s or 30s.
A simple solution would use the existing content. As a result it would not finish on the red frame but on a content frame. The test operator could be given a free choice of duration. The tests where duration matters (e.g. random access) could either be excluded from the over-ridden duration or could have the duration over-ride limited to a minimum value (e.g. 10s greater than the target time for the seek) or could make the seek adaptive to the duration, e.g. based on 1/2 of the duration and then modified to pick the nearest segment or to avoid a segment.
A better solution would require us to pick a duration such as 20s or 30s and generate new mezzanine content and encoded content with that duration. This would ensure the content finished with the red frame. Some of the same issues apply.

**Comment by jpiesing** [comment]
@nicholas-fr

**Comment by jpiesing** [comment]
Even just allowing the duration to be over-ridden for sequential track playback would be helpful as that test will be run many times for the different WAVE content options.

**Comment by nicholas-fr** [comment]
Seems we have 2 options: tester can choose an arbitrary duration, in which case the 60s content can be used and playback stops after the chosen duration (<=60s).
Or we offer the tester a choice between 2 different durations 60s and 30s (or 20s?).
In that case, we'd generate a set of 30s (or 20s) mezzanine and then the test content from that.

If the latter is the preferred approach, I can generate a set of 20 or 30s mezzanine streams.

**Comment by andyburras** [comment]
If option 1 were to be used then I think there may be some Test Runner changes required.
Currently the script https://github.com/cta-wave/dpctf-tests/blob/master/generate-tests.py writes MPD information to "tests.json", including the "cmaf_track_duration".

The Observation Framework uses this parameter in some observations when determining pass/fail. So this value would need to reflect the tester's chosen duration.

**Comment by jpiesing** [comment]
Closing as this is replaced by https://github.com/cta-wave/dpctf-tests/issues/56.
