### ISSUE TITLE
all tests have the word "manifest" in the file name?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#36]
Is there a reason why all the tests appear to have the word "manifest" in the file name?

![image](https://user-images.githubusercontent.com/8490792/117002419-d40b5c00-ace3-11eb-99aa-f93834b17b07.png)

It might be clearer if "manifest" could be removed.

**Comment by FritzHeiden** [comment]
When generating the test files from the templates, the generated test files are named after the template + video mpd name + audio mpd name. In this case the mpd file name was `manifest.mpd`

**Comment by louaybassbouss** [comment]
@jpiesing FYI this are the name of the auto-generated tests. In the past we decided to use the combination if the test implementation filename + the name of the media file. We are now in a situation where all media files have the same name `manifest.mpd`. I think we need to include more details from the path. wdyt?

**Comment by jpiesing** [comment]
>  FYI this are the name of the auto-generated tests. In the past we decided to use the combination if the test implementation filename + the name of the media file. We are now in a situation where all media files have the same name `manifest.mpd`. I think we need to include more details from the path. wdyt?

@louaybassbouss Many of the tests are only run once for any given codec. For these, the test implementation filename (i.e. the same as the heading in the DPCTF specification) is sufficient. If a test is run more than once for a given codec (e.g. sequential track playback) then what needs adding is a unique identifier for the MPD. If the MPDs all have the same name then what about the name of the directory / folder containing the MPD?

**Comment by louaybassbouss** [comment]
> > FYI this are the name of the auto-generated tests. In the past we decided to use the combination if the test implementation filename + the name of the media file. We are now in a situation where all media files have the same name `manifest.mpd`. I think we need to include more details from the path. wdyt?
> 
> @louaybassbouss Many of the tests are only run once for any given codec. For these, the test implementation filename (i.e. the same as the heading in the DPCTF specification) is sufficient. If a test is run more than once for a given codec (e.g. sequential track playback) then what needs adding is a unique identifier for the MPD. If the MPDs all have the same name then what about the name of the directory / folder containing the MPD?

@jpiesing yes we can include the path (or part of it) in the filename.  We need to decide for a rule we can apply to all filenames. It seems that we now have a stable structure for folder/file structure as defined in [database.json](https://dash.akamaized.net/WAVE/vectors/database.json)  for example for `avc_sets/15_30_60/t1/stream.mpd` (the first item in database.json) we can use `avc_sets-15_30_60-t1` in the filename. wdyt?

**Comment by cta-source** [comment]
We have a mezzanine spec in development [see Mezzanine Issue #31](https://github.com/cta-wave/mezzanine/issues/31#issuecomment-814903531); this _"encoded test file name format"_ information is important as well but isn't strictly speaking mezzanine file format.  The mezzanine format spec should be extended to include requirements on encoded test files that the test suite requires.

**Comment by FritzHeiden** [comment]
I modified the implementation of the generate script to use data from the MPDs file hierarchy as tags for the generated test files. The generated tests were updated accordingly.

**Comment by jpiesing** [comment]
> I modified the implementation of the generate script to use data from the MPDs file hierarchy as tags for the generated test files. The generated tests were updated accordingly.

@FritzHeiden Thank you for this. I have two comments for you to think about ...
- I would have expected 15_30_60 to appear somewhere. We will have 12.5_25_50 versions soon.
- I don't see a reason for the "gpac" string. Is there a reason for including this?

**Comment by louaybassbouss** [comment]
> > I modified the implementation of the generate script to use data from the MPDs file hierarchy as tags for the generated test files. The generated tests were updated accordingly.
> 
> @FritzHeiden Thank you for this. I have two comments for you to think about ...
> 
> * I would have expected 15_30_60 to appear somewhere. We will have 12.5_25_50 versions soon.
> * I don't see a reason for the "gpac" string. Is there a reason for including this?

Yes this will appear in the filename. The reason why you not see it because the current sample.csv file still include old content. We now have a new [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) file which includes the new content from database.json (we didn't generated the tests for this csv file yet). For example, for the first line in [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) (copied below) the generated filename will be `sequential-track-playback_avc_sets_15_30_60_t1.html`. the part `_avc_sets_15_30_60_t1` in the filename is created from the `/avc_sets/15_30_60/t1/` from the mpd path.  

```csv
"sequential-track-playback","/content/avc_sets/15_30_60/t1/stream.mpd","","avc_15_30_60-local"
```

**Comment by jpiesing** [comment]
> Yes this will appear in the filename. The reason why you not see it because the current sample.csv file still include old content. We now have a new [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) file which includes the new content from database.json (we didn't generated the tests for this csv file yet). For example, for the first line in [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) (copied below) the generated filename will be `sequential-track-playback_avc_sets_15_30_60_t1.html`. the part `_avc_sets_15_30_60_t1` in the filename is created from the `/avc_sets/15_30_60/t1/` from the mpd path.

That looks good to me. I'll close this issue when the tests are re-generated.

**Comment by FritzHeiden** [comment]
I added tests generated from the tests.csv file

**Comment by louaybassbouss** [comment]
@jpiesing PTAL and close issue if the file names are ok for you

**Comment by jpiesing** [comment]
This is what I see now.

![image](https://user-images.githubusercontent.com/8490792/120187278-e316f880-c214-11eb-91da-5f0e648067f1.png)

Why is 15_30_60 repeated? Is this deliberate or accidental? I would prefer it be in the directory & not in the filename if there's a choice.

**Comment by jpiesing** [comment]
I'm not completely happy with the test names due to the repetition of 15_30_60 (see below) but this specific issue is solved.
![image](https://user-images.githubusercontent.com/8490792/120766069-24abea00-c51a-11eb-878a-ba527c7cebc5.png)

The real solution is covered by https://github.com/cta-wave/dpctf-tests/issues/38 .
