### ISSUE TITLE
Question on generating tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#39]
I am not sure if this is the correct way to use the test generation. But does test runner support different content with same test code in different folder please?

I was trying to generate two different tests with different contents in different folder but use same test code. 
I have noticed that the only one test appeared on tests.json file, one test seems get overwritten by the other one. 

For example:
in sample.csv I have,
"sequential-track-playback","/contents/avc_sets/15_30_60/t20/stream.mpd","","high"
"sequential-track-playback","/contents/avc_sets/15_30_60/t34/stream.mpd","","low"

I can see two HTML+JS files are created in correct folder. 

However, from tests.json I can see only:
"54694ae36ab3a4e99db15dcfa41b6ab8": {
            "path": "high/sequential-track-playback__stream__.html",
            "video": "/contents/avc_sets/15_30_60/t20/stream.mpd",
            "audio": "",
            "code": "sequential-track-playback.html",
            "config": {
                "cmaf_track_duration": "PT0H1M0.000S",
                "fragment_duration": "PT0H0M2.021S",
                "representations": {
                    "1": {
                        "duration": 60
                    },
                    "2": {
                        "duration": 60
                    }
                }
            }
        },
Cannot find the test for "path": "low/sequential-track-playback__stream__.html"

**Comment by FritzHeiden** [comment]
Thanks for reporting. I pushed a fix to this bug, please try again.

**Comment by louaybassbouss** [comment]
@yanj-github can you confirm that the fix solves the problem? if yes please feel free to close this issue

**Comment by yanj-github** [comment]
Yes it is working fine with me.
