### ISSUE TITLE
download test not working again

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#40]
Please see the following, it seems the json file the zip path is not difined. 

python ./download-content.py https://dash.akamaized.net/WAVE/vectors/database.json content
Fetching JSON https://dash.akamaized.net/WAVE/vectors/database.json
Vector 'avc/15_30_60/tStream ID' does not specify zip path, skipping ...
Vector 'avc/15_30_60/t1' does not specify zip path, skipping ... 
Vector 'avc/15_30_60/t2' does not specify zip path, skipping ... 

... ...

**Comment by louaybassbouss** [comment]
@yanj-github  this should be related to the caching issue we discussed yesterday in the call. I just opened https://dash.akamaized.net/WAVE/vectors/database.json in the Browser I can see the zipPath. Can you try again? This is one item from database.json I just downloaded.

```json
"./output/avc_sets/15_30_60/t1": {
    "representations": [
      {
        "resolution": "1920x1080",
        "framerate": 30.0,
        "bitrate": "5100",
        "input": "tos_L1_1920x1080@30_60.mp4"
      }
    ],
    "segmentDuration": "2",
    "fragmentType": "duration",
    "hasSEI": false,
    "hasVUITiming": true,
    "visualSampleEntry": "FALSE",
    "mpdPath": "avc_sets/15_30_60/t1/stream.mpd",
    "zipPath": "avc_sets/15_30_60/t1.zip"
  }
```

**Comment by jpiesing** [comment]
Indeed. If I look at the database.json in a browser here, it looks OK as you can see below. This seems like another instance of https://github.com/cta-wave/Test-Content/issues/15 .

![image](https://user-images.githubusercontent.com/8490792/121345805-996d9280-c925-11eb-949b-8d17503e6061.png)

**Comment by yanj-github** [comment]
I cleared cache still unsbale to see the zipPath from https://dash.akamaized.net/WAVE/vectors/database.json.
Does download-content.py has cache as well please?

I can see zip path from https://dash.akamaized.net/WAVE/vectors/database_cenc.json

**Comment by jpiesing** [comment]
> I cleared cache still unsbale to see the zipPath from https://dash.akamaized.net/WAVE/vectors/database.json.
> Does download-content.py has cache as well please?

It will be a cache in the network not one locally.

@yanj-github I've attached the version of database.json that I see. If you look at import.sh, you will see that it just calls download-content.py. In the short term, perhaps you can run download-content.py manually passing it this version of database.json?

[database.json.zip](https://github.com/cta-wave/dpctf-tests/files/6623400/database.json.zip)

**Comment by yanj-github** [comment]
Thanks @jpiesing but this is not working. Calling download-content.py passing local databse.json doee not work in looks up path //avc_sets/15_30_60/t1.zip instead of full url path. @louaybassbouss  I guess download-content.py append zip path based on location/url of databse.json isnt it?
This is not a blocker to me I can always download contents manually.

**Comment by louaybassbouss** [comment]
> Thanks @jpiesing but this is not working. Calling download-content.py passing local databse.json doee not work in looks up path //avc_sets/15_30_60/t1.zip instead of full url path. @louaybassbouss I guess download-content.py append zip path based on location/url of databse.json isnt it?
> This is not a blocker to me I can always download contents manually.

You cannot use database.json from local path because `zipPath` and `mpdPath` are relative and the download script uses the location of the database.json to create the absolute URLs. Can you maybe try to use this URL https://dash-large-files.akamaized.net/WAVE/vectors/database.json (instead of https://dash.akamaized.net/WAVE/vectors/database.json) ?

**Comment by yanj-github** [comment]
This is working now.
