### ISSUE TITLE
Getting fragment_duration information from tests.json file

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#41]
The following is taken from current tests.json file.

                 "representations": {
                            "1": {
                                "duration": 60,
                                "fragment_duration": 1.9969160997732427
                            },
                            "2": {
                                "duration": 60,
                                "fragment_duration": 2.0
                            }
video content fragment_duration is 2 seconds however we cannot tell which representations is video and which one is audio form the information given. Is it possible to pass only one video representations which gets played back, if there is more than one video representations and also if the current representation is a vedio or audio representation please?

                 "representations": {
                            "1": {
                                "type": "audio",
                                "duration": 60,
                                "fragment_duration": 1.9969160997732427
                            },
                            "2": {
                                "type": "video",
                                "duration": 60,
                                "fragment_duration": 2.0
                            }
Not showing representations 3,4,5... ... if not playng them back.

**Comment by louaybassbouss** [comment]
@yanj-github we will add additional field `type` for audio/video and another field `period`. The script that generates tests.json reads the information about the representations from MPD files. If the MPD contains more than one representation but the test requires only one representation, then you can expect that the first representation is considered.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss that sounds good to me so OF will just read 1st video representation when only one is required.

**Comment by FritzHeiden** [comment]
@yanj-github I extended the generate script accordingly and updated the tests.json file

**Comment by yanj-github** [comment]
Thank you @FritzHeiden  and @louaybassbouss

**Comment by yanj-github** [comment]
I just spotted the "fragment_duration": null for switching set tests. OF need to know correct "fragment_duration" to calculate switching point.

**Comment by FritzHeiden** [comment]
@yanj-github Thanks for reporting. There seemed to be an edge case I didn't account for. The generate script is fixed and tests.json updated.

**Comment by yanj-github** [comment]
Looks all good.
