### ISSUE TITLE
Question to playout parameter

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#42]
For a switching set test, there is a "playout" parameter specifies which representations to play. 
What should this playout parameter contain? I thought this is a list of representation IDs. 

eg.: having following playout,
 ```
 "avc_15_30_60-local/switching-set-playback__ss1.html": {
    "playout": [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  },
```
with following content mpd
```
<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" bandwidth="128000">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="60" par="16:9" lang="und" startWithSAP="1" contentType="video" segmentProfiles="cmfs, cmff">
   <SegmentTemplate timescale="15360">
    <SegmentTimeline>
     <S t="0" d="30720" r="29"/>
    </SegmentTimeline>
   </SegmentTemplate>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.64002A" width="1920" height="1080" frameRate="30" sar="1:1" bandwidth="5100000">
    <SegmentTemplate media="tos_L1_1920x1080@30_60_dash$Time$.m4s" initialization="tos_L1_1920x1080@30_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="3" mimeType="video/mp4" codecs="avc1.64002A" width="1920" height="1080" frameRate="60" sar="1:1" bandwidth="6000000">
    <SegmentTemplate media="tos_L2_1920x1080@60_60_dash$Time$.m4s" initialization="tos_L2_1920x1080@60_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="4" mimeType="video/mp4" codecs="avc1.64002A" width="1280" height="720" frameRate="60" sar="1:1" bandwidth="3000000">
    <SegmentTemplate media="tos_J1_1280x720@60_60_dash$Time$.m4s" initialization="tos_J1_1280x720@60_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="5" mimeType="video/mp4" codecs="avc1.64002A" width="1024" height="576" frameRate="30" sar="1:1" bandwidth="1500000">
    <SegmentTemplate media="tos_I1_1024x576@30_60_dash$Time$.m4s" initialization="tos_I1_1024x576@30_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="6" mimeType="video/mp4" codecs="avc1.64002A" width="1024" height="576" frameRate="30" sar="1:1" bandwidth="1200000">
    <SegmentTemplate media="tos_I2_1024x576@30_60_dash$Time$.m4s" initialization="tos_I2_1024x576@30_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="7" mimeType="video/mp4" codecs="avc1.64002A" width="768" height="432" frameRate="30" sar="1:1" bandwidth="900000">
    <SegmentTemplate media="tos_F1_768x432@30_60_dash$Time$.m4s" initialization="tos_F1_768x432@30_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="8" mimeType="video/mp4" codecs="avc1.64002A" width="512" height="288" frameRate="30" sar="1:1" bandwidth="450000">
    <SegmentTemplate media="tos_B1_512x288@30_60_dash$Time$.m4s" initialization="tos_B1_512x288@30_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
   <Representation id="9" mimeType="video/mp4" codecs="avc1.64002A" width="480" height="270" frameRate="15" sar="1:1" bandwidth="300000">
    <SegmentTemplate media="tos_A1_480x270@15_60_dash$Time$.m4s" initialization="tos_A1_480x270@15_60_dashinit.mp4" timescale="15360" startNumber="1"/>
   </Representation>
```

I was expecting to see L1 and I1, however, I am getting J1 then it switching to F1. 
It seems like test runner takes 1st video Representation as 0 then +1 for each following representation. Is this what is expected please?

In addition to this, J1 plays back for 32 seconds and switched to F1 but I was expecting 30 seconds for J1 the other 30 seconds for F1 based on 2 seconds fragment duration and given playout 15 for each.

**Comment by jpiesing** [comment]
> I was expecting to see L1 and I1, however, I am getting J1 then it switching to F1.

I would also have expected L1 and I1.

**Comment by louaybassbouss** [comment]
@yanj-github according to DPCTF spec (section 8.5.3), the values of the `playout` parameter are the CMAF track numbers (1..k). I just checked with @FritzHeiden in the test implementation we start with index 0 as you guessed, this means in your example the value `2` means the video representation with index 2 in the array which is `J1` and the `5` means the video representation with index 5 in the array which is `F1`.  In other words, we need to fix the index and start by `1` and not by `0`. But in any case, the representation ID is not relevant for the playout parameter but only the index of the video representation. 

Regarding why it plays 32 seconds and not 30 seconds @FritzHeiden is checking it.

**Comment by FritzHeiden** [comment]
I pushed a fix for the representation number and the playout interpretation. Numbers now start at `1` and in your case, it should now play 30 seconds each.

**Comment by yanj-github** [comment]
Thanks it looks good to me.

Can you kindly add a default playout to the test-config.json so that it will just work out of the box without change.
OF reports error when playout parameter cannot be found for switching set tests. 

I think something like the following will do (I assume fregement duration are all same 2 seconds and track duration is 60 seconds and switching set has at least 2 Representations):

```
  "switching-set-playback.html": {
    "ts_max": 120,
    "tolerance": 10,
    "playout": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
  },
```
I think we have few more tests that are required playout. 
"overlapping-fragments.html" and "fullscreen-playback-of-switching-sets.html" if default playout get configured as well for these tests please?

**Comment by louaybassbouss** [comment]
Thanks @yanj-github for your feedback. Yes we can add the default playout to the tests you mentioned. Can you provide  the values for playout for tests  "overlapping-fragments.html" and "fullscreen-playback-of-switching-sets.html"?

**Comment by yanj-github** [comment]
Thanks @louaybassbouss 
I would make then all same. "playout": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] 
At least @jpiesing says otherwise?

Also I noticed the "fullscreen-playback-of-switching-sets.html" does not switches the representation but it always plays the 1st one. I am a bit confused on this test, and not sure if this requires to switch or not? Can anyone confirm please? It says switching set on the title but from spec it is not clearily defined that it is using swiching set.

And for "overlapping-fragments.html" is it should be using ss1 instead of content t1, if this test meant to use CMAF Switching Set? Also I am not 100% sure about this either. If anyone help to confrim it would be appreaciated.

**Comment by jpiesing** [comment]
> Thanks @louaybassbouss
> I would make then all same. "playout": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
> At least @jpiesing says otherwise?

To keep it simple, "fullscreen-playback-of-switching-sets.html" should be the same as "Switching Set Playback".
In both of these cases, I would expect to step through each CMAF track in the Switching set and not do just tracks 1 and 2 as above.

I'm not sure about how useful a default value of playout is. Sometimes each entry in the array is a number & sometimes it's a tuple.

8.5 - entries in playout are a number "playout[i]: Provides the CMAF track number for every fragment position
i=1,…,N. The value shall be between 1 and K."
8.8 - entries in playout are a tuple "Provides the triple (Switching Set, CMAF track number, Fragment number) for every playout position i=1,…,N that is be played out."
8.10 - entries in playout are a number "playout[i]: Provides the CMAF track number for every fragment position i=1,…,N. This value shall be between 1 and K."

**Comment by yanj-github** [comment]
Thanks @jpiesing OF need to read playout to calculate correct switching point if no playout set it wont do observation but report configuration parameter is missing. This is a shared paramter between Test Runner and OF. 
At OF point of view we need to get shared parameters matches with the switching.

**Comment by jpiesing** [comment]
> Thanks @jpiesing OF need to read playout to calculate correct switching point if no playout set it wont do observation but report configuration parameter is missing. This is a shared paramter between Test Runner and OF.
> At OF point of view we need to get shared parameters matches with the switching.

IMHO playout needs to be provided explicitly for each test that requires it. I don't see the benefit from having a default parameter. Indeed having a default value of playout may hide errors that would otherwise be more obvious.

**Comment by yanj-github** [comment]
> 

> IMHO playout needs to be provided explicitly for each test that requires it. I don't see the benefit from having a default parameter. Indeed having a default value of playout may hide errors that would otherwise be more obvious.

Thanks @jpiesing 
So the user need to be aware of playout needs to be defined before they can test any switching set tests. 
This is fine to me, whithout playout is set, OF will just report a configuration error saying playout is missing for the test.

**Comment by yanj-github** [comment]
So @louaybassbouss I think we are fine without no default playout. Can you help look at the following please? 

- "fullscreen-playback-of-switching-sets.html" does not switches the representation but it always plays the 1st one.
- And for "overlapping-fragments.html" is it should be using ss1 instead of content t1, if this test meant to use CMAF Switching Set? Also I am not 100% sure about this either. If anyone help to confrim it would be appreaciated.

**Comment by jpiesing** [comment]
> * And for "overlapping-fragments.html" is it should be using ss1 instead of content t1, if this test meant to use CMAF Switching Set? Also I am not 100% sure about this either. If anyone help to confrim it would be appreaciated.

Indeed the spreadsheet says overlapping-fragments should be with stream t1 so using it with ss1 looks like a bug.

**Comment by louaybassbouss** [comment]
> So @louaybassbouss I think we are fine without no default playout. Can you help look at the following please?
> 
> * "fullscreen-playback-of-switching-sets.html" does not switches the representation but it always plays the 1st one.
> * And for "overlapping-fragments.html" is it should be using ss1 instead of content t1, if this test meant to use CMAF Switching Set? Also I am not 100% sure about this either. If anyone help to confrim it would be appreaciated.

@FritzHeiden  can you please check both items raised by @yanj-github

**Comment by louaybassbouss** [comment]
> > * And for "overlapping-fragments.html" is it should be using ss1 instead of content t1, if this test meant to use CMAF Switching Set? Also I am not 100% sure about this either. If anyone help to confrim it would be appreaciated.
> 
> Indeed the spreadsheet says overlapping-fragments should be with stream t1 so using it with ss1 looks like a bug.

@jpiesing  "overlapping-fragments.html" uses content `t1`(see [tests.csv L74](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv#L74)) as stated in the spreadsheet. What do you mean `...using it with ss1 looks like a bug`?

**Comment by jpiesing** [comment]
> @jpiesing "overlapping-fragments.html" uses content `t1`(see [tests.csv L74](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv#L74)) as stated in the spreadsheet. What do you mean `...using it with ss1 looks like a bug`?

@yanj-github Said "overlapping-fragments.html" used content ss1 - perhaps this was a mistake?

**Comment by yanj-github** [comment]
> 
> 
> > @jpiesing "overlapping-fragments.html" uses content `t1`(see [tests.csv L74](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv#L74)) as stated in the spreadsheet. What do you mean `...using it with ss1 looks like a bug`?
> 
> @yanj-github Said "overlapping-fragments.html" used content ss1 - perhaps this was a mistake?

No @jpiesing I meant to ask should "overlapping-fragments.html" use switching set? In the spec 8.10.2 it says "A CMAF Switching Set is available for playback following the properties".

**Comment by louaybassbouss** [comment]
> > So @louaybassbouss I think we are fine without no default playout. Can you help look at the following please?
> > 
> > * "fullscreen-playback-of-switching-sets.html" does not switches the representation but it always plays the 1st one.
>> ...
> 
> @FritzHeiden can you please check both items raised by @yanj-github

@yanj-github regarding to your  question regarding `fullscreen-playback-of-switching-sets.html` the [spec description](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5003-final.pdf) is not very clear or maybe this is a bug. Section "8.11.3 Parameters and Variants" says `Same as documented in clause 8.9.3.`. Section 8.9 ist about out of order loading and don't use playout parameter.  In my view I think we need `playout` parameter in `fullscreen-playback-of-switching-sets.html` to switch between different representations and make sure the content is properly displayed. For this reason we activated the playout parameter for this test as well. @jpiesing  do you agree this is a bug in the spec?

**Comment by jpiesing** [comment]
> @yanj-github regarding to your question regarding `fullscreen-playback-of-switching-sets.html` the [spec description](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5003-final.pdf) is not very clear or maybe this is a bug. Section "8.11.3 Parameters and Variants" says `Same as documented in clause 8.9.3.`. Section 8.9 ist about out of order loading and don't use playout parameter. In my view I think we need `playout` parameter in `fullscreen-playback-of-switching-sets.html` to switch between different representations and make sure the content is properly displayed. For this reason we activated the playout parameter for this test as well. @jpiesing do you agree this is a bug in the spec?

I would have expected 8.11 to reference 8.5 & be the same as 8.5 except for being full screen.
@yanj-github @louaybassbouss @haudiobe What do you think?

**Comment by louaybassbouss** [comment]
> > @yanj-github regarding to your question regarding `fullscreen-playback-of-switching-sets.html` the [spec description](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5003-final.pdf) is not very clear or maybe this is a bug. Section "8.11.3 Parameters and Variants" says `Same as documented in clause 8.9.3.`. Section 8.9 ist about out of order loading and don't use playout parameter. In my view I think we need `playout` parameter in `fullscreen-playback-of-switching-sets.html` to switch between different representations and make sure the content is properly displayed. For this reason we activated the playout parameter for this test as well. @jpiesing do you agree this is a bug in the spec?
> 
> I would have expected 8.11 to reference 8.5 & be the same as 8.5 except for being full screen.
> @yanj-github @louaybassbouss @haudiobe What do you think?

@jpiesing agree

**Comment by yanj-github** [comment]
> 
> 
> > @yanj-github regarding to your question regarding `fullscreen-playback-of-switching-sets.html` the [spec description](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5003-final.pdf) is not very clear or maybe this is a bug. Section "8.11.3 Parameters and Variants" says `Same as documented in clause 8.9.3.`. Section 8.9 ist about out of order loading and don't use playout parameter. In my view I think we need `playout` parameter in `fullscreen-playback-of-switching-sets.html` to switch between different representations and make sure the content is properly displayed. For this reason we activated the playout parameter for this test as well. @jpiesing do you agree this is a bug in the spec?
> 
> I would have expected 8.11 to reference 8.5 & be the same as 8.5 except for being full screen.
> @yanj-github @louaybassbouss @haudiobe What do you think?

Yes. I think so.

**Comment by yanj-github** [comment]
> 
> 
> > > @jpiesing "overlapping-fragments.html" uses content `t1`(see [tests.csv L74](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv#L74)) as stated in the spreadsheet. What do you mean `...using it with ss1 looks like a bug`?
> > 
> > 
> > @yanj-github Said "overlapping-fragments.html" used content ss1 - perhaps this was a mistake?
> 
> No @jpiesing I meant to ask should "overlapping-fragments.html" use switching set? In the spec 8.10.2 it says "A CMAF Switching Set is available for playback following the properties".

@jpiesing How about the 8.10 overlapping please? Does it require switching or not please?

**Comment by jpiesing** [comment]
> @jpiesing How about the 8.10 overlapping please? Does it require switching or not please?

Yes as far as I can see unless the spec is also wrong on this one. I don't understand it will enough to be certain.

**Comment by louaybassbouss** [comment]
> > @jpiesing How about the 8.10 overlapping please? Does it require switching or not please?
> 
> Yes as far as I can see unless the spec is also wrong on this one. I don't understand it will enough to be certain.

@yanj-github  you can already use `playout` for this test.

**Comment by yanj-github** [comment]
> 
> 
> > > @jpiesing How about the 8.10 overlapping please? Does it require switching or not please?
> > 
> > 
> > Yes as far as I can see unless the spec is also wrong on this one. I don't understand it will enough to be certain.
> 
> @yanj-github you can already use `playout` for this test.

Thanks @louaybassbouss 

OF expecting playout for this test at the moment and it will fail the observation when this is not defined.

**Comment by louaybassbouss** [comment]
@yanj-github this is an old issue I think it should be solved now can you please confirm?

**Comment by yanj-github** [comment]
I still need an answer to the test 8.10 overlapping. 
Can anyone confirm that 8.10 overlapping test uses single track, not uses switching set content please?

**Comment by jpiesing** [comment]
> I still need an answer to the test 8.10 overlapping.
> Can anyone confirm that 8.10 overlapping test uses single track, not uses switching set content please?

No. 8.10 uses multiple tracks. "K" is >1.

![image](https://user-images.githubusercontent.com/8490792/133253862-bd2c688f-f949-4935-a53f-fd468c9d9b9a.png)

**Comment by yanj-github** [comment]
Thanks @jpiesing 
The following from tests.csv
overlapping-fragments  https://dash.akamaized.net/WAVE/vectors/2021-07-07/avc_sets/15_30_60/t1/stream.mpd

Dose it mean it should use ss1?

**Comment by jpiesing** [comment]
> Dose it mean it should use ss1?

Yes, SS1 needs to be used. This is an error in the google docs spreadsheet.

**Comment by louaybassbouss** [comment]
> > Dose it mean it should use ss1?
> 
> Yes, SS1 needs to be used. This is an error in the google docs spreadsheet.

@FritzHeiden  can you update the CSV to use ss1 for this test?

**Comment by FritzHeiden** [comment]
> @FritzHeiden can you update the CSV to use ss1 for this test?

done.
