### ISSUE TITLE
Current time reports 0 at some point in playback

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#43]
From a mobile phone testing we detected that test runner status QR code reports back current time=0 some point in playback.
Please see the following data extracetd from OF:

<html><body>

Current Time | Time Difference
-- | --
0 | 1.7976931348623157e+308
19.584 | 30.416
250.198 | 16.802
0 | 367
500.275 | 16.725
750.379 | 32.621
1000.484 | 16.516
1250.733 | 32.267
1500.811 | 16.189
1750.341 | 16.659
2010.726 | 22.274
2250.397 | 16.603
2504.204 | 12.796
0 | 2583
2750.298 | 0.298
3000.321 | 16.679
3250.532 | 16.468
3500.331 | 16.669
3750.624 | 0.624
4000.439 | 16.561
4250.479 | 16.521
0 | 4400
4500.278 | 32.722

</body>
</html>

https://github.com/cta-wave/device-observation-framework/issues/22#issuecomment-865943598

**Comment by louaybassbouss** [comment]
@yanj-github can you provide more details? which content (is online or downloaded?)? what is the status of the QR code when currentTime 0 is reported? maybe the player in waiting state because it is currently buffering content.

**Comment by louaybassbouss** [comment]
@yanj-github can you add in the table above (https://github.com/cta-wave/dpctf-tests/issues/43#issue-927253671) a new column with the status (property `s`)  included in the QR code (possible values for `s` are: `playing`, `paused`, `buffering`, `ended`, `ready`, `error`, `waiting`).

**Comment by yanj-github** [comment]
@louaybassbouss 
https://github.com/cta-wave/device-observation-framework/files/6689857/qr_code_list.zip

**Comment by louaybassbouss** [comment]
> @louaybassbouss
> https://github.com/cta-wave/device-observation-framework/files/6689857/qr_code_list.zip
> 
> Sorry about it contains more information than what you have asked for.
> You can try to do some filtering or sorting. Let me know if you need any help please?

@yanj-github we cannot reproduce this issue on our side. Are the zeros in currentTime added by your script or they are parsed from the `ct` property in the QR code? For example if `s` is `buffering`, you put in corresponding `currentTime` field in the CSV file a `0` but we don't report any `ct` in this case. @jpiesing did you use online or downloaded content in your test? do you see the player stalling?

**Comment by yanj-github** [comment]
@jpiesing what is happening in the QR code is there is no current time but only playing and play event then delay. 
I was expecting to see current time when the status is playing. 
What OF should report in this case for calculating current time match case? Should it say pass @jpiesing ?

**Comment by andyburras** [comment]
Just to clarify, what I've seen is:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ANDY~1.BUR/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ANDY~1.BUR/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Camera   Frame | Test Status | Last Action | Current Time | Delay
-- | -- | -- | -- | --
370 | playing | play | 3.75109 | 22
371 | playing | play | 3.75109 | 22
372 | playing | play | 3.75109 | 22
373 | playing | play | 3.75109 | 22
374 | playing | play | 3.75109 | 22
375 | playing | play | 3.75109 | 22
376 | playing | play | 3.75109 | 22
377 | playing | play | 3.75109 | 22
378 | playing | play | 3.75109 | 22
379 | playing | play | 3.75109 | 22
380 | playing | play | 4.001341 | 20
381 | playing | play | 4.001341 | 20
382 | playing | play | 0 | 15
383 | playing | play | 0 | 15
384 | playing | play | 0 | 15
385 | playing | play | 0 | 15
386 | playing | play | 0 | 15
387 | playing | play | 0 | 15
388 | playing | play | 0 | 15
389 | playing | play | 0 | 15
390 | playing | play | 0 | 15
391 | playing | play | 0 | 15
392 | playing | play | 0 | 15
393 | playing | play | 0 | 15
394 | playing | play | 0 | 15
395 | playing | play | 0 | 15
396 | playing | play | 4.251627 | 5
397 | playing | play | 4.251627 | 5
398 | playing | play | 4.251627 | 5



</body>

</html>


So a status QR code with 4.001341, 20 appeared for a fraction of a second and was then replaced with a 0, 15 one. It may be that the browser was buffering (difficult to tell), but in which case I would have expected a Test Status of "buffering"?

**Comment by louaybassbouss** [comment]
Thanks @andyburras we will check.

**Comment by jpiesing** [comment]
> @jpiesing did you use online or downloaded content in your test? do you see the player stalling?

Downloaded in that one. Downloaded seems not to be available any more though.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss.
When status saying bufferring OF does not do the current time check.

**Comment by FritzHeiden** [comment]
We improved the video status updating mechanism and added the current time to the qr code whenever possible.

**Comment by louaybassbouss** [comment]
@yanj-github can you re-run the tests on the mentioned device (since we cannot reproduce) and send us the Observation CSV file?

**Comment by jpiesing** [comment]
I believe the device here is my current mobile phone. If so, the file used is C0028. I shared a new run from this device with @yanj-github yesterday.

**Comment by yanj-github** [comment]
@jpiesing Your file sent to me yesterday C0030 does not include this fix. I think you need to get the latest change of test runner. 
Do you mind do another recording please? I am unable to replicate same problem on my device here. 
@FritzHeiden Do you mean current time is sent always?

**Comment by FritzHeiden** [comment]
@yanj-github Yes, as soon as the video plays, the current time is included in every qr code update

**Comment by louaybassbouss** [comment]
@jpiesing  it is possible to share the video recording of the test where the issue occurs with us if the issue still occurs.

**Comment by jpiesing** [comment]
@louaybassbouss I've also sent you C0030 via wetransfer.com - I think this one includes the problem - at least it predates the fixes. I've not validated if there is still a problem. I'm sending you C0036 which should include the fixes.

**Comment by yanj-github** [comment]
Here are the extraction from C0036:
Can still see the 0 current time no differences. @jpiesing can you confirm 0036 tested with the fix please?

2888 |   |   |   |   | playing | play | 0.504144 | 28
-- | -- | -- | -- | -- | -- | -- | -- | --
2889 | L1 | 633 | 19 | 30 |   |   |   |  
2889 |   |   |   |   | playing | play | 0.504144 | 28
2890 | L1 | 633 | 19 | 30 |   |   |   |  
2890 |   |   |   |   | playing | play | 0.504144 | 28
2891 | L1 | 633 | 19 | 30 |   |   |   |  
2891 |   |   |   |   | playing | play | 0.504144 | 28
2892 | L1 | 667 | 20 | 30 |   |   |   |  
2892 | L1 | 633 | 19 | 30 |   |   |   |  
2893 | L1 | 667 | 20 | 30 |   |   |   |  
2893 | L1 | 633 | 19 | 30 |   |   |   |  
2893 |   |   |   |   | playing | play | 0 | 23
2894 | L1 | 667 | 20 | 30 |   |   |   |  
2894 |   |   |   |   | playing | play | 0 | 23
2895 | L1 | 700 | 21 | 30 |   |   |   |  
2895 | L1 | 667 | 20 | 30 |   |   |   |  
2895 |   |   |   |   | playing | play | 0 | 23
2896 | L1 | 667 | 20 | 30 |   |   |   |  
2896 |   |   |   |   | playing | play | 0 | 23
2896 | L1 | 700 | 21 | 30 |   |   |   |  
2897 |   |   |   |   | playing | play | 0 | 23
2897 | L1 | 667 | 20 | 30 |   |   |   |  
2897 | L1 | 700 | 21 | 30 |   |   |   |  
2898 |   |   |   |   | playing | play | 0 | 23
2898 | L1 | 700 | 21 | 30 |   |   |   |  
2899 | L1 | 733 | 22 | 30 |   |   |   |  
2899 | L1 | 700 | 21 | 30 |   |   |   |  
2899 |   |   |   |   | playing | play | 0 | 23
2900 | L1 | 700 | 21 | 30 |   |   |   |  
2900 | L1 | 733 | 22 | 30 |   |   |   |  
2900 |   |   |   |   | playing | play | 0 | 23
2901 | L1 | 700 | 21 | 30 |   |   |   |  
2901 | L1 | 733 | 22 | 30 |   |   |   |  
2901 |   |   |   |   | playing | play | 0 | 23
2902 | L1 | 733 | 22 | 30 |   |   |   |  
2902 |   |   |   |   | playing | play | 0 | 23
2903 | L1 | 733 | 22 | 30 |   |   |   |  
2903 |   |   |   |   | playing | play | 0 | 23
2903 | L1 | 767 | 23 | 30 |   |   |   |  
2904 | L1 | 733 | 22 | 30 |   |   |   |  
2904 | L1 | 767 | 23 | 30 |   |   |   |  
2904 |   |   |   |   | playing | play | 0 | 23
2905 | L1 | 767 | 23 | 30 |   |   |   |  
2905 |   |   |   |   | playing | play | 0 | 23
2906 | L1 | 767 | 23 | 30 |   |   |   |  
2906 |   |   |   |   | playing | play | 0 | 23
2907 | L1 | 800 | 24 | 30 |   |   |   |  
2907 | L1 | 767 | 23 | 30 |   |   |   |  
2907 |   |   |   |   | playing | play | 0 | 23
2908 | L1 | 800 | 24 | 30 |   |   |   |  
2908 | L1 | 767 | 23 | 30 |   |   |   |  
2908 |   |   |   |   | playing | play | 0 | 23
2909 | L1 | 800 | 24 | 30 |   |   |   |  
2909 |   |   |   |   | playing | play | 0 | 23
2910 |   |   |   |   | playing | play | 0 | 23
2910 | L1 | 800 | 24 | 30 |   |   |   |  
2911 | L1 | 833 | 25 | 30 |   |   |   |  
2911 | L1 | 800 | 24 | 30 |   |   |   |  
2911 |   |   |   |   | playing | play | 0 | 23
2912 | L1 | 833 | 25 | 30 |   |   |   |  
2912 | L1 | 800 | 24 | 30 |   |   |   |  
2912 |   |   |   |   | playing | play | 0 | 23
2913 | L1 | 800 | 24 | 30 |   |   |   |  
2913 |   |   |   |   | playing | play | 0 | 23
2913 | L1 | 833 | 25 | 30 |   |   |   |  
2914 | L1 | 833 | 25 | 30 |   |   |   |  
2914 |   |   |   |   | playing | play | 0 | 23
2915 | L1 | 867 | 26 | 30 |   |   |   |  
2915 | L1 | 833 | 25 | 30 |   |   |   |  
2915 |   |   |   |   | playing | play | 0 | 23
2916 | L1 | 833 | 25 | 30 |   |   |   |  
2916 | L1 | 867 | 26 | 30 |   |   |   |  
2916 |   |   |   |   | playing | play | 0 | 23
2917 | L1 | 833 | 25 | 30 |   |   |   |  
2917 | L1 | 867 | 26 | 30 |   |   |   |  
2917 |   |   |   |   | playing | play | 0 | 23
2918 | L1 | 867 | 26 | 30 |   |   |   |  
2918 |   |   |   |   | playing | play | 0 | 23
2919 | L1 | 867 | 26 | 30 |   |   |   |  
2919 |   |   |   |   | playing | play | 0 | 23
2920 | L1 | 867 | 26 | 30 |   |   |   |  
2921 | L1 | 867 | 26 | 30 |   |   |   |  
2921 |   |   |   |   | playing | play | 0.750534 | 22
2922 | L1 | 867 | 26 | 30 |   |   |   |  
2922 | L1 | 900 | 27 | 30 |   |   |   |  
2922 |   |   |   |   | playing | play | 0.750534 | 22
2923 | L1 | 933 | 28 | 30 |   |   |   |  
2923 | L1 | 867 | 26 | 30 |   |   |   |  
2923 | L1 | 900 | 27 | 30 |   |   |   |  
2923 |   |   |   |   | playing | play | 0.750534 | 22
2924 | L1 | 900 | 27 | 30 |   |   |   |  
2924 | L1 | 933 | 28 | 30 |   |   |   |  
2924 |   |   |   |   | playing | play | 0.750534 | 22
2925 | L1 | 933 | 28 | 30 |   |   |   |  
2925 |   |   |   |   | playing | play | 0.750534 | 22
2926 | L1 | 933 | 28 | 30 |   |   |   |  
2926 |   |   |   |   | playing | play | 0.750534 | 22
2927 | L1 | 967 | 29 | 30 |   |   |   |  
2927 | L1 | 933 | 28 | 30 |   |   |   |  
2927 |   |   |   |   | playing | play | 0.750534 | 22
2928 | L1 | 967 | 29 | 30 |   |   |   |  
2928 | L1 | 933 | 28 | 30 |   |   |   |  
2928 |   |   |   |   | playing | play | 0.750534 | 22
2929 | L1 | 967 | 29 | 30 |   |   |   |  
2929 |   |   |   |   | playing | play | 0.750534 | 22
2929 | L1 | 933 | 28 | 30 |   |   |   |  
2930 |   |   |   |   | playing | play | 0.750534 | 22
2930 | L1 | 967 | 29 | 30 |   |   |   |  
2931 | L1 | 1000 | 30 | 30 |   |   |   |  
2931 | L1 | 967 | 29 | 30 |   |   |   |  
2931 |   |   |   |   | playing | play | 0.750534 | 22
2932 | L1 | 967 | 29 | 30 |   |   |   |  
2932 | L1 | 1000 | 30 | 30 |   |   |   |  
2932 |   |   |   |   | playing | play | 0.750534 | 22
2933 | L1 | 967 | 29 | 30 |   |   |   |  
2933 | L1 | 1000 | 30 | 30 |   |   |   |  
2933 |   |   |   |   | playing | play | 0.750534 | 22
2934 | L1 | 1000 | 30 | 30 |   |   |   |  
2934 |   |   |   |   | playing | play | 0.750534 | 22
2935 | L1 | 1000 | 30 | 30 |   |   |   |  
2935 |   |   |   |   | playing | play | 0.750534 | 22
2936 | L1 | 1000 | 30 | 30 |   |   |   |  
2936 | L1 | 1033 | 31 | 30 |   |   |   |  
2936 |   |   |   |   | playing | play | 0.750534 | 22
2937 | L1 | 1033 | 31 | 30 |   |   |   |  
2937 |   |   |   |   | playing | play | 0.750534 | 22
2938 | L1 | 1033 | 31 | 30 |   |   |   |  
2938 |   |   |   |   | playing | play | 0.750534 | 22
2939 | L1 | 1033 | 31 | 30 |   |   |   |  
2939 |   |   |   |   | playing | play | 0.750534 | 22
2940 | L1 | 1067 | 32 | 30 |   |   |   |  
2940 | L1 | 1033 | 31 | 30 |   |   |   |  
2940 |   |   |   |   | playing | play | 0.750534 | 22
2941 | L1 | 1067 | 32 | 30 |   |   |   |  
2941 | L1 | 1033 | 31 | 30 |   |   |   |  
2941 |   |   |   |   | playing | play | 0.750534 | 22
2942 |   |   |   |   | playing | play | 0.750534 | 22
2942 | L1 | 1033 | 31 | 30 |   |   |   |  
2942 | L1 | 1067 | 32 | 30 |   |   |   |  
2943 |   |   |   |   | playing | play | 0.750534 | 22
2943 | L1 | 1067 | 32 | 30 |   |   |   |  
2944 | L1 | 1100 | 33 | 30 |   |   |   |  
2944 |   |   |   |   | playing | play | 0.750534 | 22
2944 | L1 | 1067 | 32 | 30 |   |   |   |  
2945 | L1 | 1100 | 33 | 30 |   |   |   |  
2945 | L1 | 1067 | 32 | 30 |   |   |   |  
2945 |   |   |   |   | playing | play | 0.750534 | 22
2946 | L1 | 1067 | 32 | 30 |   |   |   |  
2946 | L1 | 1100 | 33 | 30 |   |   |   |  
2946 |   |   |   |   | playing | play | 0.750534 | 22
2947 |   |   |   |   | playing | play | 0.750534 | 22

**Comment by jpiesing** [comment]
> Here are the extraction from C0036:
> Can still see the 0 current time no differences. @jpiesing can you confirm 0036 tested with the fix please?

C0036 was made on the morning of July 1st using the version which was current at that time.

**Comment by yanj-github** [comment]
![image](https://user-images.githubusercontent.com/59022223/124614498-327fc280-de6c-11eb-9023-83c399f44460.png)

**Comment by FritzHeiden** [comment]
I am unable to reproduce this. I double checked the code, current time is read from the video on every qr code update. I now also include the current time in the overlayed text.

**Comment by jpiesing** [comment]
I'll do a new test run today.

**Comment by jpiesing** [comment]
No zero values appear in the run today.
