### ISSUE TITLE
validating the 2021-07-07 test content

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/dpctf-tests#44]
@louaybassbouss As discussed during the call I'm opening an issue here.

When you have time, could you please the new content available in all the frame rates? https://dash.akamaized.net/WAVE/vectors/2021-07-07/avc_sets

Please comment in https://github.com/cta-wave/Test-Content-Generation/issues/29 and https://github.com/cta-wave/Test-Content-Generation/issues/30.

Happy testing!

**Comment by louaybassbouss** [comment]
> @louaybassbouss As discussed during the call I'm opening an issue here.
> 
> When you have time, could you please the new content available in all the frame rates? https://dash.akamaized.net/WAVE/vectors/2021-07-07/avc_sets
> 
> Please comment in [cta-wave/Test-Content-Generation#29](https://github.com/cta-wave/Test-Content-Generation/issues/29) and [cta-wave/Test-Content-Generation#30](https://github.com/cta-wave/Test-Content-Generation/issues/30).
> 
> Happy testing!

Thanks @rbouqueau  we will do

**Comment by FritzHeiden** [comment]
I performed a test run and everything looks good. The new tests are available in the generated directory in the repository.

![image](https://user-images.githubusercontent.com/9076000/126641955-5fcce302-a1ad-46ee-a4a9-fd49a579ce82.png)

**Comment by jpiesing** [comment]
@andyburras @yanj-github would Eurofins be able to run the tests with the 25 / 50Hz video and the 29.97 / 59.94 Hz video & check the observation framework is happy?

**Comment by yanj-github** [comment]
I have tested 59.94 for sequetial playback test and 29.97 for random access tests to find out if the starting frames checked currectly. OF is observing then correctly as expected. I didnt check 25 / 50Hz video but they wont make any differences to OF.

**Comment by jpiesing** [comment]
@rbouqueau Do the above cover the validations you expect? If so then please close this issue.

**Comment by rbouqueau** [comment]
We can close. Please re-open if you encounter any issue.
