### ISSUE TITLE
Question about the random_access_time 

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#45]
random_access_time set to default value 10 currently on TR configuration.
When the random_access_time set to 10 seconds, it appears to me that the playback starts from 00:10:033 frame number 301.
Is this what we are expecting please?
Do we expect to include 10 seconds or start from next frame from 10 seconds? 
Should it start from 10:00:00 frame number 300 or from 00:10:033 frame number 301?

**Comment by FritzHeiden** [comment]
This is what I would expect. The frame numbering starts with 1, so at timestamp 00:00:00 the video starts with frame 1. Therefore, when skipping to 10:00:00, starting with frame number 301 seems right to me. Please correct me if I am wrong.

**Comment by yanj-github** [comment]
> 
> 
> This is what I would expect. The frame numbering starts with 1, so at timestamp 00:00:00 the video starts with frame 1. Therefore, when skipping to 10:00:00, starting with frame number 301 seems right to me. Please correct me if I am wrong.

Thanks @FritzHeiden I just wanted to know what to expect on TR end so that OF can match with it. If no one have an objection to it I will keep it same on OF as well to check from next frame and skipping 10:00:00.
