### ISSUE TITLE
generates audio tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#46]
While waiting to get audio content to akamai server, I have tried to generate 8.2 tests with some audio content that we have generated. 
However, I found the issue on test generation that providing same video mpd for different audio mpds will only generates one test which has last audio mpd in the row.

I have following rows added to my test.csv file:
_"sequential-track-playback","/content/avc_sets/15_30_60/t1/stream.mpd","/content/eac3_sets/at1/stream.mpd","eac3-2021-09-07-local"
"sequential-track-playback","/content/avc_sets/15_30_60/t1/stream.mpd","/content/eac3_sets/at2/stream.mpd","eac3-2021-09-07-local"_

Which only generated one test with /content/eac3_sets/at2/stream.mpd audio instead of two tests.

The reason for adding video mpd for audio only test is:
- TR wont playback anything if video mpd is missing
- Some observation requires video to capture QR code
- Some devices don’t support audio only playback

**Comment by louaybassbouss** [comment]
Thanks @yanj-github agree with you we should generate 2 tests.  @FritzHeiden  can you check the test generator script please.

**Comment by FritzHeiden** [comment]
This bug is already fixed in the upcoming update for the generate-tests.py script. You can find it in the [feature-multi-mpd](https://github.com/cta-wave/dpctf-tests/tree/feature-multi-mpd) branch

**Comment by louaybassbouss** [comment]
@yanj-github is it Ok for you to use it from the feature-multi-mpd branch?

**Comment by yanj-github** [comment]
Yes this will be fine to be stay in the same branch for time being.

**Comment by yanj-github** [comment]
I have checked this it looks fine to me. Close this ticket when it merged to master.

**Comment by louaybassbouss** [comment]
@yanj-github  can you confirm that we can merge the [feature-multi-mpd ](https://github.com/cta-wave/dpctf-tests/tree/feature-multi-mpd) in the master branch?

**Comment by yanj-github** [comment]
@louaybassbouss I think it would be best to wait until next OF release otherwise new branch won't work with current version of OF. We are working on OF currently so it will be ready soon. I will keep you posted when it is ready to go. Thanks.
