### ISSUE TITLE
8.13 Restricted Splicing of Encrypted Content

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#47]
This is an issue to make sure that completing this test doesn't get lost after https://github.com/cta-wave/dpctf-tests/issues/22 has been addressed for 8.8.

**Comment by jpiesing** [comment]
Now we have https://github.com/cta-wave/dpctf-tests/blob/stable/restricted-splicing-of-encrypted-content-https.html , can this issue be closed?

**Comment by louaybassbouss** [comment]
> @louaybassbouss Now we have https://github.com/cta-wave/dpctf-tests/blob/stable/restricted-splicing-of-encrypted-content-https.html , can this issue be closed?

Thanks @jpiesing  yes this can be closed.
