### ISSUE TITLE
random_access_fragment parameter

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#48]
As far as I know the random_access_fragment parameter allows any data type from the configuration file. 
However, it seems that it supports only integer on the TR. 

When random_access_fragment is float the OF calculates starting frames based on its given float value but on TR playback starts on different number. 
e.g: random_access_fragment=10.2 
TR starts from 301 which is same as random_access_fragment=10

What data type should random_access_fragment support?

**Comment by jpiesing** [comment]
It has to be integer.
Random access to anything other than the start of a fragment is a different test.

**Comment by jpiesing** [comment]
> > 
> 
> Thanks to confirm.
> Is this same for the parameter random_access_time as well please?

Depends on the units. Random access to time can by definition be fractional seconds.
If the units are seconds then it's a floating point number.
If the units are milliseconds or 1/100ths of a second then it might be integers.
HTML5's currentTime https://html.spec.whatwg.org/multipage/media.html#dom-media-currenttime is a double so I would assume by default this is a double.

**Comment by yanj-github** [comment]
Thanks @jpiesing 
As far as I know the TR does not stop user from entering the float value for random_access_fragment but it cast is to integer. 
However, OF just take the value what is in the configuration file. Therefor the result is not aligned. 
Do you want OF to do the same please? Or would it better for TR to flag the configuration fault when user enter invalid value.

@louaybassbouss Does random_access_time allow double? and the unit is in seconds (which I think it is) please? Is this been documented anywhere please? Sorry if I missed any documentation, if you can point it to me please?

**Comment by louaybassbouss** [comment]
> Thanks @jpiesing As far as I know the TR does not stop user from entering the float value for random_access_fragment but it cast is to integer. However, OF just take the value what is in the configuration file. Therefor the result is not aligned. Do you want OF to do the same please? Or would it better for TR to flag the configuration fault when user enter invalid value.
> 
> @louaybassbouss Does random_access_time allow double? and the unit is in seconds (which I think it is) please? Is this been documented anywhere please? Sorry if I missed any documentation, if you can point it to me please?

@yanj-github it is documented in https://github.com/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md . Unit is seconds and it is a floating number.

**Comment by jpiesing** [comment]
I suggest closing this one. Anyone who edits the configuration file needs to **really** know what they're doing. We should not invest time & energy in making the code robust if people doing such edits make mistakes.
