### ISSUE TITLE
when playout parameter is missing

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#49]
Currently, the playout parameters are not set up programmatically after the test runner is installed.
As far as I am aware, we are expecting user to configure the playout parameters manually for each test that they want to run depends on their requirements. I don’t see this process is documented anywhere but can anyone confirm if this is what we expected please? 

If the user hasn't configured the playout parameter, TR still plays back the content.
@louaybassbouss has confirmed that, by default, the first representation of the first MPD is played. 

The observation framework will report the failure due to playout parameter is missing. 
User will find out the configuration missing after they have finished running OF. 
I think it would be preferable if TR can flag the configuration error beforehand.

@louaybassbouss said TR can end the test with an error when playout is missing, if this is preferred.

**Comment by louaybassbouss** [comment]
> Currently, the playout parameters are not set up programmatically after the test runner is installed.
> As far as I am aware, we are expecting user to configure the playout parameters manually for each test that they want to run depends on their requirements. I don’t see this process is documented anywhere but can anyone confirm if this is what we expected please?
> 
> If the user hasn't configured the playout parameter, TR still plays back the content.
> @louaybassbouss has confirmed that, by default, the first representation of the first MPD is played.
> 
> The observation framework will report the failure due to playout parameter is missing.
> User will find out the configuration missing after they have finished running OF.
> I think it would be preferable if TR can flag the configuration error beforehand.
> 
> @louaybassbouss said TR can end the test with an error when playout is missing, if this is preferred.

As I mentioned in the other thread, I prefer to provide a default `playout` value for any test that requires it. And of course document this parameter and how users can override it if needed. 

Can you provide the configuration you use and we can update the tests-config.json with those as default values?

**Comment by jpiesing** [comment]
> As far as I am aware, we are expecting user to configure the playout parameters manually for each test that they want to run depends on their requirements. I don’t see this process is documented anywhere but can anyone confirm if this is what we expected please?

Absolutely not. We are not expecting users to configure anything.

**Comment by yanj-github** [comment]
> 
> 
> > As far as I am aware, we are expecting user to configure the playout parameters manually for each test that they want to run depends on their requirements. I don’t see this process is documented anywhere but can anyone confirm if this is what we expected please?
> 
> Absolutely not. We are not expecting users to configure anything.

Thanks to confirm. Which is more clear to me now. 
So the issue is that the playout parameters are missing from the https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json. 
On pervious thread you have mentioned that we should not provide default parameter for the test code. I do agree as the playout might be different and it related to the content that is linked to the test code. 
What is the best way to define the playout please? Should it be defined for every test that uses playout please?  If so what do you recommend please?

**Comment by jpiesing** [comment]
> On pervious thread you have mentioned that we should not provide default parameter for the test code.

Can you provide a reference to this so I can see the context?

> I do agree as the playout might be different and it related to the content that is linked to the test code.

playout will be different for each test (combination of HTML+JS template and stream(s)). However it will need to be provided as part of the test suite WAVE delivers to the industry.

> What is the best way to define the playout please? Should it be defined for every test that uses playout please?

Yes (assuming test = combination of HTML+JS+stream(s)).

> If so what do you recommend please?

Which gaps are there?

**Comment by yanj-github** [comment]
@jpiesing 

> Can you provide a reference to this so I can see the context?

https://github.com/cta-wave/dpctf-tests/issues/42#issuecomment-866913171

> 
>     If so what do you recommend please?
> 
> Which gaps are there?
> 
As far as I know, expected playout need to be defined for all the tests that requires it. This requires understaning of the test requirement such as whether swiching set swiches once twice or 3 times etc. And also playout is based on the contents that is linked, which need to be valid based on the requirement and content that is linked. 

- Define the test logic / requirement. 
e.g: avc_15_30_60-2021-07-07-online/switching-set-playback__ss1.html switches once from 1st video Representation to 2nd Representation 
- Define playout according to step 1 above based on the content ss1 and write to the test-config.json

**Comment by jpiesing** [comment]
> @jpiesing
> 
> > Can you provide a reference to this so I can see the context?
> 
> [#42 (comment)](https://github.com/cta-wave/dpctf-tests/issues/42#issuecomment-866913171)
> 

That response remains correct. There needs to be a (default) value of playout separately defined for each and every single test which uses it. There's no such thing as a default value of playout that applies to more than one test.

> > ```
> > If so what do you recommend please?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which gaps are there?
> 
> As far as I know, expected playout need to be defined for all the tests that requires it.

Yes. Absolutely. It could not be otherwise.

> This requires understaning of the test requirement such as whether swiching set swiches once twice or 3 times etc. And also playout is based on the contents that is linked, which need to be valid based on the requirement and content that is linked.
> 

Yes.

>     * Define the test logic / requirement.
>       e.g: avc_15_30_60-2021-07-07-online/switching-set-playback__ss1.html switches once from 1st video Representation to 2nd Representation
> 

I've provided examples in various issues.

>     * Define playout according to step 1 above based on the content ss1 and write to the test-config.json

**Comment by jpiesing** [comment]
There are 4 tests that need playout according to the DPCTF spec. Each of them will need its own value of playout[] defining that is aligned with the content to be used for that test.
8.5 Switching Set Playback
8.8 Playback over WAVE Baseline Splice Constraints
8.10 Overlapping Fragments
9.4 Splicing of WAVE Program with Baseline Constraints

I remember making a proposal for 8.5 which stepped through each CMAF track in the MPD one by one in one direction and then back again in the other direction.

**Comment by yanj-github** [comment]
> 
> 
> There are 4 tests that need playout according to the DPCTF spec. Each of them will need its own value of playout[] defining that is aligned with the content to be used for that test.
> 8.5 Switching Set Playback
> 8.8 Playback over WAVE Baseline Splice Constraints
> 8.10 Overlapping Fragments
> 9.4 Splicing of WAVE Program with Baseline Constraints
> 
> I remember making a proposal for 8.5 which stepped through each CMAF track in the MPD one by one in one direction and then back again in the other direction.

This is fine on the OF point. @louaybassbouss will this work on TR please? 

Dose the following test require playout as well please? 
8.11 Full Screen Playback of Switching Sets
8.13 Restricted Splicing of Encrypted Content
8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content

**Comment by jpiesing** [comment]
> Dose the following test require playout as well please?

Yes. The DPCTF spec just doesn't use the word "playout".

> 8.11 Full Screen Playback of Switching Sets

This is the same as 8.9 & playout[] should be the same.

> 8.13 Restricted Splicing of Encrypted Content

I don't understand this one.

> 8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content

I expect this one will be somewhat like 8.8. Two switching sets each with one track, one switching set encrypted and one not encrypted.
I expect playout would take the first half of the encrypted segments then the all the unencrypted segments then the remainder of the encrypted segments. 

{1,0,

**Comment by louaybassbouss** [comment]
PS: [tests-config.json (in feature-mpd-branch)](https://github.com/cta-wave/dpctf-tests/blob/feature-multi-mpd/test-config.json) includes default values for `playout` (and `loading` for out-of-order-loading tests).

**Comment by jpiesing** [comment]
> PS: [tests-config.json (in feature-mpd-branch)](https://github.com/cta-wave/dpctf-tests/blob/feature-multi-mpd/test-config.json) includes default values for `playout` (and `loading` for out-of-order-loading tests).

@yanj-github Please can you give us a precise list of what is blocking you?

**Comment by yanj-github** [comment]
Thanks @louaybassbouss 
Regarding to switching set tests it is fine for OF not a blocker.
However, @jpiesing said above that

>  I remember making a proposal for 8.5 which stepped through each CMAF track in the MPD one by one in one direction and then back again in the other direction.

However the following seems only stepped through each CMAF track in the MPD one by one in one direction. 
```
  "avc_15_30_60-2021-07-07-local/switching-set-playback__ss1.html": {
    "playout": [
      [1, 1, 1],  [1, 1, 2],  [1, 1, 3],  [1, 1, 4],
      [1, 2, 5],  [1, 2, 6],  [1, 2, 7],  [1, 2, 8],
      [1, 3, 9],  [1, 3, 10], [1, 3, 11], [1, 3, 12],
      [1, 4, 13], [1, 4, 14], [1, 4, 15],
      [1, 5, 16], [1, 5, 17], [1, 5, 18], [1, 5, 19],
      [1, 6, 20], [1, 6, 21], [1, 6, 22], [1, 6, 23],
      [1, 7, 24], [1, 7, 25], [1, 7, 26], [1, 7, 27],
      [1, 8, 28], [1, 8, 29], [1, 8, 30]
    ]
  },
```
Either way will work on OF it doesn matter on OF side.
But to make it clear so that playout meet requirement of "stepped through each CMAF track in the MPD one by one in one direction and then back again in the other direction"? @jpiesing 

Regarding to splicing tests, are they required to have two switching sets or two single tracks please?
```
"avc_15_30_60-2021-07-07-online/playback-over-wave-baseline-splice-constraints__**t1_t2**.html": {
    "playout": [
      [1, 1, 1],  [1, 1, 2],  [1, 1, 3],  [1, 1, 4],  [1, 1, 5],
      [1, 1, 6],  [1, 1, 7],  [1, 1, 8],  [1, 1, 9],  [1, 1, 10],
      [1, 1, 11], [1, 1, 12], [1, 1, 13], [1, 1, 14], [1, 1, 15],
      [2, 1, **7**],  [2, 1, 8],  [2, 1, 9],
      [2, 1, 10], [2, 1, 11], [2, 1, 12]
    ]
  },
```
And it should be main TOF and big bucket bunny ad. I think this is because we are blocked on big bucket bunny ad contents isnt it?

On the OF perspective, I would like to be clear about whether the main and ad are switching set or single tracks. If it should be swithcing sets, whether or not it switches within splice please?
Also I was expecting ad to always start from 1, does OF need to support ad to start from any defined fragment please?

**Comment by yanj-github** [comment]
Thanks @louaybassbouss This has unblocked us for implementing splicing observation. 
Can I close this issue @jpiesing and @louaybassbouss?

**Comment by jpiesing** [comment]
> Thanks @louaybassbouss This has unblocked us for implementing splicing observation.
> Can I close this issue @jpiesing and @louaybassbouss?

I think the original question has been answered - all tests need an explicit specification of playout. If playout is needed & not explicitly specified then open a new github issue.
