### ISSUE TITLE
Mezzanine identifier

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/dpctf-tests#52]
In the DASH MPD for the test content, we need use an identifier for the mezzanine. It consists of a key (a uri) value (a string) pair in the Asset Identifier.

Multiple Options are possible:

Option 1:
- key is the URL to the mezzanine content
- value is the start time (if not present) it is zero 

Option 2:
- key is a well defined URN such as 
   - a) urn:cta:tech:wave-test-mezzanine
   - b) http://ctawave.tech/mezzanine
- value is
  - a)   the URL to the mezzanine content
  - b)   a UUID value generated by the mezzanine creator
  - c)   a well defined string defined by the mezzanine creator

Note that URLs should resolve properly.

**Comment by jpiesing** [comment]
@nicholas-fr ?

**Comment by cta-source** [comment]
Regarding option 2: If we need a well-defined URN, CTA can apply via instructions in [RFC8141](https://www.rfc-editor.org/rfc/rfc8141.html).  Dropping this here for future reference in case we go down this road.  Note that receiving registration confirmation will likely require "weeks" (or "months"), so we should plan to get this going sooner rather than later if we do so.

**Comment by cta-source** [comment]
@haudiobe, I'd like to expand on the discussion of the URL structure for mezzanine content, as discussed in today's (9/22/2021) DPCTF meeting.  

URL redirection (via CNAME or other method) means we rely on an IT department to maintain that redirection.  It's a single point of failure for the test suite.  This is a pretty good reason to look for another way to solve this problem.  

We also discuss using a relative link with the test suite accepting a parameter of a correct domain name (or more, for example a prefix of "https://cta.tech/wave").   This approach requires some code change now (anything that parses mezz content) but would give us portability when we need to change hosts.  As an added bonus, we could switch on the fly between different mezzanine versions (this is typically useful for switching between the "live" released version, and a newer unreleased "staging" version).  I prefer this approach and welcome other inputs.

**Comment by nicholas-fr** [comment]
If I have understood, there are 2 actions needed:

1. Setting up a URL (https://cta.tech/wave) to redirect to https://dash-large-files.akamaized.net/WAVE/
2. Modifying any code that accesses mezzanine content to use a URL prefix parameter (easily updated later on as needed) and the fixed path to mezzanine releases or mezzanine content under review.

Code would use https://cta.tech/wave/ as the URL prefix (via parameter), appending either:

- `/Mezzanine/releases/<version_number>/`
- or `/Mezzanine/under_review/<upload_date>/`

to build the complete URL path to a particular set of mezzanine content.
That selection could be done via parameter also, or the code could automatically use the latest release.

The mezzanine filenames follow a known template: `<prefix>_<label>_<WxH>@<fps>_<duration>.<mp4 | json>`

Which results in the following examples:

https://cta.tech/wave/Mezzanine/releases/2/splice_ad_bbb_AD-B1_1920x1080@29.97_21.255.json
https://cta.tech/wave/Mezzanine/releases/2/splice_main_tos_B1_1920x1080@29.97_10.json
https://cta.tech/wave/Mezzanine/releases/2/croatia_A1_480x270@12.5_60.json
https://cta.tech/wave/Mezzanine/under_review/2021-08-05/croatia_A1_480x270@12.5_60.json

**Comment by jpiesing** [comment]
Can we rewind the discussion a little?
I'm not convinced that we need it at all.
@haudiobe What problem is this solving?

If we do need it, why do we need URLs that resolve at all? That really seems like a lot of work to come up with something that is maintainable in the medium term.

**Comment by andyburras** [comment]
Somewhat related... the Observation Framework will need access to the audio mezzanine used in a test (method as yet TBD). It needs to do a cross-correlation between this and the recorded audio.
If the audio mezzanine itself is updated, or if a test is regenerated using different audio mezzanine to an ealier version of the test then the OF will need access to the correct one. Having some sort of unique ID may help manage this going forwards when there potentially may be different versions of tests floating around.

**Comment by cta-source** [comment]
@andyburras, we are currently (in the study project) embedding a pseudo-random noise (PN or PRN) pattern in audio.  In the current concept, that PN sequence is always one of four "known" PN sequences that are archived for this project.  The goal is to cross-correlate those PN sequences.  If there is music or other audio in the test clip, that would be noise overlaid on the PN sequence.  

So if the current mezz content generation is including music, that's different from what we'd been discussion in the DPCTF Test Runner meetings: wired audio, no music or added noise, just the PN sequence.

**Comment by cta-source** [comment]
I should add--we're actually saying the same thing, that the OF needs a priori information to cross-correlate with.  But that a priori information is one of four files: PN01.wave, PN02.wav, PN03.wav and PN04.wav.

**Comment by andyburras** [comment]
Agreed. And if there was a necessity to regenerate audio mezzanine for whatever reason then provided it was given a unique name e.g. PN05, PN06, etc. then that should cover that issue.
The other aspect is if the test content for an existing test needs to be regenerated for some reason and has to use a different audio mezzanine. We need to be able to map the current running version of a test to its audio mezzanine.

**Comment by louaybassbouss** [comment]
independent from the option you decide to select, from test runner perspective, we need to add a new property (e.g. `mezzanineId`) for each audio/video mezzanine content used in a test. This will be provided  in [tests.json](https://github.com/cta-wave/dpctf-tests/blob/feature-multi-mpd/generated/tests.json). while generating the tests. @jpiesing  can you confirm?

**Comment by haudiobe** [comment]
All,

I rechecked the details again, and I believe we need some more consistency, because we use the different versions.

If I check here, then the assets do not match.

Here is my suggestion:
1) we use the release and the content for content identification, for example 2/croatia
2) for each Representation, we use the "id" in the MPD to specify the exact version, example "id"="A1_480x270@12.5_60"

I know this needs some update of the test content, but it makes it consistent for the test runner.

**Comment by jpiesing** [comment]
> All,
> 
> I rechecked the details again, and I believe we need some more consistency, because we use the different versions.
> 
> If I check here, then the assets do not match.
> 
> Here is my suggestion:
> 
>     1. we use the release and the content for content identification, for example 2/croatia
> 
>     2. for each Representation, we use the "id" in the MPD to specify the exact version, example "id"="A1_480x270@12.5_60"
> 
> 
> I know this needs some update of the test content, but it makes it consistent for the test runner.

@haudiobe I'm still a little lost about what would read this identifier & what would it do with the identifier that it read?

**Comment by gitwjr** [comment]
Nicholas will check with Thomas on this and see if it can be closed.

**Comment by gitwjr** [comment]
@@rcottingham to check

**Comment by gitwjr** [comment]
@nicholas-fr  Video needs to be reviewed and comment. If Nicholas is OK with it as is, he will close.

**Comment by gitwjr** [comment]
Close. @haudiobe can reopen if it is still unclear.
