### ISSUE TITLE
Program Information in MPD

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/dpctf-tests#53]
In order to identify the CTA WAVE test asset vector properly, it is proposed to add the ProgramInformation into the test MPD.

The Program Information is currently proposed to be set as follows
- The ProgramInformation element shall be present with the following information
  - The Title element may be present as an instructive summary of the Test Asset.
  - The Source element shall be present be set to "CTA WAVE"
  - The Copyright element shall be present and shall bet set to <how to do>
  - The @moreInformationURL may be present and provide a link to additional information on this Test Asset, for example who produced it, etc.

Please comment on the above and also provide a proper copyright statement that is then added.

**Comment by cta-source** [comment]
Regarding ProgramInformation, should it include something like,

- 
   - The Mezzanine Annotations version information, to identify the mezzanine specification version for programmers seeking to work with the annotations?

**Comment by louaybassbouss** [comment]
@haudiobe I see two parts of this issue:
1. Provide ProgramInformation in the test MPD. Maybe better to raise issue in Test-Content project.
2. Make ProgramInformation available for the OF. We already parse the MPD while generating the tests and provide all details in [tests.json](https://github.com/cta-wave/dpctf-tests/blob/feature-multi-mpd/generated/tests.json). We will add a new property  `ProgramInformation` with content from the test MPD.

**Comment by jpiesing** [comment]
28th September meeting
Copyright information is already in the manifest.
@haudiobe and @rbouqueau to discuss offline & ensure the DPCTF spec is correct.

**Comment by jpiesing** [comment]
@haudiobe @rbouqueau Have you checked the MPDs generated by the scripts are correct? Can we close this issue?

**Comment by rbouqueau** [comment]
The MPD were checked manually against the DASH-IF validator. The test-content-generation README is being updated to reflect the limitations of the current approach w.r.t. validation.

**Comment by gitwjr** [comment]
@rbouqueau check to see if Romain updated the readme and if that closes this issue.

**Comment by rbouqueau** [comment]
Yes, both the feature and the README are now ok. I'm closing this issue.

**Comment by rbouqueau** [comment]
PS: it seems I don't have the rights to close the issue, please someone make it for me! Thx

**Comment by gitwjr** [comment]
Both the features and the README are now OK.
