### ISSUE TITLE
update some tests to use 20s or 30s content rather than 60s

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#56]
We may consider updating some tests to use 20s or 30s sequences instead of 60s. If so, which?

Sequential track playback generally tests if some content plays at all. If 20s or 30s of a stream plays OK then that's probably good enough.
The same applies for the random access tests.
Switching set playback probably needs 60s.
I'm not sure about the others.

**Comment by louaybassbouss** [comment]
> We may consider updating some tests to use 20s or 30s sequences instead of 60s. If so, which?
> 
> Sequential track playback generally tests if some content plays at all. If 20s or 30s of a stream plays OK then that's probably good enough. The same applies for the random access tests. Switching set playback probably needs 60s. I'm not sure about the others.

@jpiesing @yanj-github  do you like to see that last 20s or 30s,... of the sequences? it is fine from the OF perspective if the first part or last part of the content is not displayed for these tests?  

Basically you can already now use this feature just by configuring the `playout` parameter. For example for Sequential track playback we can use the following if you want to play only the first 5 fragments.  

```js
[[1,1,1],  [1,1,2], [1,1,3], [1,1,4], [1,1,5]]
```

@FritzHeiden please correct me if I am wrong ;)

**Comment by jpiesing** [comment]
> If we use Mezzanine/Test Content with 20s or 30s then I don't think we need to update the Test Implementation. We only need to add new combinations to the CSV and generate new tests. The test implementation reads the duration from the MPD (it is not hardcoded).

Good.

**Comment by yanj-github** [comment]
How about 30s for most of tests but swiching is 60s and splicing 60s mians stream and 30s ad?
This will be applicable to audio streams as well.

**Comment by jpiesing** [comment]
> How about 30s for most of tests but swiching is 60s and splicing 60s mians stream and 30s ad?
> This will be applicable to audio streams as well.

That's close to my ideas.
![image](https://user-images.githubusercontent.com/8490792/153387201-a7bf491a-a1a4-497c-8926-b74e2e631a79.png)

**Comment by jpiesing** [comment]
Feb 15th
Why is splicing so short? We agreed. Don't remember why.
If we increased the length of the splicing test to 30s we could use it for other tests without regenerating new streams.
Splicing main is not quite identical to t1 & has a special segment duration for splicing.
No problem for TP Vision to make a small number of 30s mezzanine.

**Comment by rbouqueau** [comment]
@jpiesing Links regarding the splicing duration:

- https://github.com/cta-wave/mezzanine/issues/19#issuecomment-919247757
- constraints for perfect a/v cmaf fragments alignment: https://github.com/cta-wave/mezzanine/issues/40#issue-948883866

**Comment by jpiesing** [comment]
@rbouqueau @nicholas-fr @louaybassbouss @yanj-github Here is my proposal for reducing the test execution time.

1) Nicholas creates a 1920x1080 mezzanine stream with duration 30s. No other resolutions have a 30s mezzanine.
2) The current streams t1 to t17 inclusive (all of which are 1920x1080) are all re-encoded from this 30s mezzanine but otherwise unchanged.
3) Streams t20 onwards all remain at 60s (note that t20 is the only 1920x1080 one of these).
4) Since t1 is now 30s duration, a new stream is generated which is the same as the current t1. This is used only in the Switching Set tests. Call it t19 or t35 or t20 (& renumber existing t20 to t21 and so on).
5) Encrypted stream is re-encoded based on the 30s mezzanine
6) No change to splicing tests.

This seems to bring a reasonable reduction in the test duration as only the switching set tests remain at 60s. It doesn't increase the complexity of mezzanine and test content very much. We have one extra mezzanine and one extra test stream.

Thoughts?

**Comment by rbouqueau** [comment]
Do we have any agreement or progress here?

**Comment by jpiesing** [comment]
> Do we have any agreement or progress here?

Yes. We're waiting for @nicholas-fr to make the 30s mezzanine.

**Comment by pmaness** [comment]
Can an we simply truncate what we have down to 30s or will something else change?

**Comment by jpiesing** [comment]
> Can an we simply truncate what we have down to 30s or will something else change?

I leave @cta-source to comment about the audio mezzanine.
For video (which is what I was referring to above), there's a single static frame at the beginning and end so no, it cannot just be truncated.

**Comment by cta-source** [comment]
On the audio watermarking, there is code and content. On the code, as long as the test does not exceed the requested reference white noise file, the code is happy. So, for example, you can test 42.8 seconds of recorded audio against the reference PN01.WAV file, which 60s long, and the code is fine with that--it will test only 42.8s worth. 

For the files, we did agree to create 30s and 60s versions. Those are uploaded and ready with the rest of the next mezzanine release.

So the audio mezz stuff is done from my point of view (at least, the watermarking test files).

**Comment by pmaness** [comment]
So, Mike, what you're saying is I can go ahead with the 60 second assets and they'll automatically be truncated in the test by the duration of the video? No need to prepare multiple sets of the PN0x streams?

Thanks,
Phil

____________________________________________________
Phillip Maness | Sr. Director, Corporate Standards and Strategy
Xperi Corp.

[xpe_logo_rgb_101]
www.xperi.com<http://www.xperi.com/>

**Comment by jpiesing** [comment]
> So, Mike, what you're saying is I can go ahead with the 60 second assets and they'll automatically be truncated in the test by the duration of the video? No need to prepare multiple sets of the PN0x streams? Thanks, Phil

@pmaness I'm confused. 4 streams were uploaded as you can see here, 2 60s and 2 30s. 

![image](https://user-images.githubusercontent.com/8490792/161823162-d31d8962-1801-4d7d-a573-4fdede864959.png)

Splicing tests aren't being done for audio & these are the ones that use the 60s sequences.
If anything, I think it is only the 30s ones that are needed.

**Comment by pmaness** [comment]
@jpiesing I think we're good. I talked to @cta-source and I think it's best to do the full set for each codec, just in case. It's easier while I have resources focused on this. (6 month or a year from now, it might not be so easy)

**Comment by nicholas-fr** [comment]
30 second mezzanine content has been uploaded here:
http://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-04-21/

**Comment by rbouqueau** [comment]
I've regenerated the cfhd set, I'm uploading it.

However I have disabled the audio for now. I can generate some audio in the old fashion, or we have to add the json metadata to the audio file for it to be processed by the actual script.

**Comment by gitwjr** [comment]
Done. Closed.
