### ISSUE TITLE
audio tests not working 

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#58]
E-AC-3 and AC-4 tests are generated on the feature-multi-mpd branch
I tried the following test on TR but it is not working.
`eac3-2021-09-29-online/sequential-track-playback__at1.html`

**Comment by louaybassbouss** [comment]
> E-AC-3 and AC-4 tests are generated on the feature-multi-mpd branch I tried the following test on TR but it is not working. `eac3-2021-09-29-online/sequential-track-playback__at1.html`

@yanj-github can you provide more details?

**Comment by yanj-github** [comment]
Ch92:	promise_test: Unhandled rejection with value: object "TypeError: Failed to set the 'duration' property on 'MediaSource': The duration is not a number."

This is all I can see from the result.

**Comment by louaybassbouss** [comment]
> Ch92: promise_test: Unhandled rejection with value: object "TypeError: Failed to set the 'duration' property on 'MediaSource': The duration is not a number."
> 
> This is all I can see from the result.

We checked stream [eac3_sets/at1/](https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) in [dash.js](https://reference.dashif.org/dash.js/v4.1.0/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) and we got an error 'no streams to play'. This is because codec ac3 is not supported in Chrome Browser. You need to test on a device that supports this codec.

**Comment by jpiesing** [comment]
> We checked stream [eac3_sets/at1/](https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) in [dash.js](https://reference.dashif.org/dash.js/v4.1.0/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) and we got an error 'no streams to play'. This is because codec ac3 is not supported in Chrome Browser. You need to test on a device that supports this codec.

Chrome may not support ac3 even if the device supports ac3. Chrome uses ffmpeg to do audio decoding & ignores the audio decoding on the device. ffmpeg doesn't support ac3.

**Comment by jpiesing** [comment]
See https://www.chromium.org/audio-video for a list of codecs supported by regular Chrome and see https://developer.android.com/guide/topics/media/media-formats for regular android.

You may want to discuss with Dolby how to test this.

**Comment by yanj-github** [comment]
@jpiesing Contents are tested and verified by Dolby. 
@louaybassbouss Does current version on "feature-multi-mpd" supports audio only test if you can confirm please? No video mpd is given for this test.

**Comment by jpiesing** [comment]
> @jpiesing Contents are tested and verified by Dolby.

That wasn't the point I was trying to make.

Dolby may be able to recommend a web browser / device combination that supports MSE and AC-3/AC-4 as regular Chrome does not - regardless of what the device supports.

**Comment by FritzHeiden** [comment]
> @louaybassbouss Does current version on "feature-multi-mpd" supports audio only test if you can confirm please? No video mpd is given for this test.

audio-only tests are supported. I added some to demonstrate the functionality.

**Comment by yanj-github** [comment]
> device
Thanks @jpiesing  I was not using chorme.
I am testing with a TV which supports both E-AC-3 and AC-4 codecs and use the build in browser that supports these codecs.

**Comment by jpiesing** [comment]
> I am testing with a TV which supports both E-AC-3 and AC-4 codecs and use the build in browser that supports these codecs.

Ah. I was confused by the comment from @louaybassbouss ...

> We checked stream [eac3_sets/at1/](https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) in [dash.js](https://reference.dashif.org/dash.js/v4.1.0/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd) and we got an error 'no streams to play'. This is because codec ac3 is not supported in Chrome Browser. You need to test on a device that supports this codec.

@yanj-github As you are already doing this, I apologise for the distraction.

**Comment by yanj-github** [comment]
@louaybassbouss 
Here are what I can see from TV:
**Ch92:	promise_test: Unhandled rejection with value: object "TypeError: Failed to set the 'duration' property on 'MediaSource': The duration is not a number."**

On chorme (which it doesnt support the codec, that we know it won't work) the error is different on TR:
it says: 
Ch92:	promise_test: Unhandled rejection with value: object "TypeError: player.getVideoManifest is not a function"

Then I dont know what do to next, if you can help to debug and direct to the point what TR is expecting it would be helpful.

**Comment by louaybassbouss** [comment]
> @louaybassbouss Here are what I can see from TV: **Ch92: promise_test: Unhandled rejection with value: object "TypeError: Failed to set the 'duration' property on 'MediaSource': The duration is not a number."**
> 
> On chorme (which it doesnt support the codec, that we know it won't work) the error is different on TR: it says: Ch92: promise_test: Unhandled rejection with value: object "TypeError: player.getVideoManifest is not a function"
> 
> Then I dont know what do to next, if you can help to debug and direct to the point what TR is expecting it would be helpful.

@yanj-github can you test the audio only test added by @FritzHeiden (`audio-only-online` or `audio-only-local` in CSV) on the same TV? this is to double check that audio-only feature is working properly on this TV.

**Comment by yanj-github** [comment]
@louaybassbouss and @FritzHeiden I am trying to get last change which includes the (audio-only-online or audio-only-local in CSV) and trying to get TR updated and set up, but unable to set up the TR correctly with the last commit. 
The docker it keep restarting. Was it running fine on your end please?

**Comment by louaybassbouss** [comment]
> @louaybassbouss and @FritzHeiden I am trying to get last change which includes the (audio-only-online or audio-only-local in CSV) and trying to get TR updated and set up, but unable to set up the TR correctly with the last commit. The docker it keep restarting. Was it running fine on your end please?

@yanj-github yes we tested on our end and audio-only tests (the test in `audio-only-online` and `audio-only-local`) works fine.  Maybe you can do a cleanup and build the docker images again. @FritzHeiden any other idea?

**Comment by yanj-github** [comment]
> 
> 
> > @louaybassbouss and @FritzHeiden I am trying to get last change which includes the (audio-only-online or audio-only-local in CSV) and trying to get TR updated and set up, but unable to set up the TR correctly with the last commit. The docker it keep restarting. Was it running fine on your end please?
> 
> @yanj-github yes we tested on our end and audio-only tests (the test in `audio-only-online` and `audio-only-local`) works fine. Maybe you can do a cleanup and build the docker images again. @FritzHeiden any other idea?

Thanks @louaybassbouss Just pulled the last change there was one more commit after I fetched it, the last build is working now. Thanks.

**Comment by yanj-github** [comment]
> @yanj-github can you test the audio only test added by @FritzHeiden (audio-only-online or audio-only-local in CSV) on the same TV? this is to double check that audio-only feature is working properly on this TV.

Audio only test working fine with the latest version of TR.
The audio only feature is working on the TV. I can hear the t1.
However, still unable to playback the e-ac-3 tests.
Seeing same error message.

**Comment by yanj-github** [comment]
@FritzHeiden Just managed to check on a TV, the test stuck at status waiting but no audio been played.

**Comment by louaybassbouss** [comment]
> @FritzHeiden Just managed to check on a TV, the test stuck at status waiting but no audio been played.

@yanj-github can you share more details?

**Comment by yanj-github** [comment]
I have tired with dash player the content is playing fine I cna hear the white noise. However, when I run a test on TR nothing been playing I can see the status on the screen shows waiting for long time. "s:Waiting; a:initialise;" and nothing further happens.

**Comment by louaybassbouss** [comment]
> I have tried with dash player the content is playing fine that I can hear the white noise. However, when I run a test on TR, nothing been played. I can see the status on the screen shows waiting for long time. "s:Waiting; a:initialise;" and nothing further happens.

@yanj-github are you talking about EAC3 or AC4 content. We did some investigation on HbbTV:
* Both EAC3 and AC4 are playing properly in native player
* EAC3 is playing in dash.js (MSE) but the AC4 stream ist not playing

Is also the AC4 stream working on your side within dash.js or only the EAC3?

**Comment by yanj-github** [comment]
Hi @louaybassbouss yes my device support both and I used dashjs player online and both playing fine.

**Comment by louaybassbouss** [comment]
> Hi @louaybassbouss yes my device support both and I used dashjs player online and both playing fine.

Thanks @yanj-github we got the EAC3 working in dash.js but not the AC4 (both are playing fine in native DASH player). Can you test these two streams your side. autoplay is enabled you only need to open the URLs. 

* EAC3 Stream: https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-09-29/eac3_sets/at1/stream.mpd&autoplay=true  
* AC4 Stream:   https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-09-29/ac4_sets/at1/stream.mpd&autoplay=true

**Comment by yanj-github** [comment]
@louaybassbouss They both playing back fine here.
I think it might be the device that you are using doesnt support the AC4, in that case.

**Comment by cta-source** [comment]
> If someone just ports Chrome to a TV without knowing this, even if the TV 
> supports AC-4 via (for example) Dolby MS-12, Chrome will not support AC-4.  
   

If this is the case in this instance, it sounds like the WAVE test suite has caught an issue. It's not necessarily the first time, but it's easily explained in PPT in front of an audience, which is nice to have in one's back pocket.

**Comment by louaybassbouss** [comment]
@jpiesing  @yanj-github  we made a simple setup for running individual DPCTF tests via gh-pages for debugging/evaluation purposes without the need to setup the entire Test Runner. For example, these are the links for AC4 and EAC3 Sequential Track Playback tests. We sent these URLs to Dolby  (Pawel & Jan) and they are checking these 2 individual tests.

- AC4 Sequential Track Playback: https://cta-wave.github.io/dpctf-tests/generated/ac4-2021-09-29-online/sequential-track-playback__at1.html
- EAC3 Sequential Track Playback: https://cta-wave.github.io/dpctf-tests/generated/eac3-2021-09-29-online/sequential-track-playback__at1.html

We had also success with running the [EAC3 Test](https://cta-wave.github.io/dpctf-tests/generated/eac3-2021-09-29-online/sequential-track-playback__at1.html) in Safari Browser, it seems that  it is supported there. @mlasak will share more details on this.

**Comment by mlasak** [comment]
Sure, i'm glad to help. The EAC3 url plays fine in Safari Version 15.2 (16612.3.6.1.8, 16612) on Big Sur 11.6.2 and noice is audible.
![image](https://user-images.githubusercontent.com/1204653/149898115-3d954555-47b1-46ae-90ce-39937818d8f7.png)

After 60s test ends and the result looks like this:
![image](https://user-images.githubusercontent.com/1204653/149899639-76eb1299-69fc-43df-932d-b177e629a9e0.png)

**Comment by yanj-github** [comment]
> 

Both of the links work fine on my TV I can hear them playing the audio.

**Comment by louaybassbouss** [comment]
> > 
> 
> Both of the links work fine on my TV I can hear them playing the audio.

Great can we close this issue ?

**Comment by yanj-github** [comment]
> > > 
> > 
> > 
> > Both of the links work fine on my TV I can hear them playing the audio.
> 
> Great can we close this issue ?

Are the links exactly same as what TR plays the streams please? If there is no differences of full end to end I think we can close this issue.

**Comment by yanj-github** [comment]
No further comments closing the issue.
