### ISSUE TITLE
Consistent Storage of Test Vectors

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/dpctf-tests#59]
It is proposed to have a consistent storage format for the Test Vectors.

A first proposal is in the DPCTF, but we need to fully discuss and agree.

Proposal starting from a root directory

•	CMAF Addressable Resources shall made available as follows
•	All resources are relative to the MPD location. 
•	CMAF Header CH[k], k=1,…,K is made available at  `"<media type>/<mezzanine release>/<mezzanine>/<media profile 4cc>/<test vector id>/0"`
•	CMAF Fragments CF[k,i], i = 1,2,3,… N are made available at  `"<media type>/<mezzanine release>/<mezzanine>/<media profile 4cc>/<test vector id>/<i>"`
•	CMAF Chunks CC[k,i,j], j = 1,2,3,…, C[i] are made available at  `"<media type>/<mezzanine release>/<mezzanine>/<media profile 4cc>/<test vector id>/<i>_<j>"`

**Comment by jpiesing** [comment]
@haudiobe How close is this to what is done already?

**Comment by jpiesing** [comment]
This is the comment I remembered but could not find.

IMHO the stream is basically identified by these 3.

<media_type>/<frame_rate_family>/<stream_id>

These next two identify versions of what is logically the same stream and I would tend to put them at the end. As new versions of the stream are generated when problems are found, these will all be under the same parent.
/<mezzanine_release_version>/<upload_date>

I would also tend to put an MPD in the same directory as the media segments it refers to. That might keep things simpler.

**Comment by rbouqueau** [comment]
Call on 2021/11/23:

- <frame_rate_family> is mandatory for audio but can be ignored for audio
- For each media type, generate two mpds: one more with the media_type, and the other one for convenience with audio+video

**Comment by jpiesing** [comment]
> Call on 2021/11/23:
> 
>     * <frame_rate_family> is mandatory for audio but can be ignored for audio
> 
>     * For each media type, generate two mpds: one more with the media_type, and the other one for convenience with audio+video

Did we decide whether <frame_rate_family> is absent for audio, is "void" for audio or is something else?

So would stream a1 for codec ac4 uploaded on 2021-12-04 be something like this;

> ac4/a1/2021-11-01/2021-12-04 

or something like this;

> ac4/void/a1/2021-11-01/2021-12-04

or something else?

I have a certain preference for video and audio having the same depth of directories but having a directory "void" doesn't feel right.

**Comment by yanj-github** [comment]
Does this depth of directories somehow related to the folder name on test generation as well?

Based on what I see:
![image](https://user-images.githubusercontent.com/59022223/143073164-f46e6d0d-564d-4ddf-b745-55ed40fc6d62.png)

@jpiesing how about something like:
`ac4_sets/ac4/at1/2021-11-01/2021-12-04`

AACs are complicated but how about this?
```
caac_sets/aac_lc/at1/2021-11-01/2021-12-04
caaa_sets/he_aac_v2/at1/2021-11-01/2021-12-04
```

**Comment by jpiesing** [comment]
> @jpiesing how about something like: `ac4_sets/ac4/at1/2021-11-01/2021-12-04`
> 
> AACs are complicated but how about this?
> 
> ```
> caac_sets/aac_lc/at1/2021-11-01/2021-12-04
> caaa_sets/he_aac_v2/at1/2021-11-01/2021-12-04
> ```

@yanj-github I had simplified the codec to one level of directory & not the two levels you listed. Is there a reason for 2 levels?
@rbouqueau What do you think about the two levels of directory proposed by Yan?

**Comment by yanj-github** [comment]
@jpiesing I think it is fine to have a codec to one level.
My original reason to keep aac_lc, he_aac and he_aac_v2 as a folder is came from my question:
Does this depth of directories somehow related to the folder name on test generation as well?

As what I can see now on the test generation:
`avc_12.5_25_50-2021-09-09-local`
Which shows media type and frame rate on the folder name on TR, so when user select test to run on landing page it is clear that what is been selected and run.

Having aac_lc, he_aac and he_aac_v2 as a folder it just makes the test generation easier to add this information to the folder name on TR show that is shows on the configuration page and result page.

**Comment by rbouqueau** [comment]
I propose that <media_type> maps to the WAVE Media Profile or alternately to the CMAF brand. Opinions?

I agree with using <frame_rate_family> for an equivalent in audio. For Dolby that could be a codec or channel layout, thoughts?

For the audio <stream_id> we only have [this](https://github.com/cta-wave/Test-Content-Generation/blob/master/Instructions/caac.md). Would it make sense to make a table similar to https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit ?

That would bring the same depth for audio and video media types.

> caac_sets/aac_lc/at1/2021-11-01/2021-12-04

Maybe we could prefix the mezzanine date? e.g. with an 'm' or 'source'? Thoughts?

**Comment by yanj-github** [comment]
> Maybe we could prefix the mezzanine date? e.g. with an 'm' or 'source'? Thoughts?
It would be nice to have prefix di differenciate two dates. 
Q: Is there a specific reason why mezzanine date need to be a folder? Can it be on databse.json instead?
If contents has to be regenrated because of mezzanine change then I belive the content folder will have new date anyway.

**Comment by rbouqueau** [comment]
> Q: Is there a specific reason why mezzanine date need to be a folder? Can it be on databse.json instead?

Note: in Thomas' initial proposal the mezzanine_version was closer to the root. I agree it makes less sense now.

The question is: do would want/need to expose this on the folder structure?

**Comment by jpiesing** [comment]
> > Q: Is there a specific reason why mezzanine date need to be a folder? Can it be on databse.json instead?
> 
> Note: in Thomas' initial proposal the mezzanine_version was closer to the root. I agree it makes less sense now.
> 
> The question is: do would want/need to expose this on the folder structure?

If the mezzanine content is updated & the test content is regenerated then something in the directory hierarchy / filename needs to change to avoid the caching issues <upload_date> could be enough though to avoid this.

I agree that it's not essential for <mezzanine_release_version> to be included.

What do you think @nicholas-fr ?

**Comment by nicholas-fr** [comment]
As long as the mezzanine version used to generate the content is clearly documented somewhere (e.g. database.json, MPD), then I agree it doesn't have to be included as a directory level in the test content path.

**Comment by rbouqueau** [comment]
It is not at the moment. We should add the mezzanine source/version to the MPD as the database.json will be overwritten (but ok to add at both locations).

Status:
- File structure: ```<media_type>_sets/<sub_media_type (frame_rate_family|audio_codec)>/<stream_id>/<upload_date>``` e.g.
```
avc_sets/15_30_60/ss1/2021-10-22/
caac_sets/aac_lc/at1/2021-12-04
caaa_sets/he_aac_v2/at1/2021-12-04
```
- TODO: add mezzanine version/source to MPD and database.json
- TODO: document what the audio stream_ids are

Does that look right?

**Comment by jpiesing** [comment]
> Does that look right?

That looks consistent with the discussion & I can't see anything wrong with it.

@nicholas-fr ?
@yanj-github ?

**Comment by yanj-github** [comment]
> 

That looks good to me. 
audio stream_ids: 
- "at1" stands for audio track 1, but feel free to comments or suggest anything else.

**Comment by nicholas-fr** [comment]
Looks good to me.

Do we have a complete overview of the audio tests with the corresponding IDs, as we do for AVC?
I didn't see an answer to @rbouqueau 's question [earlier in the thread](https://github.com/cta-wave/dpctf-tests/issues/59#issuecomment-978079403):

> For the audio <stream_id> we only have [this](https://github.com/cta-wave/Test-Content-Generation/blob/master/Instructions/caac.md). Would it make sense to make a table similar to https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit ?

**Comment by rbouqueau** [comment]
> Do we have a complete overview of the audio tests with the corresponding IDs, as we do for AVC? I didn't see an answer to @rbouqueau 's question [earlier in the thread](https://github.com/cta-wave/dpctf-tests/issues/59#issuecomment-978079403):
> 
> > For the audio <stream_id> we only have [this](https://github.com/cta-wave/Test-Content-Generation/blob/master/Instructions/caac.md). Would it make sense to make a table similar to https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit ?

Yes it would make sense. That's what I meant by "document what the audio stream_ids are".

Status:
-   File structure: <media_type>_sets/<sub_media_type (frame_rate_family|audio_codec)>/<stream_id>/<upload_date> e.g.
```
avc_sets/15_30_60/ss1/2021-10-22/
caac_sets/aac_lc/at1/2021-12-04
caaa_sets/he_aac_v2/at1/2021-12-04
```
-  TODO: add mezzanine version/source to MPD and database.json
-  TODO: document what the audio stream_ids are
- TODO: add to annotation specification (see https://github.com/cta-wave/mezzanine/issues/31)

**Comment by yanj-github** [comment]
@rbouqueau Regarding to "document what the audio stream_ids are":
What is the value and what do we want to achieve here, which is not clear to me.
Feel free to correct me if I am wrong. 
If we would like to map audio stream_ids with its porperty such as channels and fragment duration etc isn't it enough to have this information on database.json? As soon as the database.json is updated with new audio streams, stream information cane be read from the database.json file, I don't think there is a need to duplicate this information.

**Comment by rbouqueau** [comment]
We want to achieve [this](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit) but for audio.

> isn't it enough to have this information on database.json?

database.json is an output of the system. It doesn't give enough information to regenerate the streams. Ideally database.json should be filled automatically by the test-content-generation scripts, the risk of manual errors is too high.

@yanj-github  Is it clearer?

**Comment by jpiesing** [comment]
@yanj-github The stream_ids are based on what streams need to be produced. These are 
We need to decide what content options need to be tested for each of the audio codecs. Options fall into 3 groups.
1) Options in the bitstream. I assume Dolby have a test suite that will cover all of these.
2) Options in how the bitstream is packaged in ISOBMFF/CMAF
3) Anything that doesn't easily fit into either of the above.

Additionally some tests need special streams. We need a switching set. We need some tests for splicing.

**Comment by jpiesing** [comment]
December 7th meeting
Agree to remove mezzanine version from directory heirarchy.
Is this being written up as a statement of how things are to be done. It will be done.
What about stream ids for audio? That depends on what test streams we have for each audio codec?

**Comment by rbouqueau** [comment]
Content is updated. See https://cta-wave.github.io/Test-Content/.

**Comment by gitwjr** [comment]
Closed. Reopen if needed.
