### ISSUE TITLE
Complete Configuration File

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#6]
We agreed to put all test configurations (both, test runner and observation configurations) in a single [test-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json) file. TODO:

* Fraunhofer to provide all test runner configurations in  [test-config.json] 
* Eurofins to provide all observation configurations in  [test-config.json]

**Comment by louaybassbouss** [comment]
- [ ] Add documentation page for the config parameters (description, value range, etc...)

**Comment by yanj-github** [comment]
Please find the following parameters that we think they are required for each test. Any comments are welcome. 

Tests | Parameters   Required
-- | --
8.2 Sequential Track Playback | ts_max,   tolerance, cmaf_track_duration
8.3 Random Access to Fragment | ts_max,   tolerance, random_access_time , cmaf_track_duration
8.4 Random Access to Time | ts_max,   tolerance, random_access_time , cmaf_track_duration
8.5 Switching Set Playback | ts_max,   tolerance, playout[i], fragment_duration
8.6 Regular Playback of Chunked Content | ts_max,   tolerance, cmaf_track_duration
8.7 Regular Playback of Chunked Content, non-aligned append | ts_max,   tolerance, cmaf_track_duration
8.8 Playback over WAVE Baseline Splice Constraints | ts_max,   tolerance, playout[i], fragment duration_track_1, fragment duration_track_2,   …, fragment duration_track_K
8.9 Out-Of-Order Loading | ts_max,   tolerance, cmaf_track_duration
8.10 Overlapping Fragments | ts_max,   tolerance, playout[i], fragment_duration
8.11 Full Screen Playback of Switching Sets | ts_max,   tolerance, playout[i], fragment_duration
8.12 Playback of Encrypted Content | ts_max,   tolerance, cmaf_track_duration
8.13 Restricted Splicing of Encrypted Content | ts_max,   playout[i], fragment duration_track_1, fragment duration_track_2, …, fragment   duration_track_K
8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline   Content | ts_max,   cmaf_track_duration
9.2 Regular Playback of a CMAF Presentation | cmaf_track_duration
9.3 Random Access of a WAVE Presentation | cmaf_track_duration,   random_access_time
9.4 Splicing of WAVE Program with Baseline Constraints | playout[i],   fragment duration_track_1, fragment duration_track_2, …, fragment   duration_track_K

**Comment by louaybassbouss** [comment]
Thanks @yanj-github It is possible to provide default values for these parameter?

**Comment by yanj-github** [comment]
The ts_max is 120ms from the spec, and cmaf_track_duration is 60s for the most of source contents what we have now. And random_access_time would be between 0 to 60s we can default to 30s, fragment_duration is 2000. But I am not sure what will be the suitable value for  tolerance and playout[i].

**Comment by yanj-github** [comment]
In addion to above, "8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content" we are not really clear how this supposed to work. I am not sure if 8.14 is spliced or not, it is not clear to me by reading the spec. If 8.14 is spliced then we will need parameters  playout[i], fragment duration_track_1, fragment duration_track_2, …, fragment duration_track_K instead of the  cmaf_track_duration.

**Comment by louaybassbouss** [comment]
Thanks @yanj-github  for your input. @jpiesing can you add this issue on the Agenda for tomorrows call to make final decision on the default values for each parameter.

**Comment by louaybassbouss** [comment]
@yanj-github I am not sure if we need the `cmaf_track_duration`, `fragment_duration`, `fragment_duration_track_1` , ... parameters in the config since these are provided in the content mpd. 
Regarding `playout[i]` we need to check how we can specify it in the config file since the values are dependent from the number of Segments and Representations of the actual played content (provided in the content mpd)

**Comment by jpiesing** [comment]
> @yanj-github I am not sure if we need the `cmaf_track_duration`, `fragment_duration`, `fragment_duration_track_1` , ... parameters in the config since these are provided in the content mpd.

I guess there could be an issue here about whether the test runner & the observation framework both extract these from the content MPD or whether the test runner extracts them from the content MPD and passes them to the observation framework in the configuration file? The second of these feels less error prone to me.

> Regarding `playout[i]` we need to check how we can specify it in the config file since the values are dependent from the number of Segments and Representations of the actual played content (provided in the content mpd)

According to https://github.com/cta-wave/Test-Content-Generation/issues/17 , we have 60s streams. The proposed set of tests in https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit?usp=sharing uses a 2s fragment duration for streams 1 and >=20 which means 30 segments.

In issue https://github.com/cta-wave/Test-Content-Generation/issues/16, for AVC, we decided to have a single Switching Set for all members of the same frame rate family (spreadsheet not yet adapted). For 50Hz as an example, this would mean the following 8 Tracks;
1. 920x1080p50
2. 1920x1080p25
3. 1280x720p50
4. 1024x576p25 (high bitrate)
5. 1024x576p25 (lower bitrate)
6. 768x432p25
7. 512x288p25
8. 480x270p12.5.

For 8 Tracks and 30 segments, that means most Tracks would have a segment included 4 times and a few Tracks would have a segment included only 3 times.

The device playback spec uses 'K' to represent the number of Tracks in a Switching set. I would suggest the following;

K, K-1, .... 2, 1, 2, .... K-1, K, K-1, .....

Where K is 8, this would mean playout[] would be;

8, 7, 6. 5, 4, 3, 2, 1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1, 2, 3, 4, 5, 6, 7, 8, 7

We could also make the second pass more varied with some transitions by +/-2 rather just -1 then +1.

**Comment by yanj-github** [comment]
I thought the observation framework will not have access to the contents folder, so I thought it depends on the Test Runner to pass this information to the observation framework. But if we do have access to the contents then we will be able to get it from content mpd. I agree with @jpiesing that the test runner extracts them from the content MPD and passes them to the observation framework in the configuration file is better. So that it can make sure the Test Runner and Observation framework has same information.

**Comment by louaybassbouss** [comment]
> I thought the observation framework will not have access to the contents folder, so I thought it depends on the Test Runner to pass this information to the observation framework. But if we do have access to the contents then we will be able to get it from content mpd. I agree with @jpiesing that the test runner extracts them from the content MPD and passes them to the observation framework in the configuration file is better. So that it can make sure the Test Runner and Observation framework has same information.

Yes agree we need a mechanism to pass these parameters to the observation framework. We can use the QR code that is displayed before each test for this purpose. What do you think?

**Comment by jpiesing** [comment]
> Yes agree we need a mechanism to pass these parameters to the observation framework. We can use the QR code that is displayed before each test for this purpose. What do you think?

Why not use the configuration file? What a I missing?

**Comment by yanj-github** [comment]
> 
> 
> > I thought the observation framework will not have access to the contents folder, so I thought it depends on the Test Runner to pass this information to the observation framework. But if we do have access to the contents then we will be able to get it from content mpd. I agree with @jpiesing that the test runner extracts them from the content MPD and passes them to the observation framework in the configuration file is better. So that it can make sure the Test Runner and Observation framework has same information.
> 
> Yes agree we need a mechanism to pass these parameters to the observation framework. We can use the QR code that is displayed before each test for this purpose. What do you think?

Observation Framework does not care how it passes this information, but I think this is preferable which provides mire dynamic option, so that same test with different contents can be observed correctly.

**Comment by jpiesing** [comment]
> Observation Framework does not care how it passes this information, but I think this is preferable which provides more dynamic option, so that same test with different contents can be observed correctly.

"same test with different contents" is prohibited / a meaningless concept.
"same code with different contents" is a different test.

**Comment by yanj-github** [comment]
> 
> 
> > Observation Framework does not care how it passes this information, but I think this is preferable which provides more dynamic option, so that same test with different contents can be observed correctly.
> 
> "same test with different contents" is prohibited / a meaningless concept.
> "same code with different contents" is a different test.

Thanks @jpiesing to clarify. I meant same code with different contents.  e.g.  "sequential-track-playback" for contents with different duration then cmaf_track_duration parameter is different.

**Comment by louaybassbouss** [comment]
> > Observation Framework does not care how it passes this information, but I think this is preferable which provides more dynamic option, so that same test with different contents can be observed correctly.
> 
> "same test with different contents" is prohibited / a meaningless concept.
> "same code with different contents" is a different test.



> > > Observation Framework does not care how it passes this information, but I think this is preferable which provides more dynamic option, so that same test with different contents can be observed correctly.
> > 
> > 
> > "same test with different contents" is prohibited / a meaningless concept.
> > "same code with different contents" is a different test.
> 
> Thanks @jpiesing to clarify. I meant same code with different contents. e.g. "sequential-track-playback" for contents with different duration then cmaf_track_duration parameter is different.

yes we have currently a single configuration file for all test templates. We should avoid defining dynamic parameters/configurations at different places/files.

**Comment by jpiesing** [comment]
> yes we have currently a single configuration file for all test templates. We should avoid defining dynamic parameters/configurations at different places/files.

@Louay I'm confused.

Some configuration options may have the same value for all test cases. 
Some configuration options may have the same value for all test cases for the same media profile (e.g. all AVC test cases). 
Some configuration options may have different values for different test cases even within the same media profile.

**Comment by louaybassbouss** [comment]
> > yes we have currently a single configuration file for all test templates. We should avoid defining dynamic parameters/configurations at different places/files.
> 
> @louay I'm confused.
> 
> Some configuration options may have the same value for all test cases.
> Some configuration options may have the same value for all test cases for the same media profile (e.g. all AVC test cases).
> Some configuration options may have different values for different test cases even within the same media profile.

@jpiesing the semantic of the JSON config file we discussed last year considers only test templates independent from content. Let's check tomorrow which config parameters are required on content level and are not provided in the content mpd. If required, we need to think about another solution to provide the config for the auto-generated tests.

**Comment by jpiesing** [comment]
> @jpiesing the semantic of the JSON config file we discussed last year considers only test templates independent from content. Let's check tomorrow which config parameters are required on content level and are not provided in the content mpd. If required, we need to think about another solution to provide the config for the auto-generated tests.

One simple solution might be to have the test name / identifier of the test (& not just the name of the code) as part of the name / key in the test-config file. e.g.

  "sequential-track-playback": {
    "min_buffer_duration": 40000,
    "ts_max": 100
  },
  "avc-track-001:sequential-track-playback": {
    "cmaf_track_duration": 1800
  },
  "avc-track-002:sequential-track-playback": {
    "cmaf_track_duration": 1800
  },

**Comment by FritzHeiden** [comment]
Implementation of this feature is done. Configuration parameters from test-config.json are loaded and used when executing a test. I still have to write a documentation on the usage of the test-config.json

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden documentation page is now available --> [TEST_CONFIG.md](https://github.com/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md)

**Comment by yanj-github** [comment]
Thanks @louaybassbouss Can I have the URL link to access this configuration from the Test Runner server please?

**Comment by louaybassbouss** [comment]
> Thanks @louaybassbouss Can I have the URL link to access this configuration from the Test Runner server please?

You can access the configuration via http://web-platform.test:8000/test-config.json  (change domain/port if you don't use the default values)

**Comment by louaybassbouss** [comment]
@jpiesing if all agree (especially @yanj-github), we can close this issue during out meeting tomorrow.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss  and @FritzHeiden I can access the configuration files however I cannot see the content related parameters such as "cmaf_track_duration".  Can you help how I can find this information please?

**Comment by jpiesing** [comment]
> Thanks @louaybassbouss and @FritzHeiden I can access the configuration files however I cannot see the content related parameters such as "cmaf_track_duration". Can you help how I can find this information please?

This depends on the test content & may also be different for the same content in different tests.

**Comment by yanj-github** [comment]
Thanks @jpiesing yes that is what I think it is. Are you saying observation framework need to access the mpd file and get the information such as duration of cmaf track etc please? I think the following is what we have agreed before. 

> Do we need to extract the numbers of Tracks & duration from the MPD when the test is run?
> **No - can just hard-code it in the configuration file.**

**Comment by jpiesing** [comment]
> Thanks @jpiesing yes that is what I think it is. Are you saying observation framework need to access the mpd file and get the information such as duration of cmaf track etc please? I think the following is what we have agreed before.
> 
> > Do we need to extract the numbers of Tracks & duration from the MPD when the test is run?
> > **No - can just hard-code it in the configuration file.**

It sounds like we need a script somewhere that generates the cmaf_track_duration and to run it for every stream.

**Comment by yanj-github** [comment]
I have checked the confifuration file https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json, and the following information is missing:

- random_access_time for any random access tests
- cmaf_track_duration (content specific parameter to be discussed)
- fragment_duration (content specific parameter to be discussed)
- playout[i], fragment duration_track_1, fragment duration_track_2, …, fragment duration_track_K for any splicing tests
- tolerance is not defined in the spec this is set to 10. Are we all happy about the value please?

**Comment by jpiesing** [comment]
> Thanks @jpiesing yes that is what I think it is. Are you saying observation framework need to access the mpd file and get the information such as duration of cmaf track etc please? I think the following is what we have agreed before.
> 
> > Do we need to extract the numbers of Tracks & duration from the MPD when the test is run?
> > **No - can just hard-code it in the configuration file.**

@yanj-github How many other examples are there as well as cmaf_track_duration?

**Comment by jpiesing** [comment]
> I have checked the confifuration file https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json, and the following information is missing:
> 
>     * random_access_time for any random access tests
> 

This is not really content related. Any value can be picked that is not the start of a CMAF segment. When the CMAF segments are 2s duration then any value which is an not an even number can be picked. When the CMAF segments are 5s duration then any value that is not a multiple of 5 can be picked. For example, 11s might be a reasonable value that should work on all streams.

>     * cmaf_track_duration (content specific parameter to be discussed)
> 

Indeed this needs discussion. Someone needs to write a script but who and when is it run?

>     * fragment_duration (content specific parameter to be discussed)
> 
>     * playout[i], fragment duration_track_1, fragment duration_track_2, …, fragment duration_track_K for any splicing tests
>  

I think Fraunhofer can just decide playout[i].

>     * tolerance is not defined in the spec this is set to 10. Are we all happy about the value please?

Is this 10ms? I suspect 100ms is more credible.

**Comment by yanj-github** [comment]
Thanks @jpiesing just wanted to add that 
 random_access_time for any random access tests, Whether the Test Runner randomly define on the test run or hardcodeded to make it always same, the observation framework need to know this value to check the playback is started from correct frame. I guess hardcodeded to make it always same would be eaiser to achive.

**Comment by louaybassbouss** [comment]
PS. The list of parameters that are use by the test runner are listed in [TEST-CONFIG.md](https://github.com/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md). It is possible to override the [test-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json) file in dpctf-deploy project in [docker-compose.yml#L14](https://github.com/cta-wave/dpctf-deploy/blob/master/docker-compose.yml#L14)

**Comment by louaybassbouss** [comment]
@yanj-github can you summarise the parameters you need in the observation framework that are part of the MPD manifest of individual test content.

**Comment by jpiesing** [comment]
> @yanj-github can you summarise the parameters you need in the observation framework that are part of the MPD manifest of individual test content.

I think it's they're in this comment ...

https://github.com/cta-wave/dpctf-tests/issues/6#issuecomment-771553108

**Comment by louaybassbouss** [comment]
Based on latest discussion, this is one proposal:

- `random_access_time`: use 11s as default global value in test-config.json (in `all`). Other values can be defined on test level if needed. 
- `cmaf_track_duration`: the test running in the browser on the DUT can provide this value via a QR code after parsing the MPD (JavaScript Code for the Browser). We can use the field `td` in the JSON data embedded in the QR code.
- `fragment_duration`: similar to `cmaf_track_duration`. We can use the field `fd` in the JSON data embedded in the QR code. 
- `fragment_duration` for each track: We can reuse the `fd` field and provide an array instead of a single value. 
- `playout[i]`:  can be provided in the test-config.json
- `tolerance`: can be provided in the test-config.json as a global parameter with a default value of 100ms. 

In total, 2 new parameters `td` and `fd` will be added to the QR code. 

@jpiesing @yanj-github  wdyt?

**Comment by yanj-github** [comment]
@louaybassbouss  Thanks for this, and may I ask which QR codes do these parameters are going to be added the pre-test QR code or the test runner status QR code please?

**Comment by jpiesing** [comment]
I remain uncomfortable with the approach of adding these to the QR code.
I would prefer they were added to the configuration file.
Most likely this would mean the script that parses the .CSV file would need to generate these for each test.

**Comment by jpiesing** [comment]
> @louaybassbouss Thanks for this, and may I ask which QR codes do these parameters are going to be added the pre-test QR code or the test runner status QR code please?

Given the concerns about QR code detection on smaller displays, I would prefer them to be added to the pre-test QR code as that can be made larger / more robust.

**Comment by louaybassbouss** [comment]
> @louaybassbouss Thanks for this, and may I ask which QR codes do these parameters are going to be added the pre-test QR code or the test runner status QR code please?

It is not implemented yet but I think pre-test QR Code is better.

**Comment by louaybassbouss** [comment]
> I remain uncomfortable with the approach of adding these to the QR code.
> I would prefer they were added to the configuration file.
> Most likely this would mean the script that parses the .CSV file would need to generate these for each test.

@jpiesing  for me these parameters are not configuration parameters. Configuration parameters may have a default value and can be changed if needed. This is not the case for `cmaf_track_duration` and `fragment_duration` since they are not target to be changed. We should avoid duplicating parameters in different files. If the approach passing these parameters via the QR code is not feasible, it is still possible that the observation Framework reads these values from the source MDP file (The location of the MPD is provided in the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json).

**Comment by jpiesing** [comment]
> @jpiesing for me these parameters are not configuration parameters. Configuration parameters may have a default value and can be changed if needed. This is not the case for `cmaf_track_duration` and `fragment_duration` since they are not target to be changed. We should avoid duplicating parameters in different files. If the approach passing these parameters via the QR code is not feasible, it is still possible that the observation Framework reads these values from the source MDP file (The location of the MPD is provided in the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json).

To me these are part of configuring the test code to run with a particular media file so making the MPD parsing part of the script that reads the .csv file and generates the individual tests seems logical.

**Comment by louaybassbouss** [comment]
> > @jpiesing for me these parameters are not configuration parameters. Configuration parameters may have a default value and can be changed if needed. This is not the case for `cmaf_track_duration` and `fragment_duration` since they are not target to be changed. We should avoid duplicating parameters in different files. If the approach passing these parameters via the QR code is not feasible, it is still possible that the observation Framework reads these values from the source MDP file (The location of the MPD is provided in the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json).
> 
> To me these are part of configuring the test code to run with a particular media file so making the MPD parsing part of the script that reads the .csv file and generates the individual tests seems logical.

@jpiesing let's imagine these parameters are part of the configuration file and someone changes them then we will have inconsistencies between the configuration file and MPD. We are now trying to solve how the test Runner can pass information to the Observation Framework using the configuration file but there are other ways to do it.

**Comment by jpiesing** [comment]
> @jpiesing let's imagine these parameters are part of the configuration file and someone changes them then we will have inconsistencies between the configuration file and MPD. We are now trying to solve how the test Runner can pass information to the Observation Framework using the configuration file but there are other ways to do it.

The configuration file is already a mixture of things that someone can change and things that they should not change.

**Comment by yanj-github** [comment]
@louaybassbouss  and @FritzHeiden  I can see the random access fragmement and time parameters were included in the code but still missing from the configuration file. I can add them manully for now but it would be appreaciated if you can add them to the test-config.json as well please? 
This comes to a question that what if parameters are missing from the configuration file? Does test runner work with default value?

**Comment by louaybassbouss** [comment]
> @louaybassbouss and @FritzHeiden I can see the random access fragmement and time parameters were included in the code but still missing from the configuration file. I can add them manully for now but it would be appreaciated if you can add them to the test-config.json as well please?
> This comes to a question that what if parameters are missing from the configuration file? Does test runner work with default value?

@yanj-github feel free to share the additional parameters and values you need and we can add them. You can attach your local test-config.json in this issue if it is easier for you.

**Comment by yanj-github** [comment]
> 
> 
> > @louaybassbouss and @FritzHeiden I can see the random access fragmement and time parameters were included in the code but still missing from the configuration file. I can add them manully for now but it would be appreaciated if you can add them to the test-config.json as well please?
> > This comes to a question that what if parameters are missing from the configuration file? Does test runner work with default value?
> 
> @yanj-github feel free to share the additional parameters and values you need and we can add them. You can attach your local test-config.json in this issue if it is easier for you.
I would like to see the following in test-config.json file:

- for the test 8.3 Random Access to Fragment 

random_access_fragment=<random_access_fragment_number 0-last_frame_number__of_contnet>

- for the test 8.4 Random Access to Time

random_access_time=<random_access_fragment_time ranged between 0-cmaf_duration>

**Comment by louaybassbouss** [comment]
@jpiesing back to the discussion about how to provide static/dynamic configuration. We are going to implement your approach by providing the parameters in the configuration files. This is our proposal please confirm if you are happy with it:

- The test generator script reads static parameters form the MPD (e.g. `cmaf_track_duration`, `fragment_duration`, etc.) and put them in the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json). We can also read in the same script other parameters e.g. those related to clearkey encryption. The [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) is already accessible via REST API and can be used in any external component f.e. the Observation Framework.
- All other (dynamic) configuration will be kept in the [tests-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/tests-config.json) and the generator script will not touch them. [tests-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/tests-config.json) is available through a REST API as well. 

wdyt?

**Comment by FritzHeiden** [comment]
Implementation to include the `cmaf_track_duration` and `fragment_duration` in the `tests.json` when generating tests is now done. There is one new parameter to consider when using the `generate-tests.py` script. I updated the `README.md` accordingly.

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden 👍  @yanj-github  please check and let us know if you have questions

**Comment by yanj-github** [comment]
Does random_acccess_time in seconds or ms please and it is float or int? Thanks @FritzHeiden

**Comment by jpiesing** [comment]
> @jpiesing back to the discussion about how to provide static/dynamic configuration. We are going to implement your approach by providing the parameters in the configuration files. This is our proposal please confirm if you are happy with it:
> 
>     * The test generator script reads static parameters form the MPD (e.g. `cmaf_track_duration`, `fragment_duration`, etc.) and put them in the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json). We can also read in the same script other parameters e.g. those related to clearkey encryption. The [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) is already accessible via REST API and can be used in any external component f.e. the Observation Framework.
> 
>     * All other (dynamic) configuration will be kept in the [tests-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/tests-config.json) and the generator script will not touch them. [tests-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/tests-config.json) is available through a REST API as well.
> 
> 
> wdyt?

It's an improvement.

**Comment by louaybassbouss** [comment]
> Does random_acccess_time in seconds or ms please and it is float or int? Thanks @FritzHeiden

@yanj-github it is in the same format as in the MPD. You can check the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) which already includes these parameters.

**Comment by yanj-github** [comment]
> 
> 
> > Does random_acccess_time in seconds or ms please and it is float or int? Thanks @FritzHeiden
> 
> @yanj-github it is in the same format as in the MPD. You can check the [generated/tests.json](https://github.com/cta-wave/dpctf-tests/blob/master/generated/tests.json) which already includes these parameters.

Sorry @louaybassbouss  that I didnt make is clear the  generated/tests.json  looks good to me. 
I was asking the 
"random-access-to-time-manual.html": {
    "ts_max": 120,
    "tolerance": 10,
    **"random_access_time": 10**
  },
from https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json

**Comment by FritzHeiden** [comment]
@yanj-github `random_access_time` is a float in seconds.

**Comment by yanj-github** [comment]
I am happy to close this issue. Thanks
