### ISSUE TITLE
Are bigger satrt-up delay tolerances allowed for random access to time test and splicing test? If so, what is the suitable value for it?

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#63]
Maximum permitted start-up delay is 120ms.
Which is configured in test-config.json file

Bigger value might be required for different test?
Random access to time seems always failing. Probably it required some additional time to decode at the beginning. I think on this test we might want to have bigger tolerance. 
Splicing test start up delay check is failed as well. I don't think there might be any reason for this.

I have done only a few limited tests on a single device. It might work differently on different devices. More comments and further discussions will be helpful.

**Comment by yanj-github** [comment]
It appeares that random access fragment test is failing on start up delay observation as well. 
I am not sure whether this is a device issue or not. If anyone else can help to run a test and check on different device will be helpful.

**Comment by gitwjr** [comment]
@yanj-github @jpiesing Not sure if this is pertinent or not. I ran this test on 11/30/21 using the TR and OF files downloaded that day. It was on a Lenovo Laptop, Windows 10, running Chrome, using a 23" monitor with a Hero 4 camera. The camera seems to work fine with the large monitor as I have had other tests with full pass. 
Test Files
/avc_15_30_60-2021-09-09-local/random-access-of-a-wave-presentation__t1.html
/avc_15_30_60-2021-09-09-local/random-access-to-fragment__t1.html


[Consolidated results file.txt](https://github.com/cta-wave/dpctf-tests/files/7739527/Consolidated.results.file.txt)

**Comment by yanj-github** [comment]
Thanks @gitwjr for the information. 
Is it fine to conclude that this is a device specific issue in this case?
I will close this issue in this case. Any comments please?
