### ISSUE TITLE
unexpected pre-test QR code present after the playback ended

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#65]
There is an unexpected pre-test QR code present after the playback ended. 
This was presented after the last test in a session is ended, just before TR shows session complete page. 
![image](https://user-images.githubusercontent.com/59022223/139700305-ec984ce6-08dd-4fe4-8093-32b9e02f4ed4.png)

**Comment by FritzHeiden** [comment]
Unfortunately I was unable to reproduce your problem. Can you give more information when it occurs? Does it occur with any number of tests in a test session? Or does it only occur with specific tests or a whole directory? I tried running single tests, some tests and all tests of a test directory.

**Comment by louaybassbouss** [comment]
> > Unfortunately I was unable to reproduce your problem. Can you give more information when it occurs? Does it occur with any number of tests in a test session? Or does it only occur with specific tests or a whole directory? I tried running single tests, some tests and all tests of a test directory.
> 
> Indeed this is come and go. I saw it when I run encryped test only one test in a session. The screen shot above shows which test in which folder can you try again please? It only appears couple of frame might be be human obseravble to just run test and see, you can try record with camera and scroll near to the end and go frame by frame.

@yanj-github can you clear the cache in your browser and try again. We cannot reproduce the error on our side.

**Comment by yanj-github** [comment]
I had a complete reinstall and having this problem still. 
Is seems like only happens on this test to me:
/avc_15_30_60-2021-09-09-local/playback-of-encrypted-content-https__t1-cenc.html

**Comment by yanj-github** [comment]
I cannot replicate this problem.

What I did it reinstall TR completed by removing everything and clear the borwser as well.
One or both might have resolved issue. Closing it now.
