### ISSUE TITLE
eac3 and ac4 local tests are not avalible

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#66]
eac3 and ac4 local tests are not avalible only online tests are avalible.

**Comment by yanj-github** [comment]
@louaybassbouss It is now merged.

**Comment by FritzHeiden** [comment]
The zip files referenced in the database.json have an incorrect file structure. From your pull request in `dpctf-tests` I can see that you refer to the local content as follows:
```
/content/eac3_sets/at1/stream.mpd
/content/ac4_sets/at1/stream.mpd
```
However, inside the zip files there is no `eac3_sets` or `ac4_sets` directory. As the download script extracts the contents from the zip as is, this results in the following structure in the contents directory:

```
/content/at1/stream.mpd
```

This causes the test generation to fail.

**Comment by louaybassbouss** [comment]
> The zip files referenced in the database.json have an incorrect file structure. From your pull request in `dpctf-tests` I can see that you refer to the local content as follows:
> 
> ```
> /content/eac3_sets/at1/stream.mpd
> /content/ac4_sets/at1/stream.mpd
> ```
> 
> However, inside the zip files there is no `eac3_sets` or `ac4_sets` directory. As the download script extracts the contents from the zip as is, this results in the following structure in the contents directory:
> 
> ```
> /content/at1/stream.mpd
> ```
> 
> This causes the test generation to fail.

@yanj-github can you update the zip files to follow the structure  described by @FritzHeiden

**Comment by yanj-github** [comment]
Thanks @louaybassbouss and @FritzHeiden I have emailed you a zip file to check. If you can confirm it is correct I will apply to others and get it uploaded.

**Comment by FritzHeiden** [comment]
@yanj-github The zip looks good to me

**Comment by louaybassbouss** [comment]
@yanj-github please ping us when the zip files are available on the server

**Comment by abdulwahabEDT** [comment]
@louaybassbouss and @FritzHeiden new zip files are now available and databse.json is updated. please help generate tests.

**Comment by FritzHeiden** [comment]
@abdulwahabEDT  @yanj-github  Local ac3 and eac3 tests are now included in the generated tests directory
