### ISSUE TITLE
Can you add two new shared configuration parameters

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#67]
Dirven by discussion on
https://github.com/cta-wave/device-observation-framework/issues/32

Can you help to add the following paramters to test-config.json please?

- duration_tolerance 
default value is 20, unit milliseconds

- duration_frame_tolerance: 
default us 0, unit: number

e.g:
```
  "sequential-track-playback.html": {
    "min_buffer_duration": 40000,
    "ts_max": 120,
    "tolerance": 20,
    "frame_tolerance": 2
    "duration_tolerance": 20,
    "duration_frame_tolerance": 0
  },
```

**Comment by louaybassbouss** [comment]
> Dirven by discussion on [cta-wave/device-observation-framework#32](https://github.com/cta-wave/device-observation-framework/issues/32)
> 
> Can you help to add the following paramters to test-config.json please?
> 
> * duration_tolerance
>   default value is 20, unit milliseconds
> * duration_frame_tolerance:
>   default us 0, unit: number
> 
> e.g:
> 
> ```
>   "sequential-track-playback.html": {
>     "min_buffer_duration": 40000,
>     "ts_max": 120,
>     "tolerance": 20,
>     "frame_tolerance": 2
>     "duration_tolerance": 20,
>     "duration_frame_tolerance": 0
>   },
> ```

@yanj-github can we add the default parameters in "all" ?

**Comment by yanj-github** [comment]
Hi @louaybassbouss we dont care on OF level however as far as I know at the moment default value is same but it might required to change for different test differently for the future. I think it would be better to have individul entry per test. 
@jpiesing what is your opinion please? Are you fine to have duration tolerances apply to all tests or each entry per test please?

**Comment by louaybassbouss** [comment]
> Hi @louaybassbouss we dont care on OF level however as far as I know at the moment default value is same but it might required to change for different test differently for the future. I think it would be better to have individul entry per test. @jpiesing what is your opinion please? Are you fine to have duration tolerances apply to all tests or each entry per test please?

@yanj-github  yes it is possible to override the values for specific tests. This is the semantic behind the structure of tests-config.json.

**Comment by louaybassbouss** [comment]
@yanj-github the two new parameters are now added to [tests-config.json](https://github.com/cta-wave/dpctf-tests/blob/master/test-config.json#L7-L8)

**Comment by yanj-github** [comment]
Yep this is fine in the case. Thanks @louaybassbouss

**Comment by jpiesing** [comment]
> @jpiesing what is your opinion please? Are you fine to have duration tolerances apply to all tests or each entry per test please?

I prefer to have duration tolerances be configurable per test but that seems to be the case anyway as @louaybassbouss explained.
