### ISSUE TITLE
test configuration playout paramter out of date

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#68]
I can see the tests are 2021-09-09 but the configuration parameters still point back to 2021-07-07.
The playout is missing for new tests 2021-09-09.
e.g: avc_15_30_60-2021-09-09-local/fullscreen-playback-of-switching-sets__ss1.html which is mentioned here https://github.com/cta-wave/device-observation-framework/issues/34#issuecomment-965714491
Can you help to fix it please?

**Comment by louaybassbouss** [comment]
> I can see the tests are 2021-09-09 but the configuration parameters still point back to 2021-07-07. The playout is missing for new tests 2021-09-09. e.g: avc_15_30_60-2021-09-09-local/fullscreen-playback-of-switching-sets__ss1.html which is mentioned here [cta-wave/device-observation-framework#34 (comment)](https://github.com/cta-wave/device-observation-framework/issues/34#issuecomment-965714491) Can you help to fix it please?

@yanj-github we will fix this ASAP.

**Comment by FritzHeiden** [comment]
test-config now updated to 2021-09-09 tests

**Comment by louaybassbouss** [comment]
@yanj-github  please check and close this issue if the fix works for you
