### ISSUE TITLE
tests.json needs documentation

### ISSUE THREAD

**Issue by michael-forsyth** [cta-wave/dpctf-tests#69]
Information about the tests is communicated between the test runner and observation framework using the two files:

- tests.json
- test-config.json

The structure and contents of test-config.json is already docuemented at https://github.com/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md
But there doesn't appear to be any documentation present for tests.json. Can documentation please be made available.

**Comment by jpiesing** [comment]
It would be good to get this in the next version of the Device Playback specification.

**Comment by louaybassbouss** [comment]
@michael-forsyth  a documentation of generated/tests.json is now available in [TEST_CONFIG.md](/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md#generatedtestsjson). Feedback is welcome.

**Comment by louaybassbouss** [comment]
@michael-forsyth  @jpiesing are you fine with the documentation. if yes, feel free to close this issue.

**Comment by jpiesing** [comment]
Fine by me. Over to you @michael-forsyth  ...

**Comment by michael-forsyth** [comment]
looks fine to me too
