### ISSUE TITLE
Provide initial CSV file and generate tests

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#7]
This [sample.csv](https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv) contains an example (dummy data) input CSV file for generation. Now is time to provide a CSV file with real data to generate tests and check the end-to-end workflow. @jpiesing do you think this is something that you can provide (of course with our support).

**Comment by jpiesing** [comment]
Hopefully we could generate a .csv file from this https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit?usp=sharing

We don't yet have the test streams though - at least not all of them.
Also some of them may be generated from the wrong mezzanine.

**Comment by louaybassbouss** [comment]
Thanks @jpiesing. As first step we can consider one media profile (for which the media content is available/will be available soon).

**Comment by jpiesing** [comment]
> Thanks @jpiesing. As first step we can consider one media profile (for which the media content is available/will be available soon).

Test content exists for AVC but probably needs some re-working. Some of that re-working may need new mezzanine content.

**Comment by jpiesing** [comment]
@louaybassbouss Does this https://github.com/cta-wave/Test-Content-Generation/issues/20#issuecomment-745470020 give you enough to make a real sample CSV file yourselves or is there something left for @nicholas-fr and myself still to do?

**Comment by louaybassbouss** [comment]
> @louaybassbouss Does this [cta-wave/Test-Content-Generation#20 (comment)](https://github.com/cta-wave/Test-Content-Generation/issues/20#issuecomment-745470020) give you enough to make a real sample CSV file yourselves or is there something left for @nicholas-fr and myself still to do?

Thanks @jpiesing  yes I will provide a first version of the CSV file based on the information in the comment. I will let you know if I have questions.

**Comment by louaybassbouss** [comment]
@jpiesing  we have now new [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv)  which consider [this Excel table](url). Can you please have a look on it before we generate the tests. This new tests.csv will replace the old sample.csv.  Important note: you see in tests.csv there are 2 folders `avc_15_30_60-local` and `avc_15_30_60-online`. These folders includes the same tests with only one difference that tests  in`avc_15_30_60-local` use local downloaded content (this is why we have relative MPD URL and not absolute MPD URL) while `avc_15_30_60-online` includes tests that use media stream directly from CDN (this is why all URLs are absolute). we may decide at a later point to remove the online tests for now it is better to keep them for testing purposes. 

to download content locally, please follow the instructions in [dpctf-deploy](https://github.com/cta-wave/dpctf-deploy#running-the-created-image-in-a-container)

**Comment by jpiesing** [comment]
@louaybassbouss Here are a  few comments to consider.

I think switching set playback is confused. The description says "Test to be run once with a single Switching Set containing the tracks labelled with X..". This is the MPD at https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1/stream.mpd . All the existing rows including "switching set playback" and "Full Screen Playback of Switching Sets" should be removed.

How significant is the order in the test.csv file? If this is the order that someone running the tests will see when configuring a session then we should seriously consider ordering by test rather than ordering by stream. 

Streams t10 to t17 inclusive are missing. They are optional to run but it needs to be possible to run them. t16 and t17 are chunked content so go with test "8.6 Regular Playback of Chunked Content" & the others go with "8.2 Sequential Track Playback".

**Comment by louaybassbouss** [comment]
> @louaybassbouss Here are a few comments to consider.
> 
> I think switching set playback is confused. The description says "Test to be run once with a single Switching Set containing the tracks labelled with X..". This is the MPD at https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1/stream.mpd . All the existing rows including "switching set playback" and "Full Screen Playback of Switching Sets" should be removed.
> 

agree

> How significant is the order in the test.csv file? If this is the order that someone running the tests will see when configuring a session then we should seriously consider ordering by test rather than ordering by stream.

The order in the CSV has no impact on the order of running the tests @FritzHeiden  can you confirm?

> 
> Streams t10 to t17 inclusive are missing. They are optional to run but it needs to be possible to run them. t16 and t17 are chunked content so go with test "8.6 Regular Playback of Chunked Content" & the others go with "8.2 Sequential Track Playback".

Will check this

**Comment by jpiesing** [comment]
> > Streams t10 to t17 inclusive are missing. They are optional to run but it needs to be possible to run them. t16 and t17 are chunked content so go with test "8.6 Regular Playback of Chunked Content" & the others go with "8.2 Sequential Track Playback".
> 
> Will check this

t2 and t3 differ from t1 by more than one content option so if an implementation won't play either t2 or t3 then the implementer doesn't know which content option caused the problem. t10 to t17 each differ from t1 by only one content option so they can be used to precisely identify the problem.

**Comment by FritzHeiden** [comment]
I added the optional test-content combinations to the tests.csv file

**Comment by louaybassbouss** [comment]
@jpiesing  PTAL

**Comment by jpiesing** [comment]
> I think switching set playback is confused. The description says "Test to be run once with a single Switching Set containing the tracks labelled with X..". This is the MPD at https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1/stream.mpd . All the existing rows including "switching set playback" and "Full Screen Playback of Switching Sets" should be removed.
> 

Confirmed OK.

> How significant is the order in the test.csv file? If this is the order that someone running the tests will see when configuring a session then we should seriously consider ordering by test rather than ordering by stream.
> 

Do we need a new issue for the ordering of the tests in the landing page?

> Streams t10 to t17 inclusive are missing. They are optional to run but it needs to be possible to run them. t16 and t17 are chunked content so go with test "8.6 Regular Playback of Chunked Content" & the others go with "8.2 Sequential Track Playback".

Confirmed OK.

**Comment by louaybassbouss** [comment]
> > How significant is the order in the test.csv file? If this is the order that someone running the tests will see when configuring a session then we should seriously consider ordering by test rather than ordering by stream.
> 
> Do we need a new issue for the ordering of the tests in the landing page?

@jpiesing  yes please create a new issue in the dpctf-test-runner project with more details about the ordering of the tests in the landing/companion page.

**Comment by jpiesing** [comment]
OK - https://github.com/cta-wave/dpctf-test-runner/issues/11.
With that as a separate issue, this issue can be closed.
