### ISSUE TITLE
fragment duration for eac-3 and ac-4 audio

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#70]
fragment duration for audio is not defined on tests.json file

`"fragment_duration": null`
For eac-3 and ac-4 content.

**Comment by louaybassbouss** [comment]
@yanj-github  we will investigate the issue

**Comment by FritzHeiden** [comment]
@yanj-github `fragment_duration` is now calculated correctly and available in the tests.json file
