### ISSUE TITLE
Title element is empty

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#72]
Passing avc_12.5_25_50-2021-09-09-online/regular-playback-of-a-cmaf-presentation__t1.html through the online HTML validator (https://validator.w3.org/) gives an error:

Error: Element title must not be empty.
From line 5, column 12; to line 5, column 19
   <title></title>

**Comment by FritzHeiden** [comment]
Fixed all errors and warning outputted from the validator for all template files and regenerated tests

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden  I will close this issue
