### ISSUE TITLE
Add documentation for running tests for debug purposes without deploying the entire test runner

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#74]
[gh-pages](https://github.com/cta-wave/dpctf-tests/tree/github-pages) branch hosts a version of DPCTF tests that can executed without the need to setup a test runner. This is helpful for debugging and testing. We need to add documentation to the README how to use this feature.

**Comment by louaybassbouss** [comment]
@jpiesing I added as discussed in the last meeting a documentation for running single tests from the gh-pages branch for debug purposes: https://github.com/cta-wave/dpctf-tests/blob/master/README.md#run-tests . Feel free to close this issue if you are happy with the documentation.

**Comment by jpiesing** [comment]
Looks OK.
