### ISSUE TITLE
Extend documentation for new tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#75]
Could you help to extend current documentation from 
https://github.com/cta-wave/dpctf-tests#readme: **Templates**
https://github.com/cta-wave/dpctf-tests/blob/master/TEST_CONFIG.md: **Test Parameters**
to add test code and new parameters for the new tests (8.15 to 8.24) please?

This will help to unblock us so that we can start working on the observations for the new tests.

**Comment by yanj-github** [comment]
**Test codes:**
source-buffer-reinitialization-without-change-type.html
source-buffer-reinitialization-with-change-type.html
buffer-underrun-and-recovery.html
truncated-playback-and-restart.html
long-duration-playback.html
low-latency-initialization.html
low-latency-playback-over-gaps.html
mse-append-window.html
low-latency-short-buffer-playback.html
random-access-from-one-place-to-a-different-place.html

**Comment by FritzHeiden** [comment]
I updated the readme's test list as well as the parameter documentation on the dpcat branch. Please note that the template files as well as the parameters may be changed, added or deleted, as the specification is still unfinished.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden that is fine as the spec is under development there will be some changes.

**Comment by louaybassbouss** [comment]
@yanj-github  can we close this issue for now
