### ISSUE TITLE
include hbbtv.js script from WMAS test suite into DPCTF tests

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#77]
we need to  include the hbbtv.js lib from the WMAS test suite  (which checks the UA and do proper HbbTV initialisation if the test runs on HbbTV).

**Comment by FritzHeiden** [comment]
hbbtv.js lib is now included in the index.html file

**Comment by louaybassbouss** [comment]
thanks @FritzHeiden

**Comment by jpiesing** [comment]
@FritzHeiden @louaybassbouss Will you consider re-generating the actual HTML+JS tests?

**Comment by louaybassbouss** [comment]
@jpiesing yes we will do it today together with missing tests from #76
