### ISSUE TITLE
Issue to use “ended” status to determine the end of test

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#78]
As it has been agreed previously OF detects “ended” status to determine the end of test and make observations. 
However, it will be a problem for the new added test 8.18 Truncated Playback and Restart
As this test will be presenting two presentation one after the other, “ended” status only tells the 1st presentation is ended but test is still carries on. Is it possible to have another status "finished" or similar to allow OF to be able to detect the end of test please?

**Comment by louaybassbouss** [comment]
> > @yanj-github yes it makes sense. After the last ended event we will trigger a finished event correct?
> 
> Thanks. Yes that is exactly what I would do. Can you kinldy confirm it would be "{"s":"finished","a":"play","ct"xxx:,"d":xxx}" and finished is stating current test finish not test session finish? And this will apply to all the tests.

@yanj-github yes I confirm :)

**Comment by FritzHeiden** [comment]
There already is an event that communicates when a test finished, so I just update the QR code when the test is done.
