### ISSUE TITLE
stable target for other SDOs to reference

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-tests#79]
We should consider making it cleaner for other SDOs to reference the WAVE device test suite, specifically having some kind of stable branch where changes happen in a more controlled manner.

As an example, the [HbbTV DASH-DRM reference app](https://github.com/HbbTV-Association/ReferenceApplication) has 3 standard [branches](https://github.com/HbbTV-Association/ReferenceApplication#versions), production, staging and testing.

Some kind of formality would give users of the test suite confidence that a stable branch would not change underneath them.

**Comment by jpiesing** [comment]
@pshorrock I've put this issue in the dpctf-tests repo but it probably applies to the OF and perhaps other repos as well.

**Comment by cta-source** [comment]
The DPCTF launch plan ad hoc has settled on a similar concept to HbbTV, that of dev/testing, staging and production. We're documenting this in our ad hoc summary PPT for now. The "stable target" goal of this issue will be met by a public repo that uses the github Releases feature. For an example, please see how the Releases are used in the OF: [Link to OF releases on github](https://github.com/cta-wave/device-observation-framework/releases). 

As this launch plan has a solid intent to have such a "stable target" as requested by this issue, and a plan for doing it, I am closing this issue.
