### ISSUE TITLE
Implement endpoint to submit test results

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#8]
We agreed to provide a REST API (`POST /api/results/<session_token>/json`) that can be used by the observation script to submit test results to the Test Runner. @FritzHeiden is this endpoint now available? if not, the next step is to implement it.

**Comment by FritzHeiden** [comment]
The feature is now implemented and available [here](https://github.com/cta-wave/dpctf-test-runner/tree/feature-results-upload)

Documentation was also added [here](https://github.com/cta-wave/dpctf-test-runner/blob/feature-results-upload/tools/wave/docs/rest-api/results-api/import.md#2-import-api-results)

It will be merged into master as soon as all testing is finished.

**Comment by FritzHeiden** [comment]
Testing is finished. The feature is now merged into the [DPCTF Test Runners master branch](https://github.com/cta-wave/dpctf-test-runner)

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden I will close this issue
