### ISSUE TITLE
Status given by TR when "the successful appending of the first CMAF fragment"

### ISSUE THREAD

**Issue by abdulwahabEDT** [cta-wave/dpctf-tests#80]
For 8.19 test Low-Latency (1): Initialization, the observation framework needs to recieve a notification from TR when first CMAF fragment is appended. Is it possible to pre-define the "status" that would be reported on the TR QR code? We need this information beforehand to start implementing the observation logic.

**Comment by yanj-github** [comment]
@FritzHeiden and @louaybassbouss This is not an immediate blocker but if we can agree the wording of the TR staus on QR code for this notification it would be helpful. Thanks.

**Comment by abdulwahabEDT** [comment]
Thanks @FritzHeiden
