### ISSUE TITLE
Missing parameters for updated DPCAT tests

### ISSUE THREAD

**Issue by abdulwahabEDT** [cta-wave/dpctf-tests#81]
On trying to run Buffer underrun and recovery (8.17) test the test fails due to missing parameters in the test-config.json.

Missing parameters include tolerance, frame tolerance and waiting_duration. Updated test-config.json doesn't have a parameter configuration for this test.
For Low-Latency Short Buffer Playback (8.22) test the parameter ts_max is missing along with tolerance and frame tolerance.
For Random access from one place in a stream to a different place in the same stream (8.23) test tolerance and frame tolerance are missing.

Since most observations use tolerance, frame tolerance and ts_max as parameters, it would be ideal if these parameters are included in the parameter list for all tests.

**Comment by louaybassbouss** [comment]
@abdulwahabEDT  can you provide default values for these parameters?

**Comment by gitwjr** [comment]
@FritzHeiden @louaybassbouss Does this require any changes to 8..17/.22/.23 in the DPCAT 21 spec? They have been added to the DPCTF Spec from DPCAT 21. If there are changes let me know and I'll add them to the main spec once approved.

**Comment by yanj-github** [comment]
@FritzHeiden Thanks for adding them.
I suggest it might be easiler to have 
    "ts_max": 120,
    "tolerance": 20,
    "frame_tolerance": 2
in "all" section, as they have same value and applicable to all the tests.
But it is up to you, it is just a suggestion.

**Comment by abdulwahabEDT** [comment]
Thanks @FritzHeiden for adding them. 

Closing this issue
