### ISSUE TITLE
DPCAT - truncated-playback-and-restart__splice_main.html is not working

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#83]
The test plays 10 seconds and stopped and time-ed out.

**Comment by FritzHeiden** [comment]
@yanj-github the test should now work as expected. Please try running it again and report any further issues

**Comment by yanj-github** [comment]
Re the truncate test; "Two CMAF Switching Sets are available for playback. Both Switching Sets shall use the same codec settings in order to avoid resets of the MediaSource and SourceBuffer." 

What is the suitable content to use? 
I don't have any problem with using main and ad for this test from the point of observation framework.
However, I think it had been agreed to use same test content as 8.8 test.
Truncated playback test requires two switching sets.
I am not sure if it required to generate another test content which is similar to 8.8 or just use 2 of same 8.8? 

second_playout and second_playout_switching_time is deifned but missing from the spec. 
What does "second_playout_switching_time" stating please?

**Comment by yanj-github** [comment]
> @yanj-github the test should now work as expected. Please try running it again and report any further issues

I am still having problme to run this test. I can only see 1st presentation then the test was halted. Can you test it on your end see if it is working please?

**Comment by FritzHeiden** [comment]
> What is the suitable content to use? I don't have any problem with using main and ad for this test from the point of observation framework. However, I think it had been agreed to use same test content as 8.8 test. Truncated playback test requires two switching sets. I am not sure if it required to generate another test content which is similar to 8.8 or just use 2 of same 8.8?

I don't really understand. The test is using the same content as 8.8, which is two separate switching sets.


> second_playout and second_playout_switching_time is deifned but missing from the spec. What does "second_playout_switching_time" stating please?

- second_playout: The playout parameter for the second switching set
- second_playout_switching_time: The play position at which to switch to the second switching set. Has to be smaller than total duration of the first switching set.

These parameters will be added to the spec aswell.


> > @yanj-github the test should now work as expected. Please try running it again and report any further issues
> 
> I am still having problme to run this test. I can only see 1st presentation then the test was halted. Can you test it on your end see if it is working please?

The second_playout parameter was off. I pushed a fix and it now works for me. Could you please try again?

**Comment by yanj-github** [comment]
@FritzHeiden In terms of the content I was trying to find out whether the 2 set of swithcing set shold be same duration or it can bee different. It sounds like the duration can be different. as it used seperate playout. I think this if fine with us.
I will check the test and will update you.

**Comment by yanj-github** [comment]
It is running fine and reached the end however the ended status report is missing.
Closing this issue we have seperate issue https://github.com/cta-wave/dpctf-tests/issues/87 to capture the point.

**Comment by yanj-github** [comment]
>     * second_playout: The playout parameter for the second switching set
> 
>     * second_playout_switching_time: The play position at which to switch to the second switching set. Has to be smaller than total duration of the first switching set.
> 
> 
> These parameters will be added to the spec aswell.
> 
@FritzHeiden  Just wondering who will be adding these to spec? If you havent created issue I would suggest to create it so that these parameters can be added to to spec.

**Comment by FritzHeiden** [comment]
> @FritzHeiden Just wondering who will be adding these to spec? If you havent created issue I would suggest to create it so that these parameters can be added to to spec.

I already handed them to @dsilhavy who will add them to the spec.
