### ISSUE TITLE
DPCAT - Parameters are missing from test-config.json file

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#84]
Please include all parameters that are stated on the spec 8.x.3:

- render_threshold for 8.19 Low-Latency (1): Initialization.
- mse_reset_tolerance  for 8.15 Source Buffer Re-Initialization (without changeType)
- gap_duration for 8.20 Low-Latency” Playback over Gaps

**Comment by FritzHeiden** [comment]
As most of the missing parameters are only relevant for the OF, I don't know what default values would make sense. Therefore I would kindly ask you to provide me with sensible value for them

**Comment by yanj-github** [comment]
gap_duration will be the duration of the gap in playback.

**Comment by yanj-github** [comment]
The following two parameter values should be get agreed by the TG. We can raise it on next call. 

- render_threshold for 8.19 Low-Latency (1): Initialization.
- mse_reset_tolerance for 8.15 Source Buffer Re-Initialization (without changeType)

**Comment by louaybassbouss** [comment]
@jpiesing  please add this as priority issue in the next DPCTF Call. @yanj-github what is missing here are the default values for the three configuration parameters:

- render_threshold (used only by OF)
   > Expresses the maximum allowed time between successfully appending the first CMAF fragment and the first media sample being visible or audible.
- mse_reset_tolerance (used only by OF)
  > Expresses the tolerance that is acceptable for a single MSE reset. This value is defined in milliseconds
- gap_duration (used by OF and TR). 
   > gap_duration: expresses the duration of the gap in milliseconds. Default should be set to the duration of a fragment. This value shall not be smaller than the duration of a single CMAF chunk and should be specified as a multiple of the chunk duration.

**Comment by jpiesing** [comment]
> @jpiesing please add this as priority issue in the next DPCTF Testing Call. @yanj-github what is missing here are the default values for the three configuration parameters:
> 
>     * render_threshold (used only by OF)
>       > Expresses the maximum allowed time between successfully appending the first CMAF fragment and the first media sample being visible or audible.
> 

Something like 0.2s may be a good aspirational target. I fear some devices may want something more like 0.5s.
This should be considered an informed guess and I'm happy to hear other opinions.

>     * mse_reset_tolerance (used only by OF)
>       > Expresses the tolerance that is acceptable for a single MSE reset. This value is defined in milliseconds
> 

Perhaps something like 300ms?
This should be considered an informed guess and I'm happy to hear other opinions.

>     * gap_duration (used by OF and TR).
>       > gap_duration: expresses the duration of the gap in milliseconds. Default should be set to the duration of a fragment. This value shall not be smaller than the duration of a single CMAF chunk and should be specified as a multiple of the chunk duration.

I don't consider myself qualified to make an informed guess on this one.

**Comment by louaybassbouss** [comment]
regarding `gap_duration`, default value according to spec is the `fragment_duration`, which is parsed from the MPD and provided to OF via tests.json.

**Comment by yanj-github** [comment]
The required parameters need to be set otherwise it will block OF from observing the tests. 
@louaybassbouss Jons suggestion seems reasonabile at this stage.  If nobody has any objection, can you define default value for the parameters as follows please? 
- render_threshold: 200ms for 8.19 Low-Latency (1): Initialization.
- mse_reset_tolerance: 300ms for 8.15 Source Buffer Re-Initialization (without changeType)

**Comment by FritzHeiden** [comment]
>     * render_threshold: 200ms for 8.19 Low-Latency (1): Initialization.
> 
>     * mse_reset_tolerance: 300ms for 8.15 Source Buffer Re-Initialization (without changeType)

I added the two parameters to the test-config.json.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I can see both are defined as requested.
