### ISSUE TITLE
DPCAT - incorrect contents are used

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#85]
The following tests are required to have Two CMAF Switching Sets  but only one is used.
- source-buffer-re-initialization-without-changetype
- source-buffer-re-initialization-with-changetype
- truncated-playback-and-restart

**Comment by FritzHeiden** [comment]
@yanj-github the truncate test now uses the content as suggested by the specification.

**Comment by yanj-github** [comment]
I think we agreed to use same test content as 8.8.
However thits test requires two switching sets.
I am not sure if we required to generate another test content which is similar to 8.8 or use 2 off same 8.8?

**Comment by louaybassbouss** [comment]
@yanj-github can we close this.

**Comment by yanj-github** [comment]
I am happy to close it assume that we are waiting to get right content for:

- source-buffer-re-initialization-without-changetype
- source-buffer-re-initialization-with-changetype

**Comment by jpiesing** [comment]
> I am happy to close it assume that we are waiting to get right content for:
> 
>     * source-buffer-re-initialization-without-changetype
> 
>     * source-buffer-re-initialization-with-changetype

We are waiting for some HEVC content for these two. They are currently de-prioritised for this reason.

**Comment by yanj-github** [comment]
Thanks @jpiesing 
It is fine to us, can you confirm for truncated-playback-and-restart test, splice_main and splice_ad are right streams to use please?

**Comment by louaybassbouss** [comment]
ok lets keep it open for now until content is available and everything is tested

**Comment by gitwjr** [comment]
Keep open until final content is created/tested.

**Comment by gitwjr** [comment]
The correct content is available.
