### ISSUE TITLE
DPCAT - random access from one place to a different place

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#88]
"random_access_from": 5,
"random_access_to": 30
So the presentation should render frames 1, 2, 3,..., 148, 149, 150, 901, 902, 903....., 1800. Can you confirm this is correct please?
I am expecting not to see frame number 151 and 152. However, the frame 151 and 152 are rendered. 
It seems like the device issue but any anyone else confirm on another device?
Can you check on other device please?

**Comment by louaybassbouss** [comment]
> "random_access_from": 5, "random_access_to": 30 So the presentation should render frames 1, 2, 3,..., 148, 149, 150, 901, 902, 903....., 1800. Can you confirm this is correct please? I am expecting not to see frame number 151 and 152. However, the frame 151 and 152 are rendered. It seems like the device issue but any anyone else confirm on another device? Can you check on other device please?

@yanj-github according to spec, you are right you shall not see the frames 151 152. But we may need to change the spec and add tolerance here. The reason for this is that you cannot trigger the seek in the test in a frame accurate manner. 

@jpiesing please add this for discussion in the next call

**Comment by yanj-github** [comment]
@louaybassbouss and @dsilhavy I can see more frames rendered however are we expecting a tolerance in both directions?

**Comment by jpiesing** [comment]
I agree with a tolerance around frame 150 as the seek may not be triggered in a frame accurate manner.
It's important that there not be a tolerance around 901.
Also please can someone double check that 901 is in the middle of a GOP as that is what needs to be tested.

**Comment by yanj-github** [comment]
I would suggest to add a parameter to test-config.json
"random_access_from_tolerance" in ms what should be a defaul value please? Is 200ms resonable?

**Comment by louaybassbouss** [comment]
For me is a reasonable value. if @jpiesing  agrees, then @FritzHeiden  `random_access_from_tolerance` can add it to json config. 

PS: I will be from now until end of August in vacation, but @FritzHeiden (Tests/Test Runner) and @dsilhavy (Questions related to the spec) will be available.

**Comment by jpiesing** [comment]
> For me is a reasonable value. if @jpiesing agrees, then @FritzHeiden `random_access_from_tolerance` can add it to json config.

I agree.

**Comment by yanj-github** [comment]
@louaybassbouss Do you think similar tolerance is required for truncated playback please?
"second_playout_switching_time": 5 but I noticed more frames rendered at then end of 1st preserntation before swithing to the 2nd.

**Comment by FritzHeiden** [comment]
The test-config.json does now contain the new tolerance parameter
