### ISSUE TITLE
Workflow to  New Testcases

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/dpctf-tests#89]
In GitHub, in the Observation Framework README, there is some information how to support new testcases depending how much they diverge from existing tests.

But, in terms of the overall workflow to author new testcases, it appears the basic steps to create a new testcase, goes something like the following. I was hoping there was more detailed documentation:

Create the HTML5 file, i.e., template.
Create an entry in a 'new' CSV file.
Run generate-tests.py
Optionally, create a new test folder to generate a dedicated test run without having to generate all testcases. Assuming that new CSV file is utilized.
All of this, is hosted and generated locally as opposed to downloading the generated testcases.

Can someone confirm this flow?

Thank you.

**Comment by louaybassbouss** [comment]
> In GitHub, in the Observation Framework README, there is some information how to support new testcases depending how much they diverge from existing tests.
> 
> But, in terms of the overall workflow to author new testcases, it appears the basic steps to create a new testcase, goes something like the following. I was hoping there was more detailed documentation:
> 
> Create the HTML5 file, i.e., template. Create an entry in a 'new' CSV file. Run generate-tests.py Optionally, create a new test folder to generate a dedicated test run without having to generate all testcases. Assuming that new CSV file is utilized. All of this, is hosted and generated locally as opposed to downloading the generated testcases.
> 
> Can someone confirm this flow?
> 
> Thank you.

@javierbarellano4v  this is correct. Let me put some details in your list:

- Create the HTML5 test template file (includes HTML+JS) similar to [sequential-track-playback.html](https://github.com/cta-wave/dpctf-tests/blob/master/sequential-track-playback.html). The template file includes placeholders for parameters like URL to audio and/or video MPDs. These will be replaced with the actual URLs in the generate script later. Example is [sequential-track-playback.html#L54-L55](https://github.com/cta-wave/dpctf-tests/blob/master/sequential-track-playback.html#L54-L55).
- Create an entry (or multiple entries) in a 'new' CSV file with URLs to audio and/or video MPDs. If your MPD includes audio and video AdaptationSets, you can use the same URL for both. The URL field can be the path to MPD in the content folder of the docker container or can be URL pointing to the content available online. The online content can be used during development or debugging purposes but should not be used in production to avoid higher latency while downloading the content during.
- Run `generate-tests.py my-new-file.csv` script which generates the tests in the generated folder only for entries in the new CSV file. 
- If you are developer of new tests, usually you need a simple way to debug a single dedicated new developed test without the need to setup of whole docker which includes the test-runner.  The only thing you need to do as developer of new tests in this phase is to serve the generated files via http/https and debug the test in browser. 
- Once the new tests are implemented and tested, you can add the entries to the CSV file [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv), generate the tests, push to git (in a feature branch) and test everything together using [dpctf-deploy](https://github.com/cta-wave/dpctf-deploy). Please make sure when you create the docker image to use the new feature branch of [dpctf-tests](https://github.com/cta-wave/dpctf-tests) and not the main branch. 

If you find this explanation helpful, we can put it in as new subsection "Develop new tests" in the readme.

**Comment by javierbarellano4v** [comment]
Perfect. This is very helpful.  Greatly appreciate expanding this list.  

Yes, put into a new section. Absolutely!

Thank you.

**Comment by FritzHeiden** [comment]
I added the steps to the [README.md](https://github.com/cta-wave/dpctf-tests/blob/master/README.md#creating-new-tests)
@javierbarellano4v Please feel free to close this issue if it is solved

**Comment by javierbarellano4v** [comment]
Thank you very much.  I will close.
