### ISSUE TITLE
Download and serve media content locally (in local network)

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-tests#9]
We agreed few months ago, that the media content should be downloaded and served locally to avoid network latency and other issues that may affect the tests. We need to implement a script that download the media content and serve it locally via HTTP (with proper configuration e.g. CORS, etc.). The script can be executed when while starting the docker container and if content is missing, it will first be downloaded before starting any test.

**Comment by FritzHeiden** [comment]
Here a possible workflow to approach this:

1. Execute script to download the content to a local directory
2. Add the directory to the `docker-compose.yml` to map it into the container
3. Run or restart the container for the changes to take effect
4. When updating to a newer image, leaving the `docker-compose.yml` as it is still integrates the content, no redownloading needed

A requirement for this would be in the CSV generation script to download the MPD and change its URL accordingly, while the MPD only uses relative paths, so the content is fetched from the same origin.

This way it is sufficient to execute the download script ones across multiple versions. Only if a release contains breaking changes in this regard the content might have to be downloaded again.

**Comment by louaybassbouss** [comment]
@FritzHeiden FYI:
- Each single test content will be provided as Zip file -> see issue [cta-wave/Test-Content-Generation#19](https://github.com/cta-wave/Test-Content-Generation/issues/19)
- Available test content is listed in single file which will be the entry point for the download script -> see issue [cta-wave/Test-Content-Generation#20](https://github.com/cta-wave/Test-Content-Generation/issues/20)

**Comment by louaybassbouss** [comment]
@jpiesing FYI we will proceed on this once the content is provided as Zip files. see [Test-Content-Generation/issues/19](https://github.com/cta-wave/Test-Content-Generation/issues/19)

**Comment by yanj-github** [comment]
I would like to get an update once this is done please?

**Comment by jpiesing** [comment]
> I would like to get an update once this is done please?

@yanj-github So far we haven't prioritised this. Should it be prioritised? If you think so, please bring it up in the regular call on Tuesday 16th.

**Comment by yanj-github** [comment]
> 
> 
> > I would like to get an update once this is done please?
> 
> @yanj-github So far we haven't prioritised this. Should it be prioritised? If you think so, please bring it up in the regular call on Tuesday 16th.

I will try to find a way to work around this, if not working and I am blocked I will raise it in next meeting to be prioritised, Thanks.

**Comment by louaybassbouss** [comment]
This issue ist about downloading and serving the content locally. 

The Downloading part is blocked by this issue https://github.com/cta-wave/Test-Content-Generation/issues/19. 
The serving part is work in progress. When this is ready, you can put content in a shared folder and this will be served via the test runner. We need this for example to serve encrypted content to finalise the implementation of encrypted tests.

**Comment by yanj-github** [comment]
I can work around this by downloading the contents manually, regarding the serving part I can move this inside the docker so that it can be served by the test runner until we get the serving part done.

**Comment by louaybassbouss** [comment]
@yanj-github: we (thanks @FritzHeiden) added a new section to the [dpctf-deploy README](https://github.com/cta-wave/dpctf-deploy/#mapping-new-content-into-the-container) with more details how to map a folder on the host machine which includes local/downloaded content to be served via the Test Runner HTTP Server. Once the download script is ready, the content from Akamai CDN will be downloaded in that folder. But you can put your own or manual downloaded content as well.

**Comment by FritzHeiden** [comment]
I implemented a script to download test content based on a json file. I added documentation about it to the dpctf-tests README.md.

**Comment by yanj-github** [comment]
I have a question about the test-group folder from readme. Does test group contains test html files or it contains contents is not clear to me

**Comment by FritzHeiden** [comment]
> 1. Execute script to download the content to a local directory
> 2. Add the directory to the `docker-compose.yml` to map it into the container
> 3. Run or restart the container for the changes to take effect
> 4. When updating to a newer image, leaving the `docker-compose.yml` as it is still integrates the content, no redownloading needed

This workflow is now implemented in the [dpctf-deploy](https://github.com/cta-wave/dpctf-deploy) repository. Executing the `import.sh` script will download the contents defined in the `database.json` into the content directory, which is mapped into the container.

**Comment by yanj-github** [comment]
Yes @louaybassbouss  "download-content.py" works fine to me. Did not tried import.sh but I think it calls to download-content.py anyway isnt it?

**Comment by louaybassbouss** [comment]
> Yes @louaybassbouss "download-content.py" works fine to me. Did not tried import.sh but I think it calls to download-content.py anyway isnt it?

yes it is the same thanks for feedback I will close this issue
