### ISSUE TITLE
stall_tolerance_margin for low_latency_playback_over_gaps.html is missing

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#91]
Can you add a missing parameter "stall_tolerance_margin" for test "low_latency_playback_over_gaps.html" please?

**Comment by louaybassbouss** [comment]
what is the default value?

**Comment by yanj-github** [comment]
I don't think I am qualified to define default value for this. 
@jpiesing can you provide default values for this parameter please?
This will be used by OF to observe duration check with additional tolerance for this specific test.

**Comment by jpiesing** [comment]
> I don't think I am qualified to define default value for this.
> @jpiesing can you provide default values for this parameter please?
> This will be used by OF to observe duration check with additional tolerance for this specific test.

I have no idea and have no idea who would have any idea.

**Comment by dsilhavy** [comment]
The problem is that most platforms will not reach `range.end(0)` and stall before. We introduced this parameter in dash.js: 

````javascript
@property {number} [threshold=0.3]
Threshold at which the gap handling is executed. 
If currentRangeEnd - currentTime < threshold the gap jump will be triggered.
For live stream the jump might be delayed to keep a consistent live edge.
Note that the amount of buffer at which platforms automatically stall might differ.
````

I suggest to use `0.3` seconds for this test as well but in both directions. That way the stall event can be thrown either `0.3` seconds before `range.end(0)` or `0.3` seconds after `range.end(0)` was reached.

**Comment by yanj-github** [comment]
I have run a quick check on one of my device. The stall is around 200ms before the range end, so I think 300ms sounds reasonable. Thanks @dsilhavy to point out stall can be in both directions.

**Comment by louaybassbouss** [comment]
Thanks @dsilhavy, @FritzHeiden can you please add this parameter with 300ms as default value.

**Comment by FritzHeiden** [comment]
@yanj-github The parameter is now included in the test-config.json

**Comment by yanj-github** [comment]
Thanks @FritzHeiden  and @louaybassbouss I can see the paramter is included.
