### ISSUE TITLE
DPCAT - fault in mezzanine QR code

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#92]
The last mezzanine QR code reports 00:60:00 instead of 01:00:00.
I remember this issue has been corrected before but it seems the issue is back again. 
Sorry to raise it here, but can you @louaybassbouss @rbouqueau @nicholas-fr help with this issue please?
OF won't take 00:60:00 as a valid time data.

**Comment by louaybassbouss** [comment]
@yanj-github I propose to raise the issue in the mezzanine repo if the QR codes within the video content are affected. Or do you mean the QR codes generated by JavaScript?

**Comment by yanj-github** [comment]
raised on mezzanine repo https://github.com/cta-wave/mezzanine/issues/50
