### ISSUE TITLE
generating a new testcase 

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/dpctf-tests#93]
While attempting to generate a new testcase using the Python script, the following occurred in a Windows Powershell:

![image](https://user-images.githubusercontent.com/97479879/185842990-e4febdbe-9caf-4e4f-8986-d44df7f183c8.png)

I downloaded the code from https://github.com/cta-wave/dpctf-tests and created a new template (html file) and a new text file with a single entry in CSV format:

    "my-sequential-track-playback","https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t1/2022-01-17/stream.mpd","","avc_15_30_60-online"

It appears there is an issue in writing the new file. 

It is able to create a subdirectory for the test, e.g., 

        C:\Users\javier.arellano\Downloads\dpctf-tests-master\tests\avc_15_30_60-online

Thank you.

**Comment by javierbarellano4v** [comment]
I was able to successfully generate a testcase and corresponding folder using the python script in a Linux VM (as opposed to creating in Windows OS).

Now, to check it out. 

The generated HTML file references JS libraries, etc. not co-located with the generated HTML.

Unless you incorporate the HTML file(s) into the usual generated folder and an corresponding entry into the test CSV file, respectively then recreate docker image, not clear how to test stand-alone.

**Comment by FritzHeiden** [comment]
What python version do you use? For me all the files are copied to the destination directory (lib)

**Comment by gitwjr** [comment]
@javierbarellano4v 
Please provide an update on this issue.

**Comment by javierbarellano4v** [comment]
Fixed my problem. Please close issue.
