### ISSUE TITLE
delay in "waiting" status report

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#94]
For buffer underun and Short Buffer Playback test OF relay on the waiting status reported to calculate playback duration match. 
Therefore we assume the status report is accurate. However, we have noticed that the status is not reported on time.
There is a delay in reporting "waiting" status. 

camera frame | content ID | media time | frame | frame rate | status | action | current time | delay 
-- | -- | -- | -- | -- | -- | -- | -- | --
4496 | L1 | 34833 | 1045 | 30 |   |   |   |  
4496 |   |   |   |   | playing | play | 34.80394 | 7
4497 | L1 | 34833 | 1045 | 30 |   |   |   |  
4497 | L1 | 34867 | 1046 | 30 |   |   |   |  
4497 |   |   |   |   | playing | play | 34.80394 | 7
4498 | L1 | 34867 | 1046 | 30 |   |   |   |  
4498 |   |   |   |   | playing | play | 34.80394 | 7
4499 | L1 | 34867 | 1046 | 30 |   |   |   |  
4499 |   |   |   |   | playing | play | 34.80394 | 7
4500 | L1 | 34867 | 1046 | 30 |   |   |   |  
4500 |   |   |   |   | playing | play | 34.80394 | 7
4501 | L1 | 34867 | 1046 | 30 |   |   |   |  
4502 | L1 | 34867 | 1046 | 30 |   |   |   |  
4502 |   |   |   |   | waiting | play | 34.84919 | 11
4503 | L1 | 34867 | 1046 | 30 |   |   |   |

**Comment by louaybassbouss** [comment]
@yanj-github we report the `waiting` status immediately after we receive the "waiting" event from the underlying video. If you notice a delay, most probably is caused by the UA agent.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss to confrim the "waiting" event gets reported promptly. 
As I only tested on one device it might be a device issue then. 
Happy to close it, @louaybassbouss are you fine with it please?
