### ISSUE TITLE
Merge DPCAT into master branch

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/dpctf-tests#95]
From our side, the dpcat branch reached a state which is stable enough to merge it into the master branch.
@yanj-github Do you have any issues with the dpcat tests that would speak against this, or are you fine with that?

**Comment by yanj-github** [comment]
@FritzHeiden There is still an open issue for turncated test otherwise others (7 tests that they are in scope) are fine. 
I guess they can be merged if you are happy to make fixes to main any further changed if required.

**Comment by gitwjr** [comment]
Waiting for resolution to Truncated Test.

**Comment by FritzHeiden** [comment]
Truncated test no works properly. Waiting for #96 to resolve with new content

**Comment by FritzHeiden** [comment]
Merged dpcat branch into master
