### ISSUE TITLE
Tolerance for Visible Video Shifts observation

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#97]
This issue is outside the scope of the DPCAT2022 release. 
Tolerance for Visible Video Shifts observation required to be agreed and configured. 
Shall we define it on “test-config.json” file, same as we did for other tolerances please?

I suggest calling it “video_shifts_tolerance” and what is the best default value please? 
It should be number in pixel based on fullHD. How about 20, or any other suggestions please?

**Comment by yanj-github** [comment]
Thanks @louaybassbouss to be honest I don't know who can help with default value. @jpiesing will you be able to help with this please?

**Comment by rcottingham** [comment]
Hi @haudiobe, linked to the recent spec updates regarding the Video Shifts observation, do we need to specify a pixel tolerance? Currently we have it set to (an arbitrary) 20 pixels. Any thoughts on what the value should be, and if it should be included in the spec (s8.5.5.2 / 8.10.5.2)?

**Comment by jpiesing** [comment]
I would have said the value should be somewhere around 0.5 pixel or even less.

**Comment by yanj-github** [comment]
@jpiesing and @nicholas-fr could you please help to provide a faulty test material so that we can exercise the testability please?
A faulty Mezzanine with Visible Video Shifts in there so that we can compare the detected location data.

**Comment by gitwjr** [comment]
@nicholas-fr Was the test material generated?

**Comment by yanj-github** [comment]
This observation has been removed and not present anymore in the latest version of spec.
If this observation is not required anymore then we don’t need to do further analysis.

**Comment by gitwjr** [comment]
Most likely error is undetectable.
