### ISSUE TITLE
aditional configuration is required for audio

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#98]
This issue is required for audio observation which is not in scope for the current release.
Aditional configuration is required for audio from tests.config file. 

- Source from mpd: to be used by OF to check which audio mezzanine is used.
- audioSamplingRate
- SegmentTimeline

**Comment by louaybassbouss** [comment]
@yanj-github  for all observations config, please put concrete parameter names, default values and for which tests are relevant. We can then add them to the test-config.json

**Comment by yanj-github** [comment]
@louaybassbouss this is seperate to test-config.json but tests.json file.
So we need extra parameters passed from mpd file to tests.json file. For all the contents that is linked please?

**Comment by FritzHeiden** [comment]
audioSamplingRate and SegmentTimeline are now included in the tests.json

**Comment by yanj-github** [comment]
Thanks @FritzHeiden will you be able to take <Source>value</Source> from mpd and present it on tests.json file please?

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I can see all of the followings are presented in tests.json
    Source from mpd: to be used by OF to check which audio mezzanine is used.
    audioSamplingRate
    SegmentTimeline

**Comment by yanj-github** [comment]
@FritzHeiden Sorry that I had to add one more, can you kindly add timescale on SegmentTemplate section from mpd please?
Thank you.

**Comment by FritzHeiden** [comment]
@yanj-github timescale is contained in `tests.json`
