### ISSUE TITLE
Configure required tolerance to A/V sync

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#99]
Re;  the A/V sync observation that is defined in device capability spec as follows:
"The mediaTime of the presented audio sample matches the one reported by the video currentTime value within the tolerance of +40 mS / -120 mS.  "

Can we defined the tolerance in test-config.json file please?

**Comment by louaybassbouss** [comment]
@yanj-github yes but we need more details. What are the names of the parameter?  For which tests?

**Comment by yanj-github** [comment]
A/V sync observation applys to all section 9 tests. As they are all same can we set this on section for "all", let me know if there is any objection please?
I suggest to set value as follows:
    e.g: "av_sync_tolerance": [40, -120],

**Comment by FritzHeiden** [comment]
Added the parameter to the test-config

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I can see that the av_sync_tolerance are definied now.
